### ISSUE TITLE
Protect private keys with your public Key in Display Keys

### ISSUE THREAD

**Issue by MaikoID** [mailvelope/mailvelope#100]
Hi, I was wondering it will be nice if I could improve my security cryptographying  my private key with my public key. When the user want to see the private key he must enter the private keys password. 

If so, we are safe when other people use your chrome user, or they have admin privileges in your PC and can copy your Chrome/Firefox profile.

I'm trying to improve it in my fork, but after my first, second, third, .. sight I can confirm that I have a lot of work to do and I was wondering if this approach is valid for more users.

Bye, and nice work.

**Comment by toberndo** [comment]
That would require the private key which is inside the keyring to decrypt the keyring...
Tracking keyring encryption in issue: https://github.com/mailvelope/mailvelope/issues/57
