### ISSUE TITLE
Get contacts and subject from pop up compose mail window

### ISSUE THREAD

**Issue by 2624789** [mailvelope/mailvelope#104]
Is there any way for automatically adding to the contacts mail form the mails detected from keys when click on transfer?

It would be better if the user has the posibility for adding in this window the subject too, this way, the only thing needed after transfer will be just click send.

PS: How can I tag this as an enhancement?

**Comment by toberndo** [comment]
Recipient transfer for Gmail, Outlook.com and Yahoo is now available in latest release.
