### ISSUE TITLE
Cannot decrypt messages from adele@gnupp.de

### ISSUE THREAD

**Issue by novahyth** [mailvelope/mailvelope#112]
I'm quite new to e-mail encryption / OpenPGP. As a GMail user, I wanted to give Mailvelope a try.

To test the certificates and especially the decryption, I sent e-mails to the robot adele@gnupp.de containing my public key (once as attachment, another time in the mail body).

I got e-mails back both of the times but cannot decrypt the content with Mailvelop. When I enter my password, it says "Error! Could not decrypt this message".

**Comment by rugk** [comment]
Is this issue still valid? Because your milestone v0.7 was reached long time ago and this issue is stioll open.

Additionally I was able to send, receive and decrypt a message to adele@gnupp.de with the DSA public key `DD87 8C06 E8C2 BEDD D4A4 40D3 E573 3469 92AB 3FF7`.

**Comment by toberndo** [comment]
Should be fixed. Closing.
