### ISSUE TITLE
Decrypted text should have URLs turned into clickable links

### ISSUE THREAD

**Issue by holloway** [mailvelope/mailvelope#137]
When people email me URLs gmail renders them as clickable links.

But a mailvelope decrypted message is just displayed as plain text, so any URLs in there need to be copy and pasted into the address bar and doing that makes me feel like some kind of filthy caveman using IE3 for Windows 3.11.

I guess that we should do a lot of what Gmail does in terms of making relevant text clickable.

**Comment by toberndo** [comment]
Fixed in: https://github.com/mailvelope/mailvelope/releases/tag/v3.1.0
