### ISSUE TITLE
`auto_add_primary` should be enabled by default

### ISSUE THREAD

**Issue by Noleli** [mailvelope/mailvelope#143]
For nontechnical users, I would think that expected behavior is that you should be able to read your own sent mail. I can imagine all the support requests I'll get from friends who I will (hopefully) get to use mailvelope. Thanks!

**Comment by toberndo** [comment]
> Could be implemented as: if no other private key is in key ring and private key gets imported or
> generated -> set primary key.

This feature is available for quite a while.
