### ISSUE TITLE
Cannot decrypt email

### ISSUE THREAD

**Issue by resistorsoftware** [mailvelope/mailvelope#151]
Mailvelope keychain contains a public key from Bob. Bob sent me an encrypted email he encrypted with his private key. 

When I go to decrypt this email using Gmail, I get the message:

Error! No private key found for this message. Required private key IDs: 51A5BB5DFAD7C0A3 or BA7BD6CDA94A3030 or 90B9C29D804ABB91

I notice Bob's Public key has a subkey that is 90B9C29D804ABB91

Did Bob do something wrong?

**Comment by webmaven** [comment]
I just encountered this issue with v0.12.0 on Chrome and Gmail. I was sent a message encrypted with two of my public subkeys, but Mailvelope is not using them even though they have been imported.

**Comment by AndreGeddert** [comment]
I got the same Problem here with Firefox 42, Mailvelope 1.2.3. Webmailer is Rouncube 1.1.3.
My subkey is shown with exact ID in Mailvelope Key Management as ELG (Elgamal) Subkey but Mailvelope says it cannot find the key with the ID. Like in resistorsoftware's screenshot.

**Comment by AndreGeddert** [comment]
Ok, after some fiddling around i found the problem. I imported my Key for another provider in the Mailvelope key management (for web.de). Then i imported the key while "mailvelope" as provider was selected, the key was imported to the right place and now im able to decrypt with my Elgamal subkey.
