### ISSUE TITLE
Clear a Key Migration Error?

### ISSUE THREAD

**Issue by zmanian** [mailvelope/mailvelope#176]
I got a key migration error on a public key b/c of some HTML tags that got picked up along the way like this

```
-----BEGIN PGP PUBLIC KEY BLOCK-----</br>
Version: GnuPG v2.0.21 (MingW32)</br></br>
```

It was easy to deal with. How do I clear the error from the options UI?

**Comment by toberndo** [comment]
Key migration code has been removed, so this should not happen any more. Closing.
