### ISSUE TITLE
Cannot call method 'toHex' of undefined

### ISSUE THREAD

**Issue by felipe1982** [mailvelope/mailvelope#179]
I sent myself a message using [openkeychain](https://github.com/open-keychain/open-keychain) to my gmail, and I received an error trying to open it with mailvelope 0.8.0 on chrome Version 33.0.1750.154 m

Error reads:
Error! Cannot call method 'toHex' of undefined

![image](https://cloud.githubusercontent.com/assets/275621/2652194/8be4bda6-bfa4-11e3-93e6-69d85c7e03ce.png)

**Comment by toberndo** [comment]
I'm clearing old issues related to OpenPGP.js because library has improved a lot in the last 2 years. Please reopen if you can reproduce the issue with latest Mailvelope release.
