### ISSUE TITLE
Fail to decrypt a message

### ISSUE THREAD

**Issue by whudson** [mailvelope/mailvelope#181]
I get an error while trying to decrypt a message. After I put in the password for my key.

Error! Could not decrypt this message: Error: Error during parsing. This message / key is probably not containing a valid OpenPGP format.

Message decrypts fine in gpg4usb.

**Comment by vaisov** [comment]
Is it still unsolved? Any way to workaround this? I don't want to switch to Thunderbird

**Comment by toberndo** [comment]
Fixed in latest beta: https://github.com/mailvelope/mailvelope/releases/tag/v0.12.0b1
v0.12.0 will soon be released.

**Comment by vaisov** [comment]
Thanks! It works!
