### ISSUE TITLE
Add sign & encrypt option

### ISSUE THREAD

**Issue by tearvisus** [mailvelope/mailvelope#184]
I think that most people who encrypt their mail usually sign it as well, so it would be useful to add a button which signs and encrypts the message at the same time, like by using:

```
gpg --armor --sign --encrypt 
```

This produces a nice output which can be decrypted and verified by a single command, while the two step procedure (first sign, then encrypt) requires two operations.

**Comment by ittaiz** [comment]
Hi,
First of all thanks for this awesome project! Looks really interesting.
Can I ask why is this issue closed if the feature isn't out yet?

**Comment by toberndo** [comment]
@ittaiz Think it's still open? #183 is closed...

**Comment by ittaiz** [comment]
You're right, I was indeed mistaken.
Do you have any idea if/when this feature will be in the main branch?

**Comment by toberndo** [comment]
@ittaiz Ok, should see this soon in the main branch.

**Comment by guilhermesimoes** [comment]
Can't wait for this!

**Comment by ittaiz** [comment]
excellent, thanks!

**Comment by ittaiz** [comment]
Any update?

**Comment by ittaiz** [comment]
Any update? (an update saying you'd like me to stop asking is also ok)

**Comment by toberndo** [comment]
No update as of now. Will post here once the feature hits a beta release.

**Comment by HibikiTaisuna** [comment]
+1 for this feature request

**Comment by ittaiz** [comment]
Hi,
Is there something we can do to help this feature progress?

**Comment by dmp1ce** [comment]
I still use GPG on the command line because this feature is not completed. When will it this feature be added?

**Comment by jkrauska** [comment]
+1

It seems to have been over a year since this was completed in a dev branch. Can you share what's holding it back from the main release?

**Comment by richardbuehler** [comment]
Hi, I tested mailvelope with WEB.DE today: encrypt&sign worked well.
Does that mean that WEB.DE isn't using the main branch?

**Comment by elwiley** [comment]
I have tried many times now and am not getting secure communication. I can sign a message and the recipient is able to confirm my identity, which addresses message integrity. Or I can encrypt the message, which addresses message confidentiality. I have tried alternating the order with both encrypting and signing, but it seems that encrypting the message precludes getting a digital signature. It looks like Thunderbird, GnuPG, and ENIGMAIL are still the best way to go.

**Comment by pianist** [comment]
Any updates? Why this feature is not in the main branch? :(

**Comment by andrey-utkin** [comment]
Up. What is the problem with merging? May some donations help? :)

**Comment by tcosenza** [comment]
Updates?

**Comment by pianist** [comment]
Are devs reading this topic?

**Comment by stonky** [comment]
:+1: 

It's a pity that this excellent piece of software is lacking this support; particularly since some of the dev work seemed to have been finished. I hope it gets some more focus soon.

Also requires signature verification as a recipient actor too, of course.

There's a work-around for signing; just copy the signed text, "undo", then paste the signed text over the original text and transfer. But no signature verification available at the recipient end.

Although it may not be a standard, as others have said sign and encrypt is fundamental best practice for many.

Fingers crossed :)

**Comment by Ekleog** [comment]
BTW, this workaround appears to break when trying to hand-check the signature using gnupg. Any news as to when this feature is expected? Is there anyway I could help? I personally use enigmail, but trying to make people I know use OpenPGP will be achieved only through operations such as mailvelope, and it not supporting sign&encrypt is *the* reason why I haven't asked them to install it yet... :/

**Comment by toberndo** [comment]
Sign & encrypt is available in Mailvelope v1.6.0
