### ISSUE TITLE
No decrypt of images in rich text emails?

### ISSUE THREAD

**Issue by Pe4nutG4llery** [mailvelope/mailvelope#187]
The message editor supports drag-and-drop insertion of image files, in-line with the text.  (Good feature, btw.  That works fine for composition.)

Encrypting the resulting rich text messages appears to work fine.  The image data seem to be encrypted along with the text, based on the size of the resulting ciphertext.

However, when I decrypt the message, only the text remains.
The image is either not decrypted, or it simply isn't rendered in the Message display window.
No error messages are shown.
And, after this, the Copy to Clipboard button doesn't work.  Clicking it results in the message text being highlighted.  But nothing is actually copied to the clipboard.  No text.  And No image.   (I have not tried decryption with any other client eg. Enigmail.)

Is this related to multipart MIME support, or to Issue #123 "Decrypt inline mode for Firefox"?

I'm using the plugin in Firefox 28.0.  So far I've only used it to send test messages back and forth between a Gmail account and a Yahoo account, using a 1024 bit GPG-generated RSA keypair.

**Comment by toberndo** [comment]
We removed rich text editor due to issues with PGP/MIME (can't be supported in the standard mode of Mailvelope (Gmail, Yahoo, etc.)).
