### ISSUE TITLE
encrypt performance with DSA key in Firefox

### ISSUE THREAD

**Issue by rollerblader** [mailvelope/mailvelope#197]
I've noticed multi-minute encryption times if one of the recipients has a DSA key and I'm using Firefox under windoz7. It's far faster in Chrome. This may be an OpenPGP.js issue rather than Mailvelope, but I thought I'd pass it along anyway. If all the public keys are RSA, everything is fine.

Great product! thanks.

**Comment by barrydegraaff** [comment]
Seen that DSA problem as well, but it is also in Chrome

**Comment by toberndo** [comment]
BTW, with Mailvelope 3.0 you can also use the GnuPG integration which is probably faster.
