### ISSUE TITLE
 Ascii armor integrity check on message failed: '' should be 'PEFA'

### ISSUE THREAD

**Issue by edouard-lopez** [mailvelope/mailvelope#198]
Hi,
I'm trying to use Mailvelope during a cryptoparty and I can't import some of my friends key with the following error :

> Import Error! Unable to read one public key: Ascii armor integrity check on message failed: '' should be 'PEFA'

I don't find anything related to `PEFA` and `GPG` on Google. Any idea ?

[related issue on Mailvelope project](https://github.com/openpgpjs/openpgpjs/issues/226).

**Comment by towr** [comment]
I got this error when the `=` before the checksum was missing. After adding it the key imported fine.
