### ISSUE TITLE
Signing with encrypted subkeys (and without master key) doesn't work?

### ISSUE THREAD

**Issue by numinit** [mailvelope/mailvelope#199]
I tried installing Mailvelope and importing my private key. I don't have my master key in my keyring. Here's the output of `gpg -K`.

```
$ gpg -K
sec#  4096R/2FC1C1FF 2014-04-11
uid                  Morgan Jones (GPG identity key) <me@numin.it>
ssb   4096R/213459B1 2014-04-11
ssb   4096R/A18D9C40 2014-05-03
```

When I go to sign a message using this key, I **always** get the "Wrong password" error. I imported the key using the `--export-secret-subkeys` option.

What's going on here? I built Mailvelope from cloned source (revision `78ad87c`).

**Comment by neurolit** [comment]
Hi!
As openpgpjs/openpgpjs#251 is solved, is it possible to reopen this issue?

**Comment by neurolit** [comment]
(in fact, it could be that 04de523f75b959d8284473d3d81c23a664fe2414 solved this issue)

**Comment by toberndo** [comment]
@neurolit Yes, OpenPGP.js 4.5.1 in Mailvelope 3.2 comes with support for the export-secret-subkeys feature. But I have not tested yet.
