### ISSUE TITLE
Mailvelope does not work with MyKolab.com

### ISSUE THREAD

**Issue by oova** [mailvelope/mailvelope#203]
I followed the recommended procedure described [here](https://www.mailvelope.com/help#watchlist) to use Mailvelope with the MyKolab.com webmailer, but I did not find either Mailvelope's compose button when composing a new email, nor the decryption overlay when opening an encrypted email. The webmailer was successfully added to the watch list, where I can see a new entry (scan="true", frame= "*.webmail.mykolab.com"), but I assume something else went wrong.

I'm aware that this issue might not be easy to reproduce as MyKolab.com is a paid service, but I would appreciate any feedback.

**Comment by alecpl** [comment]
works for me.
