### ISSUE TITLE
Watch list only picks up the site immediately after the "add page"

### ISSUE THREAD

**Issue by d3adb33f** [mailvelope/mailvelope#206]
The watch list does not work with some webmails. I was only able to get it to work immediately after add the page to the watch list, after reloading the page mailvelope does not work anymore and stops processing the pgp armor (the webmail in question is the protonmail.ch).

**Comment by t2d** [comment]
As described in #22 I see the same behaviour today.

**Comment by toberndo** [comment]
This is probably fixed in recent releases of Mailvelope. Please reopen if problem persists.
