### ISSUE TITLE
Add support for SeaMonkey

### ISSUE THREAD

**Issue by unix-junkie** [mailvelope/mailvelope#211]
Please add support for [SeaMonkey](http://www.seamonkey-project.org/).

Right now I'm running the latest version (2.26), and it declares FF 29 compatibility:

    Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:29.0) Gecko/20100101 Firefox/29.0 SeaMonkey/2.26

At the same time, I was able to successfully add _mailvelope_ to not that recent FF 28, meaning the extension should work seamlessly with SeaMonkey as well.

**Comment by toberndo** [comment]
We support latest Firefox ESR release. If SeaMonkey is based on latest Firefox release then I don't see a problem. But we are not planning to add official SeaMonkey support (in the sense testing new releases etc.).

**Comment by unix-junkie** [comment]
Thanks for the feedback.

What I meant was simply adding a SeaMonkey-specific section to `install.rdf`, as described [here](https://developer.mozilla.org/en-US/Add-ons/SeaMonkey_2), so that SeaMonkey also sees Mailvelope as its native extension.

Can this be implemented?
