### ISSUE TITLE
Firefox Crash When Viewing .asc in Gmail Preview

### ISSUE THREAD

**Issue by Nrbelex** [mailvelope/mailvelope#212]
Steps to Reproduce:
1. With Mailvelope enabled, receive an E-mail with an attached signature.asc.
2. Click on the attached signature.asc, bringing up a preview in the Gmail window in Firefox.
3. Firefox crashes.

Expected behavior = signature verification? Not sure how that's supposed to work...

Thanks

**Comment by toberndo** [comment]
Extract frame stops now the loop after max nesting: https://github.com/mailvelope/mailvelope/blob/master/src/content-scripts/extractFrame.js#L43
So this crash should be fixed.
