### ISSUE TITLE
Compose - Missing textarea in plugin window

### ISSUE THREAD

**Issue by StanDog** [mailvelope/mailvelope#217]
Issue with Firefox (Windows) version 31 with Mailvelope 0.9 on Google Mail:

Often when clicking on Mailvelope's small compose button (which opens a plugin popup) the textarea where the text will be entered does not show up. Here is a screenshot: http://i.imgur.com/VE1jbEI.png

I can reproduce this error everytime. It seems that the problem can be circumvented by setting the cursor to the subject field before clicking Mailvelope's compose button. Then the textarea appears and the message can be typed in. Or if opening Firefox' browser console window (Ctrl + Shift + J).

I examined the code in the background and it seems that the DIV container (DOM ID "rte-box"), which contains the textarea field, has the CSS attribute "display: none" for some reason. If I deactivate / overwrite the CSS instruction manually, the textarea appears back again. Screenshot: http://i.imgur.com/YbUl6gv.png

Can somebody reproduce this too?

Firefox is a fresh installation, no other plugins.

**Comment by toberndo** [comment]
Cannot reproduce and lot of changes to the editor since this issue was created. Please reopen if you still run into this issue.
