### ISSUE TITLE
Signature verification fails when message is encrypted

### ISSUE THREAD

**Issue by cajuntechie** [mailvelope/mailvelope#218]
If I send an unencryted but signed message to a Mailvelope user, Mailverlope can successfully verify the signature. However, if the message is both encrypted and signed, there is no indication from Mailvelope that the message was ever signed.

In the reverse, when I receive a signed and encrypted message from a Mailvelope user and decrypt it using something like Enigmail or GPGShell, it will successfully decrypt the message but show the signature cleartext. I have to click decrypt a second time to perform signature verification. This ONLY happens when receiveing message from Mailvelope users.

**Comment by stevewalker61** [comment]
Still the same problem!
Writing an (first) signed, then encrypted mail (from mailvelope to mailvelope). Recipient can encrypt but not verify! Rig the Signature does mailvelope not recognize! Only signed messages are ok.

Is there a way to fix it? Do you still work on the problem?!

**Comment by toberndo** [comment]
Mailvelope now supports signed & encrypted messages and verification of those messages for major providers. What is described in this issue as first cleartext sign a message and then encrypt is a procedure that is not supported by many (if any?) PGP implementations.
