### ISSUE TITLE
Feature: Support Outlook Web Access (OWA)

### ISSUE THREAD

**Issue by ahill00** [mailvelope/mailvelope#22]
It would be nice if Mailvelope could work with OWA, it may be implementable as Outlook.com is supported.

**Comment by stevemit** [comment]
In Firefox, I cannot read encrypted messages in OWA.  In Chrome, I can read and send encrypted messages.  

In Chrome, when I reply to an encrypted message, the ciphertext of the original message is quoted, instead of the plaintext.  Is that how Mailvelope works, or is it an OWA bug?

**Comment by t2d** [comment]
Works for me with Chrome and Firefox.

**Comment by monperrus** [comment]
Yes, it would be great to have full support for Microsoft Exchange OWA webmail. Many companies use that webmail.
