### ISSUE TITLE
gpgtools generated Key import sucessful decryption of message -> wrong password

### ISSUE THREAD

**Issue by JTheilmann** [mailvelope/mailvelope#226]
I have imported an gpgtools keychain 4096 RSA key into mailvelop and everything worked perfectly however if I want to decrypt a mail with my passphrase it says wrong passphrase even if I copy it doesn't work :( I always get the error "wrong password"

**Comment by patcon** [comment]
Did you remove your master key?
Ref: https://github.com/mailvelope/mailvelope/issues/199

**Comment by drzraf** [comment]
Same behavior.
Install extension, export existing gpg key, import key inside MailVelope, try to decrypt an email => fails.

**Comment by toberndo** [comment]
Due to update to OpenPGP.js 4.2 these compatibility issues should be fixed. Please reopen if problem persists.
