### ISSUE TITLE
Allow setting expiration time on key generation

### ISSUE THREAD

**Issue by D4nte** [mailvelope/mailvelope#233]
On Windows 7/Chrome Version 37.0.2062.124 m/mailveloppe v0.10.2

On Generate Key > Advanced the selection of an Expiration date is disabled and not clickable.

![image](https://cloud.githubusercontent.com/assets/300805/4733462/ab85c93e-59c8-11e4-8298-5173eb59f65f.png)

**Comment by CodeAlDente** [comment]
> Feature is currently not supported. I will keep this open as a tracker.

Is this feature still on your to-do list? At the moment I do the workaround over Thunderbird, creating the key there and export/import it to get it working with Mailvelope - But this isn't really handy.

**Comment by zachgraeve** [comment]
Also curious if this is still being developed and if this enhancement is coming. Thank you.

**Comment by toberndo** [comment]
@zachgraeve Had this feature scheduled for March, but this is now postponed, probably April.

**Comment by McLovin-810** [comment]
IMHO, the key expiration should default to 1 year.

**Comment by CodeAlDente** [comment]
Any news?

**Comment by toberndo** [comment]
Allow setting expiration time on key generation now available with v1.6.0
