### ISSUE TITLE
Absence of encrypt button on email

### ISSUE THREAD

**Issue by cyberalpine** [mailvelope/mailvelope#242]
I installed Mailvelope and generated my key but when I compose a new email in Gmail, I don't see any padlock anywhere, as described in Mailvelope Help.
I use Chrome Version 41.0.2218.0 canary (64-bit) and Chrome Version 40.0.2214.5 dev-m but the result is the same on both versions.

**Comment by tomasabril** [comment]
I am using gmail and firefox and this has happened to me. If I click the Mailvelope button and the Reload it fixes it for me.

**Comment by toberndo** [comment]
Should be fixed by now. Please re-open if problem persists.
