### ISSUE TITLE
On Firefox Importing key from email fails while mailvelope option tab is open

### ISSUE THREAD

**Issue by hendrixski** [mailvelope/mailvelope#246]
I was getting my father set up with Mailvelope, emailed him my public key, but he clicked on the blue box with the key to import my public key nothing happened. When he closed the mailvelope options tab and tried again it opened the tab to the import-keys page and showed the import was successful.

I then tried to reproduce this and had the same issue. He sent me the key he had generated and I had the option window open to the "display keys". Clicking on his public key in my email gave me a spinner but nothing happened in the already-open tab. But when I closed the tab, refreshed my email, and tried again then it imported with no problem.

We had this issue on Firefox. I just tried to reproduce it in Chrome, and the import worked just fine.

**Comment by toberndo** [comment]
This is fixed in Firefox
