### ISSUE TITLE
Feature request: populate the email addresses into the "to" field

### ISSUE THREAD

**Issue by hendrixski** [mailvelope/mailvelope#247]
Something that bothers me, and that is instantly noticed by other people whom I introduce to mailvelope, is that they have to enter email addresses twice. It would be a pretty killer feature if you could take the email addresses that the email is encrypted for, and paste them into the "to" field in the webmail.

For example: I open webmail, click compose, click the little author button, write my mail, select the recipient, click OK --> transfer and not only is the encrypted text in the webmail but also the recipients email is in the "to" field, so all I have to do is click "send" and I'm done.

An added bonus would be to read the "to" field in case I entered the address in there before opening the popup for composing an email. Then when I click the lock then both my name and the recipient are already pre-selected, so all I do is click "Ok".

**Comment by toberndo** [comment]
Yup, recipient transfer happens now automatically. At least for Gmail, Yahoo, Outlook.com (provider specific integration is required).
