### ISSUE TITLE
Error: Unknow ASCII armor type

### ISSUE THREAD

**Issue by bungabunga** [mailvelope/mailvelope#248]
since the last two instances of mailvelope i can no longer open encrypted mail sent by OpenKey Chain android app. i always get the message "Error! Could not read this encrypted message: Error: Unknow ASCII armor type".

**Comment by alecpl** [comment]
I've got this also for some GnuPG v1 encrypted messages in inline format.

**Comment by toberndo** [comment]
This has improved in multiple steps and latest with the v1.6.0 release. Extracting the armored block from HTML is still a challenge. Report any new issues with latest Mailvelope release.
