### ISSUE TITLE
Support for mail.ru webmail

### ISSUE THREAD

**Issue by sambul13** [mailvelope/mailvelope#249]
As known, mail.ru is the largest and very popular webmail service in Eastern Europe. Is it possible for the mailvelope author to add it to the list of webmail services supported by mailvelope? I just installed it as an extension from Google Store to the latest Chrome running in Win 8.1 64-bit, and was trying to add it to the latest mailvelope watch list , but no new features or buttons appeared in mail.ru webmail UI. 

Am I doing something wrong? Mailvelope docs are vague on exact procedure on "how to add a new webmail server, how to verify it works, and how its GUI should change after that to show mailvelope integration".

**Comment by Manouchehri** [comment]
Add `*.mail.ru` to the list of mail providers. It was reported as working by @pianist in #275.

**Comment by toberndo** [comment]
mail.ru is now part of the list of supported mail providers in Mailvelope v1.3.3.
