### ISSUE TITLE
How to migrate Mailvelope - Switch to new Macbook

### ISSUE THREAD

**Issue by juhucoding** [mailvelope/mailvelope#253]
After having switched to a new Macbook, I can't find a possibility to migrate my keys to the new machine. 

I searched for the config files and had a look in my TimeMachine Backup under

    ~/Library/Application Support/Chromium/Default

but found only cryptic directory names like

    kajibbejlbohfaggdiogboambcijhkkf

Searching for "*.asc" or "*ailvelope*" did not show up any results. 

Any suggestions, how to extract or migrate my keys?

Thank you very much!

**Comment by toberndo** [comment]
Do you have still access to the old MacBook? Then you could go to the Mailvelope options and in the keyring click on "Export" -> "Display all keys".

You can then re-import all the keys on the new device with a bulk key import.

**Comment by juhucoding** [comment]
Unfortunately not. 

Any further ideas?

Thx for the response!

**Comment by toberndo** [comment]
If you have restored the complete ~/Library/Application Support/Google/Chrome folder, shouldn't you see all of your bookmarks, chrome extensions etc. as before?

**Comment by juhucoding** [comment]
Nice suggestions, I might try that one and report back tomorrow.


Thomas Oberndörfer <notifications@github.com> schrieb am Sun Jan 04 2015 at
19:38:33:

**Comment by juhucoding** [comment]
Although it throw an error message after replacing the Chromium-Settings
(which were almost as big as 3 GB) on Chromium launch, I was able to
reinstall Mailvelope and in consequence export the keys.

Btw, I stayed in the Chromium world: ~/Library/Application Support/Chromium

Thx again for the idea.

Martin Bothe <martin.bothe@googlemail.com> schrieb am Sun Jan 04 2015 at
20:38:33:
