### ISSUE TITLE
Cannot import secret key

### ISSUE THREAD

**Issue by oeekker** [mailvelope/mailvelope#256]
When trying to import my secret key (I've exported it with gpg --export-secret-key --armor, both with and without --openpgp switch), I get the following error:

Import Error. Unable to import one key due to exception: TypeError: that.users[i].userId is null

I'm using Firefox 35.0 and have restarted it before trynig again. There are no error messages in the error console...

**Comment by toberndo** [comment]
Currently a limitation of OpenPGP.js. Tracked here: https://github.com/openpgpjs/openpgpjs/issues/282

**Comment by oeekker** [comment]
This looks like an easy change. Would it be possible for you to fork openpgpjs and create a pull request?

**Comment by oeekker** [comment]
Hmz... Seems like importing the same key with version 0.12.1 under Firefox 36 in Windows 8 on one computer works, while it fails in Windows 7 on the other computer...
Is there a way to add a userid to my private key by any chance?

**Comment by oeekker** [comment]
After removing my own public key and re-importing the private key it also worked on Windows 7...
Not sure why, but now I can finally use Mailvelope :-)

**Comment by toberndo** [comment]
openpgpjs/openpgpjs#282 is closed, closing this as well.
