### ISSUE TITLE
Support for palemoon

### ISSUE THREAD

**Issue by dcherian** [mailvelope/mailvelope#265]
Pale Moon, is an optimized fork of Firefox. Adding support for it shouldn't be too hard. Directions are available here: http://forum.palemoon.org/viewtopic.php?f=1&t=5440

**Comment by Dissectional** [comment]
Registering interest in this.

Have just tried installing Mailvelope 1.3.2 with Pale Moon 25.8.1 x86 - have disabled compatibility checking but unable to get Mailvelope to work.

**Comment by tristan-k** [comment]
+1

**Comment by Russtopia** [comment]
Also interested, I have little add-on experience but perhaps could take a crack at seeing why it's not compatible :p

**Comment by aphirst** [comment]
I'm also interested in this. I have an e-mail account with a service that provides encryption for all inbound emails using a public key you provide them, and although I primarily use a dedicated email client, they recommend the use of mailvelope for viewing such emails from their web interface.

**Comment by toberndo** [comment]
@aphirst minimum Firefox version is: 38.

**Comment by aphirst** [comment]
@toberndo Is there a known correspondence between the Mailvelope versions and Firefox, such that it might be possible to (without having to resort to brute force) find the most recent version which still works with Firefox ~24 ?

**Comment by toberndo** [comment]
If you unpack the xpi file, you will find minimum version requirement in the install.rdf. Maybe try <0.13.2. But not recommended, as we had security fixes in between.

**Comment by aphirst** [comment]
Hmm, that is an awful long way back. I'll see if I can modify the (current) extension to work using the simpler methods this evening.

**Comment by espress0** [comment]
+1

**Comment by toberndo** [comment]
We want downward compatibility of Mailvelope on Firefox only to the latest Firefox ESR release. That means soon we will switch to Firefox ESR 45. It does not look like Palemoon can meet this requirement.

**Comment by sergeevabc** [comment]
If someone found a way to use Mailvelope (or another in-browser PGP addon) with Pale Moon, then tell us about it, please
