### ISSUE TITLE
Restore settings and keys after signing out from Google Chrome

### ISSUE THREAD

**Issue by link7777** [mailvelope/mailvelope#266]
Hi 
A few days ago I had to sign out on Google Chrome. A few minutes ago I have signed in on the same Chrome browser.
After that all my keys disappeared.
I have all my tabs, extentions and extentions data synced with google user account but seems that it doesn't work with Mailvelope. 
Any change to get mailvelope settings and keys data back?

Thanks.

**Comment by toberndo** [comment]
With sign out you mean that you have removed the profile?
Described here: https://support.google.com/chrome/answer/2364824?hl=en

If yes, then you could check http://www.chromium.org/user-experience/user-data-directory to see if the profile folder still exits and somehow load it into a new profile.

Mailvelope does not sync settings and keys, therefore if you remove the profile (and in case the profile folder is deleted) then all your keys are gone.
