### ISSUE TITLE
Cant import public or private keys generated in GPG ..this used to work

### ISSUE THREAD

**Issue by dbgdngit** [mailvelope/mailvelope#268]
Chrome on win 7, Firefox on Win 7

Import Error. Unable to import one key due to exception: TypeError: Cannot read property 'length' of null

Sample public key below

-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG v1.4.11 (GNU/Linux)

mQENBFIUmVABCADEmq8QVRenAMb1Rdt8sKnjLJnkggSc037A7Q/MNw1uqRix1cFR
KQQAk9wEY9ISup9KoQYZqgJS8PSXXsnBwVpID0IGHjTRkPUY5DIvUH09Ezv3xPc8
Kqw9Lch2BtbZyXRg3MjiLwsOF0AfzLLkuXLpkDmTnrxGcMs22x0ye+l/hvYkNpYA
IzBKHvlgrDW/LIm/JnjctCe7RV3nJPQINQrGrnrn1oczzY2TG8TVaY244nEZqrNr
uH66XkrulijgGPQi69QGknyVgjkJyiLdrh/kcwiWtb8gLJV23vSWmCcPcRjAyWsm
deaWCI8RvpeejqGrc6BO17GOtV2bxFm7DyFBABEBAAG0KURhdmUgQm94YWxsIDxk
YXZlLmJveGFsbEB0aGVndWFyZGlhbi5jb20+iQEcBBABAgAQBQJSFJlVCRA9FaGE
ZjwT6gAAFDYH/1ops0TfS8SGz73Y3DpvymTAlThR6YLKNqpDK6zeOShHNfbt7oP/
NNiHECBu95qp5yUNpMHLyhO5QhMa5zgUg/iGBfTurNCvqoM8tkIc3cw4XJbykPaB
FJ2mBcn2MyRErInmSNbCC/gaWSR9nFpqbEQ0+Zy2PIR2LDseThbsGIhJxIfOIGIY
xdfpTCpuM/ZIaaiwMuk16YPzMisA+khsorqRiD5RCuRLK4Soz5+2wPsFE7vvR0/3
UT5xrdWhd0upzUk7vqyFW/yrE7IEG/Fx6ELExqzbfxZqY7mtapdOQeCFwVtoXK86
W5NV+q9l0V6gaM8S3jQQ9obIr4lpAcGuPvO5AQ0EVBrJWQEIAMOi9RW/NE09+JAe
qPwhXiED+QMBsjCrQshnY5W+hoP9xMFdTrbylK2Mzx0W4Mx06Ml2lRTz32/dU8so
+Q7iTGMyNBTTbMGyxgjCJTUT03gmxjYZ4sE7MfcFo5eVs4OOzxyLQaD/gWnbFuF2
R6JttvPIP5znIMPUPkTeDzM0UCPhX3YntHa90rh9R8Hrvj17qhb8FinOdLAlVdBe
M89krdCcirRlXuVipkDbywUJMKLGFoLnFmtFMTVAeI117t3hy7My/keHRqw9Dc7j
25qwYxWKSwWKKO9KPn5LewOZFa8o7B5w03kQdv6EwlQ3sB92drjLJVkr/PzAtBfc
/jLKIx8AEQEAAYkBHwQYAQIACQUCVBrJWQIbDAAKCRA9FaGEZjwT6uhjB/93I78O
bqu3UI245gNQjrml/JKYHYYIDkFF+Opf+iaQA+gxBmQnhaJrfivR4deq+/rJyu1S
eZwtW+rncilodxw7JyXVmj5o9oEOEtkWSFQPTqPfa4oHsRWsy3pNX7hux6sMzzh5
ZQXR2D9/5Id22ODex8Pm23ee8xWu/iO027IXnNha0/Cwl16KGBPTbOLEs/86FO4o
KTY8I/UXt00M6Hy0GQFAtcbhh0LGdjAK+tlPEKX11500sRh2jTjKcNkheGNKh41n
Y2Kp5HZJaIDnH0W0dkyYChhl8AeEeP30CctmabwS9iOITHV3iL2aA/5sCnO13FGD
4ZXk9eRnSNLUOhI1
=b/4R
-----END PGP PUBLIC KEY BLOCK-----

**Comment by toberndo** [comment]
Could successfully import in Mailvelope v0.11 in Chrome and Firefox on Linux.
Will try on Windows...

**Comment by dbgdngit** [comment]
works in 12.0.3b on win 7 chrome 40

**Comment by glamrock** [comment]
I have run into the same issue on Mac (today), but not sure why -- the key was exported from Mailvelope and works fine on command line.
