### ISSUE TITLE
search in Gmail for PGP message when opening mailvelope does not recognise unless you F5

### ISSUE THREAD

**Issue by dbgdngit** [mailvelope/mailvelope#269]
This happens in Firefox 35 and Chrome 40 on Win 7
and Chrome 40 on Mac OSX

Again this has only started happening in the past few days and is affecting numerous people

**Comment by toberndo** [comment]
This is a very old bug: https://github.com/mailvelope/mailvelope/issues/30

And there is no fix available.

A work-around in Gmail would be to create a label for PGP messages and use this label for search.

Closing this as duplicate.

**Comment by VPhantom** [comment]
This is closed, so I don't know if this comment will work, but could you please include this work-around suggestion in your documentation? I've been bitten by this bug too and these two bug reports required a lot of digging to find. :)
