### ISSUE TITLE
Support for SmarterMail & Zarafa

### ISSUE THREAD

**Issue by toberndo** [mailvelope/mailvelope#27]
Mail compose editor:
- editor does not recognize the injection of the encrypted message. After send the mail is stored unencrypted (last state before encryption) in the sent folder. Simple click in the text area seems to trigger an update and solves the problem. -> Mailvelope needs to trigger a user event on the editor after encryption.

Decryption scenario:
- client uses iframes without src attribute which are currently not scanned for messages (this could be added)
- as expected messages in inbox are not identified, but not so for sent folder (page structure the same). Did Chrome start to inject content script into dynamic iframes?

**Comment by fbartels** [comment]
Hi Thomas,

I just retried your extension with the latest Zarafa WebApp (2.0.1). Mails can be signed and encrypted and also the behaviour of text being replaced seems gone (its fine to add recipients and subject afterwards).

What does not seem to work is decypting recieved messages as I do not get an overlay window then. Tested on Ubuntu 14.04 with Chrome 41 and Mailvelope 0.12.0.

**Comment by davodego** [comment]
The same to me,
encrypting mail on compose editor with Zarafa WebApp works well.
Decrypting a mail in my WebApp inbox fails. Mailvelope does not notice the encrypted mail. The decrypt button was not shown. Not in mail preview or when I open the mail in a singel tab.
On another webmail client, e.g. Owncloud Mail App or Zarafe WebAccess UI, it woks.

Firefox Plugin 
Mailvelope 0.10.4
Zarafa 7.1.13-51032
Zarafa WebApp: 2.0.2.48619

**Comment by davodego** [comment]
With Mailvelope v1.3.3 Zarafa Webapp is still not stable.
Encrypting and decrypting works, but not from start on. Most times i have to add my site again to Mailvelope to show up encrypting or decrypting button.

**Comment by JPCrypto** [comment]
I see the issue with Smartermail still hasn't been resolved. I would be happy to create a testing account on my server to help get the Smartermail issue resolved.

**Comment by fbartels** [comment]
Encrypting and decrypting messages work now with the 4.3.2 release of mailvelope. I think this issue can be closed.

**Comment by JPCrypto** [comment]
Agreed. It's worked for some time now.

John Perry

Jun 8, 2020 09:32:09 Felix Bartels <notifications@github.com>:

**Comment by toberndo** [comment]
Thanks for reporting back. Closing.
