### ISSUE TITLE
gpg: WARNING: multiple plaintexts seen gpg: handle plaintext failed: Unexpected error gpg: uncompressing failed: Unknown compression algorithm gpg: decryption failed: Bad signature

### ISSUE THREAD

**Issue by fpietrosanti** [mailvelope/mailvelope#270]
I received an email that's digitally signed and encrypted from someone with Mailvelope 0.11 and i was not able to decrypt it from enigmail with gnupg 2.0.33 on Mac Os X with the following error:
gpg: WARNING: multiple plaintexts seen
gpg: handle plaintext failed: Unexpected error
gpg: uncompressing failed: Unknown compression algorithm
gpg: decryption failed: Bad signature

By saving the message to disk, removing manually the signature, i was able to decrypt it.

**Comment by toberndo** [comment]
A cleartext signed message that is afterwards encrypted is according to my understanding not a valid signed & encrypted message. Mailvelope supports now sign & encrypt. Please reopen if reproducible with latest Mailvelope.
