### ISSUE TITLE
Remove header (comment, version) from encrypted message

### ISSUE THREAD

**Issue by toberndo** [mailvelope/mailvelope#28]
There should be an option to create messages without header lines.

**Comment by Fastidious** [comment]
I second this.

**Comment by jelledionot** [comment]
I agree with that too.

**Comment by rugk** [comment]
Like I suggested in https://github.com/mailvelope/mailvelope/issues/361 this should be optional IMO. Even if it is opt-out I would like this option.

**Comment by Tectract** [comment]
bump. Security bug in mailvelope

**Comment by rugk** [comment]
Not really a serious security bug, but it may be bad in certain conditions and it is unnecessary metadata.

**Comment by toberndo** [comment]
- Add option to UI in Options -> Security
- Read option from preferences and set accordingly in https://github.com/mailvelope/mailvelope/blob/master/src/modules/pgpModel.js#L48

**Comment by toberndo** [comment]
This is now available in https://github.com/mailvelope/mailvelope/releases/tag/v3.1.0
