### ISSUE TITLE
Incorrect instructions on Security tab

### ISSUE THREAD

**Issue by marnen** [mailvelope/mailvelope#287]
I'm reporting a UI bug. Steps to reproduce (I'm using Chrome 40 on Mac OS X 10.10):
1. Open the Mailvelope Options window.
2. Click Options in the top bar.
3. Click Security on the left.
4. Change any option.
5. Click Save.

Actual result: 
The following text is displayed: "Please reload your mail provider tab (F5) to make these settings take effect."

Expected result:
Since I'm running Mailvelope on Chrome on Mac OS X, I should not see any mention of the F5 key, which doesn't reload pages in this browser (all Mac browsers that I know of use Cmd-R for this). Perhaps it would be better not to list a keystroke at all, but rather assume that the user knows how to reload pages.

**Comment by marnen** [comment]
I should mention that this is Mailvelope 0.12.0.

**Comment by comradekingu** [comment]
@marnen Is this still the case?

**Comment by marnen** [comment]
@comradekingu Not in 1.7.2 (see screenshot). The current wording is rather awkward, but at least it's not inaccurate. :) Closing.

![image](https://cloud.githubusercontent.com/assets/34378/26066369/998b22e6-3964-11e7-98a2-2c0182a1d501.png)
