### ISSUE TITLE
Icewarp webmail 11 - Improperly formatted armor header

### ISSUE THREAD

**Issue by davart14** [mailvelope/mailvelope#298]
Hello, I was using icewarp webmail 10 and mailvelope worked perfectly.

They upgraded to icewarp webmail v11, mailvelope seems to encrypt emails correctly, but I cannot decrypt them. I get the following message when trying to decrypt:

Error! Could not read this encrypted message: Error: Improperly formatted armor header: Comment:

![error](https://cloud.githubusercontent.com/assets/9370210/6734584/f37ad4c8-ce26-11e4-99ac-042dd2ff596d.jpg)

I'm using firefox 36.0.1 and mailvelope 0.12.1.

Any suggestions that might help?

You can access icewarp webmail v11, thru this url: http://demo.icewarp.com/webmail/ 

Regards,
Davart

**Comment by toberndo** [comment]
Some improvements in the area of armored block extraction have landed in Mailvelope. Please reopen if you can still reproduce this bug with latest Mailvelope.
