### ISSUE TITLE
simple-storage instability - data loss when addon updates and also at other times (Bug 1091244)

### ISSUE THREAD

**Issue by federicotg** [mailvelope/mailvelope#304]
Hi.
I have been noticing that every once in a while all my imported public keys and my private key disappear from mailvelope. The whole extension looks as newly installed.

I use Firefox on Ubuntu with Sync set up not to synchronize add-ons.

I only use sync on one desktop machine, but I have FF sync'ed with my Android phone.

I think the keys disappear when a new Firefox update is installed from the Ubuntu update servers.

This has happened several times since I installed mailvelope for the first time on my machine and also on another person's machine (also Firefox and Ubuntu user).

On a another user's netbook that does not install updates automatically the keys have never disappeared.

**Comment by federicotg** [comment]
Apparently it is a real bug:

https://bugzilla.mozilla.org/show_bug.cgi?id=1091244

**Comment by toberndo** [comment]
@federicotg thanks for linking to bugzilla. Pretty ugly story. Seems like we should use IndexDB.

**Comment by federicotg** [comment]
@toberndo Yes, data loss seems very frequent in Ubuntu. Probably with browser updates while Firefox is running or logging out without closing the browser. You can't count on storing your keys just inside the browser.

**Comment by v6** [comment]
// , This seems to cause #321. 

I wonder whether there is a way to get around using the Firefox data stores.

**Comment by My1** [comment]
is there a possibility of using a config file or similar?

**Comment by toberndo** [comment]
@My1 It's a Firefox bug that affects all add-ons that use simple storage: https://bugzilla.mozilla.org/show_bug.cgi?id=1091244

We are working on migrating to IndexedDB.

**Comment by v6** [comment]
// , If you like, hit us up when we have a scratch branch or a git repository for the IndexedDB migration.

**Comment by chaoscommander** [comment]
Is there a way to recover said data? I used Mailvelope with a mail provider (web.de) that now refuses to let me reset or access my encryption settings in any way, tells me to open the settings page from the machine I used to set up encryption. Sadly, this IS the machine.

**Comment by ajvb** [comment]
@toberndo Anything I can do to help out? I've been experiencing this recently and it sucks. Let me know if there is anything I can do to help.

**Comment by v6** [comment]
// , Well, you can raise hell with the Firefox developers about this, I guess.

**Comment by dotnetCarpenter** [comment]
mailvelope is serious **unreliable**. I just lost my access codes to our servers because of this. Please write that "keys might get lost in Firefox" in big letters, so people know to backup their keys somewhere safe. 

OS: Windows 10
Mailvelope: 1.4.0

**Comment by rugk** [comment]
I also experienced this issue (although I am not sure what causes it, but you already had some answers to it). And I agree with the others, it is serious and may really make users leaving Mailvelope as they think it is Mailvelope's fault. (users don't care about this)
Losing your private key is the worst thing which can happen, so I had expected this bug to be fixed until now. It discourages users and may even discourage them of PGP in general.

@ajvb  What you can do, well..., as @toberndo said, make a PR with a different way of saving the data.

> Please write that "keys might get lost in Firefox" in big letters, so people know to backup their keys somewhere safe.

Well... at least put it in the FAQ or make it.
Generally - as you see of this bug - you might make it much more serious that backups are important.

BTW: A better (manual) backup-mode, which also includes Mailvelope's settings (which is quite useful as you might not want to try to set the exact same background color/settings you had before) is to set backup the file `jetpack/jid1-AQqSMBYb0a8ADg@jetpack/simple-storage/store.json` in your profile dir.

**Comment by rugk** [comment]
This happened again with v1.7.2 on two different profiles. As this is the first release with an embedded web extension, maybe it was the last one with this error? Or how is the current plan?

**Comment by toberndo** [comment]
v1.7.2 has embedded web extension but does not yet convert to the web extension storage. This will be done with the v1.8 release which will be released in around two weeks. You can test this release already with the latest builds from https://build.mailvelope.com/nightly/.

**Comment by rugk** [comment]
With v1.7.2 this horrible error happens again and again when restarting Firefox or when it crashes or something similar. (I have not yet found out, which behaviour exactly triggers it.)

Please fix it ASAP. It is the worst case for such an add-on when your private key(s) are lost literally 10 times in a week and you always restore it in a more or less cumbersome way just to see it lost again the next day.

**Comment by toberndo** [comment]
@rugk we know that already. Did you have the chance to test the builds from https://build.mailvelope.com/nightly/?

**Comment by rugk** [comment]
No we don't know that. We knew that it **sometimes** fails when **updating/upgrading** the extension, but it has never been so frequent.

No, it's unverified. Just publish the version when it is ready.

**Comment by toberndo** [comment]
Mailvelope v1.8.0 has been released which should fix the storage instability. On Firefox all data in the local storage is now migrated to the WebExtension API storage.
It could still be that you lose your data with the 1.7.2 -> 1.8.0 update, but afterwards it should be stable. Please report any data loss that happens after the update.

**Comment by rugk** [comment]
Update worked fine here without data loss.

**Comment by v6** [comment]
// , I'm curious, how does the fix work?

**Comment by rugk** [comment]
Completly rewritten system. Now is a WebExtension.
