### ISSUE TITLE
Widget is loaded multiple times in the message textarea

### ISSUE THREAD

**Issue by jancborchardt** [mailvelope/mailvelope#307]
I left my ownCloud Mail tab open for some minutes in the background. This is what I came back to:
![capture du 2015-04-15 11 29 48](https://cloud.githubusercontent.com/assets/925062/7155917/e3312dc8-e362-11e4-9dd9-1477eb6f0f99.png)

What looks like a bunch of widgets overlaying each other. Not sure why there were inserted more and more after the first one.

**Comment by toberndo** [comment]
This has been fixed in one of the previous releases.

**Comment by jancborchardt** [comment]
Awesome @toberndo! :)
