### ISSUE TITLE
0.13.1 Private key not found when decrypting

### ISSUE THREAD

**Issue by dbgdngit** [mailvelope/mailvelope#309]
Deployed 0.13.1 to get round absent recipient list
Reimported keys from 0.13.0
Restarted Chrome browser on win 7 (also did this on mac os_8 and 9)

Sent an encrypted email - when recipient tries to open (also using 0.13.1)
Gets Private Key not found. ID of the key referred to is not a Key ID any of us can find

Can Decrypt emails sent prior to 0.13.0 Release

**Comment by toberndo** [comment]
Tried several combinations and was not able to reproduce.
Have you set a primary key and the "Always add primary key ..." option?

**Comment by dbgdngit** [comment]
There is no longer a dropdown menu to select a primary private key - although the tick box exists to always add

**Comment by dbgdngit** [comment]
I have 2 private keys in my store - one for me, one for a shared mailbox however I know that not all most users who have experienced this only have 1.

**Comment by dbgdngit** [comment]
The primary private key is no longer automatically added even if that option is enabled. The recipient doesnt appear in the bottom box of added encryptees

**Comment by dbgdngit** [comment]
ok I've got the primary key and auto add setting to be honoured. Re-install and re-import keys.
Still getting private key not found error

**Comment by dbgdngit** [comment]
To add - I can decrypt anything sent by any other pgp client

**Comment by dbgdngit** [comment]
I'm pretty sure that this issue is related to the Primary Private Key setting not being set whilst the always add Primary Key setting is enabled.
Hence when decrypting private key wasn't found and key id was random.
