### ISSUE TITLE
Performance in Firefox and Internet Explorer is no good

### ISSUE THREAD

**Issue by barrydegraaff** [mailvelope/mailvelope#315]
I apologize in advance for the lack of technical argumentation in this issue.

When decrypting messages especially ones that are not created by OpenPGP.js (eg GnuPGP with Thunderbird/Enigmail) I must say Firefox and Internet Explorer are slow.

Also in general, every PGP operation is slow in Firefox and Internet Explorer while all is rocket fast in Google Chrome.

I am not sure how we can improve this, but I am opening this report for reference.

At times the PGP stuff is just to slow to be useful in Firefox and Internet Explorer

https://github.com/openpgpjs/openpgpjs/issues/318

**Comment by barrydegraaff** [comment]
Right now I am waiting for over 10 minutes to generate a 4096 RSA key in firefox...

**Comment by toberndo** [comment]
Mailvelope uses now OpenPGP.js v2 with performance improvements. The key generation on Firefox uses the Web Crypto API so this issue should be solved as well.
