### ISSUE TITLE
Error: «Ascii armor integrity check on message failed»

### ISSUE THREAD

**Issue by stopdesign** [mailvelope/mailvelope#316]
Each time I decrypt messages from Airmail with GPG I get an error:
`Error! Could not read this encrypted message: Error: Ascii armor integrity check on message failed`

I know that there is no checksum in Airmail encoded messages. Is it possible to make an options to disable this check?

**Comment by toberndo** [comment]
This would be option `--ignore-crc-error` as in https://www.gnupg.org/documentation/manuals/gnupg/GPG-Esoteric-Options.html

Currently not available in OpenPGP.js and I'm seeing this as an edge-case.

**Comment by toberndo** [comment]
This is fixed now: if now checksum is available, then no "wrong checksum" error is triggered.
