### ISSUE TITLE
Clicking on links inside encrypted emails opens them inside the encrypted iframe

### ISSUE THREAD

**Issue by akkartik** [mailvelope/mailvelope#320]
I'd like to suggest it open in a new tab just like clicking on links in regular gmail.

(Please let me know if this isn't reproducible.)

![mailvelope](https://cloud.githubusercontent.com/assets/3161/8013529/cddddacc-0b7e-11e5-8ac8-c6e51e8da693.png)

**Comment by toberndo** [comment]
This has already been fixed in the 3.0.2 release. Thanks
