### ISSUE TITLE
Security Background Enhancement

### ISSUE THREAD

**Issue by PRabahy** [mailvelope/mailvelope#322]
It appears that the security background is just a static image right now. It would be really cool (and I believe more secure) if the background image was generated deterministically from a hash of the primary private key.

An attacker wouldn't know the private key and therefore couldn't spoof the background image. The user wouldn't have to take any additional steps to setup this security layer because almost all users will be importing at least 1 private key anyway.

**Comment by toberndo** [comment]
Actually, it's not static and uses random data at installation for the angle (between 300-60 degree) and the size of the locker. In the settings you can always modify these values and in the next release we also offer different background colors.
