### ISSUE TITLE
Predetermined key pair

### ISSUE THREAD

**Issue by superplane** [mailvelope/mailvelope#323]
We are doing research currently about the encryption usability (one HCI area), and we found this tool very interesting to be used in the research. 

We planed to implement the auto exchange of public keys by automatically uploading and retrieving public keys from a key server. However it seems not supporting right now. Instead, we want to generate a predetermined key pair every time, so that in lab experiments, participants and us don't need to exchange public keys and we can know their keys. 

We looked into the code, but could not identify all functions that can generate a fixed key pair every time. Is their any ideas how to change the source code?

PS: we are doing research, and the changed code will never be disclosed. 

Thanks!

**Comment by toberndo** [comment]
Predetermined keys would first need to be implemented in OpenPGP.js: https://github.com/openpgpjs/openpgpjs/blob/master/src/key.js#L950
