### ISSUE TITLE
Retrieving Mailvelope private key from Chrome folder on a backup disk?

### ISSUE THREAD

**Issue by philgooch** [mailvelope/mailvelope#327]
I have a new laptop, but the private key I need to read an encrypted email is buried somewhere on the backup disk from the old machine in the Google Chrome Application Support directory (OS X). The old machine is dead - I only have the backup disk.

Is there any way to retrieve this key from the backup disk so that I can read the email on the new machine?

**Comment by Manouchehri** [comment]
Copy your Chrome data to a new machine or run with the user data pointed to the backup.

https://www.chromium.org/user-experience/user-data-directory

```
do shell script "/Applications/Google\\ Chrome.app/Contents/MacOS/Google\\ Chrome --user-data-dir=/Users/$USER/Library/Application\\ Support/Google/ChromePersonal > /dev/null 2>&1 &"
```

**Comment by beta2k** [comment]
Sorry to reopen this, but I have the exact same issue, but I am on Windows 7. When I try to start Chrome as follows ...

    "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --user-data-dir=[Path_To_Backup_Folder]

... the extensions of Chrome are not restored. The bookmarks are restored however. 

How can I restore the mailvelope backup?

**Comment by cartel0x27** [comment]
This advice is incomplete at best.

The application database is located in User Data\Default\Local Extension Settings\kajibbejlbohfaggdiogboambcijhkke 

So for windows that would be %LOCALAPPDATA%\Google\Chrome\User Data\Default\Local Extension Settings\kajibbejlbohfaggdiogboambcijhkke

Steps to recover:

1. create a new chrome profile
2. add the Mailvelope extension
3. close chrome
4. copy the contents of the User Data\Default\Local Extension Settings\kajibbejlbohfaggdiogboambcijhkke folder from the backup to the same location under the new profile
5. open chrome
