### ISSUE TITLE
Compatibility with smartcards like yubikey

### ISSUE THREAD

**Issue by serginator** [mailvelope/mailvelope#328]
I think this should support smartcards, currently cards owners can send encrypted mails but when they have to decrypt, they have to copy the message to a file and do it the old way, `gpg -d file`.

Thanks!

**Comment by Bene81** [comment]
Same as https://github.com/mailvelope/mailvelope/issues/238
But nonetheless a major feature, I'd like to see in any security software.

**Comment by serginator** [comment]
You are right @Bene81, I'm going to just +1 the other issue. It's fun that it is #238 and this is #328, that should be enough reason to develop this feature :P
