### ISSUE TITLE
Firefox addon verification 

### ISSUE THREAD

**Issue by Hedaja** [mailvelope/mailvelope#329]
Since Firefox 41 addons need to be verified to be executable. At the moment Mailvelope isn't verified and gets rejected and deactivated by Firefox. Has the verification process already started?

Cheers,
Christian

**Comment by toberndo** [comment]
Verficiation for 1.0.0 started but failed. We are soon going into another review process with a patched 1.0.1 version soon. For FF 41 there will definitely be a signed version.

**Comment by toberndo** [comment]
A signed v1.0.1 is out.

**Comment by kmindi** [comment]
There is no release available here nor a tag (maybe forget to push the tag?) nor an updated xpi.

**Comment by toberndo** [comment]
@kmindi https://github.com/mailvelope/mailvelope/releases/tag/v1.0.1 is now available
