### ISSUE TITLE
Key incompatibilities Mailvelope <-> APG

### ISSUE THREAD

**Issue by toberndo** [mailvelope/mailvelope#33]
- generate a new key pair in Mailvelope and import into APG (android), the APG does not encryp or sign with this keys. Same for GnPg Mac.
- only public keys generated in APG works in Mailvelope. Private keys, when importing into Mailvelope, dont work

**Comment by hakarune** [comment]
I'm getting problems importing multiple keys into mailvelope that were created in OpenKeychain, sample key posted here (https://github.com/google/end-to-end/issues/337).

**Comment by ctaverne** [comment]
Similar problem with OpenKeyChain.
I can't sign mails with imported keys. No pb with encryption.

**Comment by toberndo** [comment]
Key flags available since v0.8 and therefore we have compatibility with OpenKeychain. There is no upgrade path planned for keys generated prior to v0.8.
