### ISSUE TITLE
Please submit Mailvelope for inclusion in https://gnupg.org/related_software/frontends.html

### ISSUE THREAD

**Issue by MagicFab** [mailvelope/mailvelope#331]
I didn't know or remember about Mailvelope until someone suggested I use it. I first looked at https://gnupg.org/related_software/frontends.html and it's not there, please consider submitting it for inclusion there.

**Comment by Manouchehri** [comment]
Probably asking on the mailing list would be the most appropriate.

https://lists.gnupg.org/mailman/listinfo/gnupg-users

**Comment by rugk** [comment]
Mailvelope does not use GnuPG so I wonder whether it would be valid to have it in this list.

**Comment by toberndo** [comment]
My understanding is also that this is a list of GPG frontends, which Mailvelope isn't.
