### ISSUE TITLE
Can't Open "Plugin Options"

### ISSUE THREAD

**Issue by sh3bang** [mailvelope/mailvelope#332]
If Firefox cache is disabled and the root ca of the https page is availaible/imported in firefox key store, then the mailvelope plugin "option" page will not open! Workaround is to leave the Firefox window and switch back, then it will be open :-)
Using windows 7, firefox 40.0.3 and mailvelope plugin 1.0.2

**Comment by toberndo** [comment]
Probably this issue is not Mailvelope specific? Closing for now.
