### ISSUE TITLE
FAQ should reference bug #61

### ISSUE THREAD

**Issue by bwpearre** [mailvelope/mailvelope#340]
It took me a while to figure out that I cannot encrypt attachments in Mailvelope. Given the number of watchers on bug #61 and the number of duplicates, doesn't this qualify as a FAQ?

(p.s. Nice work!!!)

**Comment by rugk** [comment]
:+1:

**Comment by toberndo** [comment]
File encryption is now available: https://www.mailvelope.com/en/help#files
