### ISSUE TITLE
GPG private keys on a smart card such as YubiKey NEO

### ISSUE THREAD

**Issue by egarcia74** [mailvelope/mailvelope#343]
Hi there,

Forgive my ignorance on the subject, but is it possible at all to support decryption keys stored on a PIN protected smart card such as the YubiKey NEO?

I love Mailvelope but I had to stop using it after I switched to using YubiKey.

**Comment by reuterbal** [comment]
There is an open feature request for that: #238

**Comment by toberndo** [comment]
This is now available with the GnuPG integration. See also: https://github.com/mailvelope/mailvelope/issues/238#issuecomment-447895904
