### ISSUE TITLE
Bug with expiration date

### ISSUE THREAD

**Issue by russkiy78** [mailvelope/mailvelope#346]
If main key have  expiration date more than 2038-01-19 key becomes "invalid".

**Comment by rugk** [comment]
By default keys created my Mailvelope do not expire at all. Additional - at least in Firefox - I cannot change the expiration date at all in the Mailvelope UI when creating a key.

**Comment by russkiy78** [comment]
I mean, then I import  other user open key with  expiration date more than 2038-01-19 (64 bit timestamp) Mailvelope mark this key as "invalid" because it can worked with 32 bit  timestamps only.

**Comment by rugk** [comment]
Ah okay, this is indeed and issue and should be fixed.

**Comment by canaaerus** [comment]
I came across this issue too. My pgp key expires on 2087-01-07, but Mailvelope reads it as 1950-12-02 and marks the key as _invalid_. Please fix this.

**Comment by toberndo** [comment]
Depends on https://github.com/openpgpjs/openpgpjs/issues/497

**Comment by toberndo** [comment]
Fixed with Mailvelope v2.0.0
