### ISSUE TITLE
Encrypt and decrypt any text block 

### ISSUE THREAD

**Issue by couriernew** [mailvelope/mailvelope#351]
This request is partially brought up in:
[Issue #318 Encrypt any arbitrary TEXTAREA?](https://github.com/mailvelope/mailvelope/issues/318)

The basic idea is to allow the user to encrypt and decrypt any text block using the keys that are stored inside Mailvelope.  The UI could be through the Mailvelope Options Tabs.
## Option Menu Change

The additional menu item could be: 
Key Management   |  Options  |   **Quick Encrypt / Decrypt**
## Quick Encrypt

![mailvelope_idea_encrypt](https://cloud.githubusercontent.com/assets/1687285/11689669/f23c99de-9ecd-11e5-8bde-a6c12979dbe2.jpg)
Next step would follow the same UI as composing inside an email (key selection, etc.).  
Basic idea is to offer user a compose message option outside of being logged into an email service.  
User could be offline or just not logged into a email site to use the encryption functionality.
## Quick Decrypt

![mailvelope_idea_decrypt](https://cloud.githubusercontent.com/assets/1687285/11689673/f9dab96e-9ecd-11e5-97a1-0b883c4e6886.jpg)
Next step would follow the same UI as decrypting message, with "Enter key password" next.
Basic idea is to offer an input box for encrypted text.
User could decrypt text blocks without having to have received the encrypted text inside an actual email.
## Use Case
- **Encryption:** User does not want to send the encrypted message as an email.  However, would still like to use Mailvelope as an easy graphical interface for managing keys.
- **Decryption:** User's friend sends an encrypted file as a text attachment.  Mailvelope workaround (seems to me) user should open the encrypted text attachment, copy-paste into an email, and send the email to the user's self.  User could simply copy-paste the encrypted message, without having to actually send an email.  Again, main goal is to continue using Mailvelop's easy GUI and key management.

**Comment by rugk** [comment]
:+1:

**Comment by toberndo** [comment]
@couriernew Thanks for the detailed design proposal. Looks great! I'm currently working on a similar enhancement in the Mailvelope settings that would allow to encrypt/dectypt files. Once this is in place we can easily extend it with two more views for encrypt/decrypt in textareas.

**Comment by riton** [comment]
:+1:

**Comment by couriernew** [comment]
Would be super excited to see this!  Thanks @toberndo

**Comment by jonathanjuursema** [comment]
I'm also looking for this. :)

**Comment by steglicd** [comment]
+1

**Comment by pinheadmz** [comment]
Also have this use case. Or even if mailvelope could detect any <textarea> element and add the editor-popup button.

**Comment by viktorgoc** [comment]
I have a similar use case where we would like to be able to encrypt pages in an internal wiki, meaning that these pages would not be stored on the server in clear text.

**Comment by toberndo** [comment]
Text decryption/encryption is now available in the main app window:

![Bildschirmfoto 2019-03-11 um 15 28 12](https://user-images.githubusercontent.com/1164474/54131386-8734df00-4412-11e9-97d6-27c10b239485.png)

**Comment by pinheadmz** [comment]
This is great thank you! Unfortunately, updating the extension wiped out the data directory and I lost all my keys. At this point it's easier for me to install GPG tools than restore my old mailvelope keys from backup.

**Comment by rugk** [comment]
@pinheadmz Remember the new version of Mailvelope can even be used with gpg directly… :smile:
