### ISSUE TITLE
Improve iframe sandboxing

### ISSUE THREAD

**Issue by rugk** [mailvelope/mailvelope#352]
Currently you sandbox encrypted messages in an iFrame with `sandbox="allow-same-origin allow-popups"`.

`allow-popups` is not that bad, but I still wonder why it is there. Because after the password for encryption is entered (where no iframe is used AFAIK) you should not require to open any popups anymore.

What I do not like is `allow-same-origin`. It basically allows the inner things to do manipulate all the content of the parent frame. But as you disallow script execution this is obviously still secure.
I'm just curious why you added these exceptions.

**Comment by toberndo** [comment]
allow-same-origin: content of iframe is set from outside
allow-popups: not sure what was required here

No improvements required in this area.
