### ISSUE TITLE
Add option for link detection (and auto-linking) and correct quotation marks

### ISSUE THREAD

**Issue by rugk** [mailvelope/mailvelope#362]
IMO there should be an option, which makes Mailvelope to look for links in the decrypted mail text and auto-links them so the user can easily click on it instead of manually copy and pasting them.

**Comment by rugk** [comment]
You should also support the display of quoted replies/text as `>`. This is a very common thing of many mail programs and you should also format it correctly by displaying a coloured bar.

**Comment by toberndo** [comment]
> IMO there should be an option, which makes Mailvelope to look for links in the decrypted mail text and auto-links them so the user can easily click on it instead of manually copy and pasting them.

This is now supported in https://github.com/mailvelope/mailvelope/releases/tag/v3.1.0
