### ISSUE TITLE
"Error! Could not read this encrypted message"

### ISSUE THREAD

**Issue by PetrusBelmonte** [mailvelope/mailvelope#369]
I do everything right. He can send me encrypted messages, and I can decrypt them. But I can not decrypt my own messages, and neither did he can decrypt mine.

I got this error

"Error: Ascii armor integrity check on message failed: 'xVEL' should be 'ZRMM' "

**Comment by toberndo** [comment]
We modified the extraction of the message from the mail client which could fix this issue. Please re-open if problem still exists with latest version of Mailvelope.
