### ISSUE TITLE
Electrolysis (e10s) compatibility

### ISSUE THREAD

**Issue by rugk** [mailvelope/mailvelope#371]
Please [test](https://www.arewee10syet.com/) whether this addon is compatible with [Electrolysis](https://wiki.mozilla.org/Electrolysis).

**Comment by toberndo** [comment]
No issues so far found in e10s mode.

**Comment by rugk** [comment]
Would you mind adding your addon to this list: https://www.arewee10syet.com/?

**Comment by toberndo** [comment]
Mailvelope is currently not in the list, but I sent them a mail. Thanks.
