### ISSUE TITLE
Revoked Signatures are still displayed

### ISSUE THREAD

**Issue by tomrittervg** [mailvelope/mailvelope#373]
I'm unsure if this is impacted by #372 or if it applied in a general case.  But if I revoke a key certification, Mailvelope still displays the signature.  Import the keyblock in #372 and look at the signatures of Test Key Two.

**Comment by toberndo** [comment]
Fixed with https://github.com/mailvelope/mailvelope/commit/487d0e479e04e75af7a79bd96f4319abe2f4eccc. Revoked Signature now not shown as a valid signature in Test Key Two.
