### ISSUE TITLE
Import Error. Unable to import one key due to exception: TypeError: Cannot read property 'userid' of null Import

### ISSUE THREAD

**Issue by lastknight** [mailvelope/mailvelope#376]
Key exported with:

`gpg --export-secret-keys -a mf@matteoflora.com --armo`

Key info:

`
sec   1024D/F3B6BC10 1999-12-13 [expires: 2019-07-29]  
uid                  Matteo G.P. Flora <mf@xxxxxx>  
uid                  Matteo G.P. Flora <lk@xxxxxx>  
uid                  Matteo G.P. Flora (The Fool s.r.l.) <mf@xxxxxx>  
uid                  Matteo G.P. Flora (Hermes Center for Transparency and Digital Human Rights) <mf@xxxxxx>  
uid                  Matteo G.P. Flora (GlobaLeaks Project) <mf@xxxxxx>  
ssb   4096g/5B9416C1 1999-12-13  
ssb   4096R/10384C36 2012-10-07`

I've tried Mailvelope now and then in the last 2 years, always with the same error.

**Comment by walterrenner** [comment]
My file i wanted import contains both parts, the private and the public Key.

I got around this Error by just importing the private Key.

**Comment by xxdesmus** [comment]
Exact same blocking problem.  Any progress on this?

**Comment by gregcope** [comment]
Same issue for me;

Unable to import a key due to exception: TypeError: Cannot read property 'userid' of null

I only have a public key.

**Comment by wowawebdesign** [comment]
Same problem here with latest version of Mailvelope, both in Chrome and Firefox. This issue is open since 2 years, when will there be a fix??

**Comment by toberndo** [comment]
Please provide a public key to reproduce the issue.

**Comment by wowawebdesign** [comment]
I can import a public key or a private key, but not a key pair. But importing only the private key seems to work. But that's not an expected behaviour, I think.

**Comment by toberndo** [comment]
Key pairs are imported: first public, then private key. Second operation is then a key update, so seems like the problem is related to key update.

**Comment by ckhung** [comment]
Importing this key for example gives the error "TypeError: Cannot read property 'userid' of null"
https://pgp.mit.edu/pks/lookup?search=jrfernandez%40ofset.org&op=index

The file was generated using
gpg -ao a.txt --export 2fc7cb1c0d709914
on lubuntu 17.10 using gnupg 2.1.15-1ubuntu8

**Comment by toberndo** [comment]
@lastknight Your key (https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xBD1E29B0F3B6BC10) can be imported now in Mailvelope 3.0 without errors.
