### ISSUE TITLE
Cannot decrypt message in google chrome

### ISSUE THREAD

**Issue by fujisan43** [mailvelope/mailvelope#378]
Since I cannot import my secret keys in firefox (see issue #365), I switched to google chrome (Version 49.0.2623.87 (64-bit)) where I succeeded to import all the keys (secret and public keys).
I installed version 1.3.6 of mailvelope extension.
When I send myself a message that I encrypt with my public key, I cannot decrypt it. I always get this error message:
`Error! Invalid enum value.`
Has anyone got the same problem on Firefox?

Regards,
Fuji

**Comment by toberndo** [comment]
> When I send myself a message

But the this message is not created with Mailvelope?

**Comment by fujisan43** [comment]
I don't know but I always have it when I click OK after entering the passphrase.

**Comment by fujisan43** [comment]
Here it is.
![mailvelope_error](https://cloud.githubusercontent.com/assets/10160128/13950850/a91b6c42-f02d-11e5-9250-3a52317ae3fd.png)

**Comment by fujisan43** [comment]
I may have misuderstood you. I created the encrypted message with mailvelope with my public key, send it to me and then when trying to decrypt it, i get this error message.

**Comment by fujisan43** [comment]
And all is done in gmail.

**Comment by toberndo** [comment]
I think this is related to ECC, which is currently not supported by Mailvelope. Does your key have a ECC subkey? Can you share your public key?

**Comment by fujisan43** [comment]
I don't think it was ECC generated. Subkeys are RSA 2048.

Anyway I succeeded to fix issue #365. The problem was that the keys I generated had no email address associated to them. So I added one and remove the id without email address.
I uploaded the keys on firefox and everything is working fine.

So I'm switching back to firefox.



-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: Mailvelope v1.3.6
Comment: https://www.mailvelope.com

xsFNBFbxWSsBEACjODywExkYaB2z+UNt9wMZlxPXafNDVlz4bYxTcAqxQq3Q
Fd//V7cw+FrmfNi5ke7RBSQg/hvTafr9axxpP4MoHOKGGpkAcJFrEqhw/ZO9
DMkXIxO2Z8JP3l04FKV2CgTtDDED23NSLjyXZ+KrimAHqQli4UBFYAmgUnPq
ysVIx6UtgccOltFBA2slOBIEpq9hJUdOw03BH66aKSWsxGBDeXUFu5FCjR0E
QAS9jfgt3G3x9/kWfQG6JKQX9HUjBoyteePvamAvFYIL+bjLTPcVzwppr5fJ
kXatFEyHx28GPEavActMBRY80b6NdwIcTO6dqikjYjAakMy4z8hW3oFWQfcB
9m0esd0DvviTzIR6pz+YpWM+YewbE+tFUKJyjRB39LcuX0UIZ/OpX6O/jtCE
I7p/WkfXR+AIKTMgFUxNODpdCdKiwC/87aPMtBrwvfrl7gM3S5Al8i3yEApw
Ek2Y0CtR3zy7YGoUpl6874gHGzZTLUVy15+rsv+Yq/KkL8WHruawSkoYUVFq
lYsH9HckDq3tcPzFvhenLWgpUB9ntOmanrMm/hc7QULRu3Y+nhYsZWU4rjCt
vsb1vDTY5A3CVvRJLf9xc6AiLYryAP8ztzPXevxh3vdjBGs2OhOUDfrGSdrR
haZ1j7XpNpodG0gj7P5DGg7bePmfyDjqT1D4OQARAQABzR1GdWppc2FuIDxm
dWppc2FuNDNAZ21haWwuY29tPsLBfQQTAQoAJwUCVvFZKwIbAwUJAeEzgAUL
CQgHAwUVCgkICwUWAgMBAAIeAQIXgAAKCRDD4Po1FpbG5RvfD/43/ei2Xtnc
EoGUgLoXBG14wr/fxaAD5MhDGO4Z22dovH2P1DzonkfRouPJ630ZlUjCJTOG
8dnbU1O8RWqiEMNgbXNG0MP22QGFclqzqQTv/cBRz5CJ7nRGFU8j62GHAqrL
JJGhYoap6oPD5+4gqRl+OBTz1n2vrggQGJsOFGZVOVVoQk2i8g2ifKo7TkGN
I1xuovMpbde51DEdPcc7kw36RaLaMwuEMr2Keeg//uDmZbUeUT0b8qZ8WUG1
TrvCTeixa2MQ5LU2LWwa/4Z4L9BOIx3QDJRblESKMl5UhAqvmKRGoHrwABwa
ReviOyM8p23ameVkyRHW2bu9Ir6Cx3Eb7+XCzELi3SNh3zdbhunykZd0lmZG
Ql3abADjZ2awiKXTAE27XVzfKuI4uWkCuT3W7ZKKollyc0zD0INQKnuafONh
0KTTB4lC7yymjFEQkLufn1eL6IbOYhhmXhqN4AldSYO+hy1rfq2ilxgSR8po
V23ufjgsu2Op6uDiVM66BaOlEVDHBFv9/213bgksdeh0oIjsBoCal6VeqVsN
mDS+JUEAvcPmMdaSWZojixu4JlUuD0NKUhamojlxrHjpZ2V6cl2g0yu9Qx2c
XkAqVIVXqUYtEwjvCs07wGf52/I+FIPOAhELfld/fDW+u/v0NMS0O6heEd5X
8o5gIk2LtKjbBM7ATQRW8V4LAQgArZKkd0xx5Odw96fq/qcHw9H6uz/QbtYc
cpScRKUFDxG0jBmPfo/ZugDgNTBrkow675ebpBIhDMFoBjXXYmP4Fg0qLr5C
weer3mNV991yv8pBOB+hFH1PZ73mZk+RQ5sakgtCbjNteP1kZDCu/cxeRw6c
5kNgI7KOKvIsbUVBWXIKQe+4LHwEQxAOV3CaFZpzSG5eoL9IeySBQ3A3DEr1
aEl8e30y+McSje1/2vS+f+xVe0Hy98ToOUDyr7P9fxZHB7fa1uZN1yIe5h+u
TOAmHGywgK2gZEYoO8+2TiTf+XpcWf+fkSI85ZmiJxGKYxdPhnEf8wphs/+q
xl3goHvvBQARAQABwsKEBBgBCgAPBQJW8V4LAhsuBQkB4TOAASkJEMPg+jUW
lsblwF0gBBkBCgAGBQJW8V4LAAoJEAGJ6QDq7z9rxAQIAJSND2awv+T2Mo3d
TU1gRbt4pGFsiaZEdFZj1Hjl5D+fzIInzuw7sndnoWHd9nsvGHcbapRx2aYV
7QbiQsFVHqSG8q/iikPqG8C00He5/pOuP3h1GYP6AvQQbq6Ya4ANi9p3nd/9
aWgO/Q7U1duJN+tAWtQVGsdN+RW3imK4cF0Pfb59gl9lxuqFh8Ww0sMp3yor
gqrELEXdLLHLi/9nqEqyW+zzXpA2IS9JFpewZWmz8VWATUe8Sed8cK4p49VP
yTk7oUmNRUKFZrqjmCKVjrLpUOKMgsuSBzfJ8pe34RFSOzYbFpDA0nHwAFer
hH9H8ZJvgvfGBY4P13Y20uVjgF6JnA/8CJAVJ4JBGeCmt+hLCZTgtZmkPgMu
HtALfajXBiRRKUGFa0WOOFibw1txW0bMj2xtuZXhJhL+2WE2gfEAxkilgRF2
yZj6QoRsrEIuD3CxSSMUpO9fuC4ztXHYNgDaY8Hslh4hnb7IQa7/8Pf5mjpA
uP2YqR8BgRFPwZOS5SQy+/A6BMAwa/yfuS8jL7xP38g7tgZRIrD+RX5Go3lY
+qNKeRNcClfBlEO0CeJTmLaP6Z7avYk8hALLrWWS3RtnyBp2XjVm/+Pt+yas
tbKvpDgw/gpjFk/qPPL9P4YZKhOpRuE8vpNOBZ/5caXOfEOhndksfO18oOVy
SgmQfCanojoAOHVUNReXKxcLeOCTbGC23uYMa+0O1pQlY/SDADXi3TIdso+W
4dE4GAmzlpMHY0hc2WUBcbNocdK5/jTkdJ0De94/gmPLaFFxi/nWXcMXbjci
PFhzld4OJltfFGmJDmina0HWoF4zKGZPohU7PGyIxVOxK5LMsmMW8V+ihy3f
mMwr/dtwReTVMA76mp8lqBpv94sBrvlpYMim3DwIPYdU6SUC/Zh+qELUs94S
rsCHemfgk4O1pCgsAoygCqshKj6UCGI7y4MUzSK1QZwXlec57fGechZ6dUlQ
ocW802eRmRTUZbYhoV6SQ7cSCVcEXbxvYeOuQngLunPrt3Y4ew7gTdvOwE0E
VvFfOAEIAK0kfnkbsn88P+blZfcOj/yc/0Qr1t3j95CmgNz2TwhFfusuUDFF
g2k77vQox2kMHLO98tsZlyCRNfs4CQBL/UDo0OqEiWoa1Uc7Frz4Oo41KLvs
j//ihD4bm10n9fS0QtnQDwrT1FnIQN0Z9yrDMYYkax+V2I3P35fY4pU7fE8u
X9XN2L6Q308avrOaqEXU9RZKYrZG/Fk73VvmLYwN8AHI8X8RikI899aMfnZP
PL70cFAW8BwPj/hhpBMxdQNTe3AqkEYfLgon8vINTLSOCUW7FNhx44K+Ach0
puLzpVGHUXeoif7hzksGxVQkF/X9oQSmKTQxrg8m9NXKVL98uUMAEQEAAcLC
hAQYAQoADwUCVvFfOAIbAgUJAeEzgAEpCRDD4Po1FpbG5cBdIAQZAQoABgUC
VvFfOAAKCRDndI6TSefB8UHtB/0dnRcUkXsuuV0nHaWQCZ017uyXbWYrLivE
VXrbhnuWcyfSLkmq3zVmwLU4m3HVE1YZHz2ZsZUKGeua+UyXBdnWVBoqnlnZ
d+alca0+8/i3QXaamuBkmbxLVfdV9fkYjThNbBSSjifdZcWF8LvmK1FyBWwq
5G8p3qxIQhkQA9QPGM7ZrlaCHxkH2XC1ngDOwZYWfoeUTkT48ok/tKHnUkDQ
tT8h44lL7b/GII4+Y9p+CnoePXjvyUdHelx3A8nRKU0tgJKWTpxPUCSJlxfR
boiTQaEvKbAFoDKt4jodfaGme9qSbQYEccS88YyYQlhYZd3YJlh2njgFx08X
pG7WD1xzvpIP/1WaqLfc+bS4ItRT3iNo3I8mcSI0DC6fRYVwHtCgqIq8NZgO
fW6pziH02ouH0O8MOr75I9j2hTRkhfuogvndbr3/AV43T8kV+ekMkhleteBg
kZUJz5C63agbNkthJoJDxwbP0dXUuxz08To7LCfo3PWvkXGb2gTmTigMxu+6
B3jgIEl7mKGrB+q1x62vNL761sWjmPRDErMng4gl+0nu9e5NuiRpbZHx62bz
M0jQq00ebsO/SPJRtT0vYNrX6V1SorHoiR7eFNFhWEd2OMp6FJ6ETkJN4e6B
dhCxHEsWloVpAgCsAfq8jJevRJQx1ZK7AzxemPQeR8GlqxS2JpoZertk18mm
k7akUrwMIu093ePvHX1kPrdQH6sTnJKhw8VhaOe1S/+5dF0faXGAGatMtb/2
UzhpNBsHlsKvPYAfMFoAnhlqrOweoE1DFKVowBnrmDrpHWXs9fd6w4lIrKb1
afyn2TCb6JuzDuV76D6hMHpyQ1phYCSNbQOQYILZI0q7Gk9eEUU9UBrIMK4r
QgozwvDe8aCgTfRIdXk6mC2iBXbZqTnRfFoMx+aMSgQvqD+ZYosGc0YVcoVL
Kl44qhCRP6qI1UEGi66B3QR3Ud7rYOyM4Vcgefj+zXJKvHepqQCAotdix0Gv
/r/vqUEB2ZBGu/jIFHHaYQwfQG/lNujSkJW0zsBNBFbxX34BCACdjryfOFXs
2FQBLcxAjTwYk1L1Zlc89tvgB/dJGs/3nkuTzdgFO98y3hOD94NCPzJZV+77
DwaSrLfcXc3MgRueF9r7ec+RvN9fK7vYSQDxJIg5pA8HTjh2irKGAu1hqaiy
W3sNNTqIrRkteL4My3okx7yY3uBLucpWyvbFY7uapOhfki4b6Cqm3lk4uE3x
FwZXGK8rCH8+o7I36wQb11zCzoAffvFowZ7P1AoHP8iMbSbceLjeeYXCHxXM
LayUPhRkWwWqTBKX5yEwjzxAhGsL+j6Igvih6w7iZhMOpfWZ92AjX/sqI97/
LZHsNS1HXgyO/lMt1v0Y4Jg6UHVlIFm7ABEBAAHCwWUEGAEKAA8FAlbxX34C
GwwFCQHhM4AACgkQw+D6NRaWxuXGKw//RA6Qhpanry1XdEttEmGTuKAkh4Ej
CdaVNsqqSzq/YzFtfeuG+eA1QUNbTYfNLsy9L2ANyrBAkDGodq5Qgi3MlYT8
GP9nhEv25Rh4hMEx0+m3C6SDbEtgLUclt7dnAKi+SGlAP+PkzpAXHuawehr7
OEtmZOItIx14tMzj4TGh0P91EhphTbf3lQJnpsGS8LaEYjtu67Pa5oui0Uoq
mHtPtMffuvwE+ySDvIob9/frqeccyODnNZuDvqLdPFPT0TxkRg3wzYqQT5lM
5MmCaTrQwCYpiWMhIPS9CEwyjm+SAtfO8f0BRmSYHAemG+U3IJYRH/OMrUxB
5dl/FjDE4pANiX+l/KpYr0+FFX/P9wF3YMrtlyNRN33ZjW0BQQfIj7jEC8tK
0bpKhbagvUrfGN9YRLGG84LB0GbOnMUvXxRb2Zr7XSb/dDIPnJkuiKgQrARQ
C8Q/Q1XxSd4uJ6oYrlK5sbT2seBOgZqUxckFU7Dd40oOgdts2sSTreDL0YaQ
ArJ58xh3QkY/Ddpbm8Rg+EaiexCupzaZ9ZcseIFeZfhvUm5yMd4WBbjtLj2z
ClNnVZD0TVV2z+ULTbW8nezF2i7S/XeHv72c8ZK+G35oKEkCeB3Hf/KgHX1A
kbTuaOLFG9sQ2PGlQLLFuY651YAEG/Isd7Ul7uN4X/HblkDQa0roMS3OwE0E
VvFfqQEIAKxivEdXID+YHlfGZrrbH8gIZ7Q+PsDb6W+iqJImJhLAuWL21x+0
iQGvpAQhc5pjbwWWGOxbLe7yfVtGEHC8bQ9aRTc78RRLkvc997UR1Rb2fSf7
+C6Fo7h1z9AE5LSHTv6LyN+8sfDLZN5Kj9ZGDNLvCBN1k8fqp23tAyQ3HQk8
9o46TuTQ6OL0dC6MaRD2hxYUxeC7LbLMhjLvDxt75DrqKn4CjDwUwlSVf4oU
DYj077DHBYW8B1U4eeIOBFUbbE3bcW4Fa5BoJ+JYJ4hk+r3fOWyqDIEiewls
X8cNk0IKi62JZr+OhZhcU6xrzEHMTwkMstc4WKFj+/ZGUGfHchsAEQEAAcLB
ZQQYAQoADwUCVvFfqQIbIAUJAeEzgAAKCRDD4Po1FpbG5dTbEACgYzzppGOR
JSeS65+N/j+bOxYLQS4xQm2Wg0VmN8MJ8RZv7y8lB3wf5dEUzPPygI9u6MHR
8Fyin3oE/IrxyIoKi+XFtHHvmgIu7vWYV1eC3gBdJy60A9NsH50SNZVdad6k
J+x00dhnVeQZh+/Mq03gSE2EYlsfD/8O4QSL2hheXL9VuQlHJ1F7A0OjmV6V
+Jv0TdtzOflOMZBWq4r8NuMP7FOYL3+lOXpFYXHr1QgjpUsF+qwfjMxlUvWg
zSGI3sAT15eo3+UGDvCi6g5jwEOMhl3e9MJlgI3JEYw22le0G26I95Hr0Iiw
A07yyFwK8mHTMqrF0Av1GOBPIW0auru5EjvPPKhGD8zOXbrIkrg32YIAhfNf
XFbZJWu005UGo8ZRFzn37pOuaMMSl/IYFliF0nf105Ht6oc21aTXau9tX2E9
G4+61xfhxAnLSxoog0LHH1x126Kc4nM890ugwxVTNm6/oK8a0sI6MsEbo02Q
Spm2mu6JIyowU45yPnB/QT7ubJSXJZcTB8Z8QgAI892vwW7yscIzNZmODDr5
rof6t7iV1XjCAYlZ9KAbk8h49HKxCPIotISXRjhwCzoV8zrXvvLOPoWLO/cy
DBt9lK6Is5cbm4VsmcaMLOYBnJkYUZRq+DXrPmDcmuOmEK+dyd8JGnHamw9S
/fQfIW1S/+94PQ==
=G8bX
-----END PGP PUBLIC KEY BLOCK-----

**Comment by JasperWeiss** [comment]
@toberndo 

> I think this is related to ECC, which is currently not supported by Mailvelope.

Do you plan to add support for ECC any time soon? I was actually thinking about getting a Yubikey and use it with ECC OpenPGP. It'd be nice if Mailvelope supports Yubikeys by the way.
It would solve the sort of "Don't do PGP in the browser" problem and it would make it easier for less skilled people to keep track of their key.

**Comment by toberndo** [comment]
@JasperWeiss ECC support is planned for https://github.com/openpgpjs/openpgpjs/milestones/v3.0
As soon as it is available in OpenPGP.js we can support it in Mailvelope.

**Comment by JasperWeiss** [comment]
@toberndo Great! Have you looked at Yubikey support? That'd be a real killer feature. I currently don't deel entirely comfortable storing my PGP key in a browser plugin. (Actually, storing it on a computer in general. If it's compromised, it's game over)

**Comment by toberndo** [comment]
@JasperWeiss Yubikey support would be nice. Problem is that AFAIK you cannot directly access the OpenPGP functionality of Yubikey from within the browser. That means some external application is required to do that part for Mailvelope.

**Comment by JasperWeiss** [comment]
@toberndo I noticed there's an add-on for firefox that implements U2F support. Can't the same be done for PGP?

**Comment by toberndo** [comment]
@JasperWeiss Firefox is moving to WebExtensions. Low level stuff like U2F support is probably based on XPCOM which will soon be deprecated.

**Comment by JasperWeiss** [comment]
@toberndo would it be possible to make a 'helper extension' that the add-on can use to interact with the yubikey? The same way that you can use a browser plugin that interacts with KeePass (password manager)

**Comment by toberndo** [comment]
@JasperWeiss I think you would use something like https://developer.chrome.com/extensions/nativeMessaging to connect Mailvelope to a helper application that can then access the Yubikey.

**Comment by JasperWeiss** [comment]
@toberndo Cool, so it is technically possible. I think Hardware tokens like Yubikeys could help to solve the biggest problem associated with doing PGP in the browser which is the fact that the browser is inherently insecure and should not hold your PGP key. 
I'd love to work on this but I'm only a beginning programmer so it's a bit above my skill set.

**Comment by fujisan43** [comment]
Hello,

I again got this error message : `Error! Invalid enum value.` (see above picture) on firefox.
I had to remove all the keys and import them again, those exported with `gpg2 -a --export`. Only then could I decrypt messages again.
Importing the keys exported by mailvelope doesn't fix the problem.

**Comment by toberndo** [comment]
In Mailvelope latest OpenPGP.js will drop invalid key packets which should prevent the "Invalid enum value" error.

**Comment by SharkIng** [comment]
Sorry that i got this issue again with the latest installation. I tried multiple time and I am sure the password i entered is valid. The key is 4096 RSA key and no matter how I Sign./Encrypt./Decrypt or change password, it keep telling me the password is wrong or "invalid enum value"
`Error in openpgp.decryptKey. Error decrypting private key: Invalid enum value.`
