### ISSUE TITLE
Error Unchecked runtime.lastError while running tabs.executeScript: The tab was closed.

### ISSUE THREAD

**Issue by devmessias** [mailvelope/mailvelope#379]
![captura de tela de 2016-03-24 15 49 14](https://cloud.githubusercontent.com/assets/6979335/14027815/47d092bc-f1d8-11e5-9003-7013f2b0aedb.png)
![captura de tela de 2016-03-24 15 51 46](https://cloud.githubusercontent.com/assets/6979335/14027827/5b33dc10-f1d8-11e5-8ecd-4a2a2df17cbe.png)

**Comment by devmessias** [comment]
executeScript and insertCss is causing another errors.
Unchecked runtime.lastError while running tabs.executeScript: Cannot access a chrome:// 
I found an alternative in stackoverflow, but is not safe
http://stackoverflow.com/questions/19042857/can-you-access-chrome-pages-from-an-extension

**Comment by toberndo** [comment]
These errors occur, but we don't log them anymore.
