### ISSUE TITLE
OpenPGP.js build errors

### ISSUE THREAD

**Issue by vphantom** [mailvelope/mailvelope#384]
Hello,

In following the instructions provided in the README I hit a wall in `dep/chrome/openpgpjs/` and `dep/firefox/openpgpjs/`, in addition to the dozen or so scary "deprecated" warnings I have a fatal error when running `grunt` in these two directories:

```
Warning: Command failed: npm install dist/openpgp-1.3.0.tgz

npm ERR! Linux 4.2.0-0.bpo.1-amd64
npm ERR! argv "/usr/bin/nodejs" "/home/lis/.node_modules_global/bin/npm" "install" "dist/openpgp-1.3.0.tgz"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.6
npm ERR! code ENOSELF

npm ERR! Refusing to install openpgp as a dependency of itself
```

I'm hesitant: is this an issue with my version of NPM, with the packaging done by Mailvelope or in OpenPGP.js 1.3.0's build process itself?

**Comment by toberndo** [comment]
> is this an issue with my version of NPM

Yes, build currently fails with node v5 and npm v3.x. Please use node v4.x which includes npm v2.x

**Comment by vphantom** [comment]
Yikes, I guess I need to familiarize myself with NVM. Thanks. :)
