### ISSUE TITLE
error: unable to import key

### ISSUE THREAD

**Issue by markuse** [mailvelope/mailvelope#387]
I'm unable to import the following key into mailvelope. Any ideas? 

-----BEGIN PGP SIGNATURE-----
Comment: GPGTools - https://gpgtools.org

iQIcBAEBCgAGBQJXLExlAAoJEOavvAFvPcE7ZdoP/RSBRzqJk02Hrp6n1mXSZTM7
ing5hCszHsRNYy1oCP57kjcwb0tpcfYFDeP6f1yp4qCIPTxyj7gPO/C61RloXtbF
S0jfSvXHnWJpckB27YukQ+SfhvmSkLQkOWCYop110Lv16R6MhKT5Z10HDzV+t+wZ
bqdEjvzv6YhTKElq6KOJOJutSt66nX0uBbua9BHctvCL4VZ8CDeuJLkmqId5o3KT
XVgModAn8Ei/J95PqDz/N8uKSZIjlXmcIPVEifWoPZQT6ylzCtd+CHnItqPFig5h
MYObOX6c5g8LQx89rGyVqVXbNEYP7C0WMzhWA9uxXmFGp0uroY3U04+b6fwBuQay
jr7gD0S1E053IDXgCHN/dDAYqeTp7RElksYam7t22NFM6Ivxvxz7I630sEqnGZfd
xfQDSasBLU15Tz1rNFjakTfKpYOZ5umRwsWXQiCVAd6AgeVuegbazCaJwrbyuJ/S
hFPr/ZzKhS/YO3TWKWeC2wiXy9rJkbFu7cKxm85+W8zv/mygBJKSBxOf7yS+DdkQ
l+EsUfAJWy/Ev/en1lnanToKOh9fEN1A7yoRx7ap43a1f9OareoEummg+p5joNYC
3ufLVZrlI6zby9nwLSVUZpJoU0Ibn5S+w6kJJ5aWOq27888BwqO71tD2R7B7UFil
jtsmP4cu0cM2DiyhGAXP
=Xg4H
-----END PGP SIGNATURE-----

**Comment by BjoKaSH** [comment]
Hi @markuse , that is not a key, but a detached, clear-text signature block as the header line "BEGIN PGP SIGNATURE" clearly says.
