### ISSUE TITLE
Error encrypting message

### ISSUE THREAD

**Issue by dnaber-de** [mailvelope/mailvelope#390]
I'm using mailvelope on MacOS (10.11.4) with the latest Chrome. When trying to encrypt a message I see the error message `error encrypting message`. 

The public key I'm using to encrypt is [`DD0DE528`](https://pgp.mit.edu/pks/lookup?op=get&search=0xD1636265DD0DE528)

Does the existing sub-key causes the problem here? If so, how can I solve this?

**Comment by toberndo** [comment]
Relates to https://github.com/openpgpjs/openpgpjs/issues/266
Multiple sub-key binding signatures currently not supported by OpenPGP.js

**Comment by dnaber-de** [comment]
Okay, thanks.
