### ISSUE TITLE
Sign GitHub releases with GPG

### ISSUE THREAD

**Issue by qua-bla** [mailvelope/mailvelope#392]
Since there is no other source / way to verify releases.

**Comment by toberndo** [comment]
You can find signed releases here: https://github.com/mailvelope/mailvelope/releases

Code signing key: http://keyserver.ubuntu.com/pks/lookup?op=vindex&search=codesigning%40mailvelope.com&fingerprint=on

Fingerprint=16F4 5CCC 1848 12B4 AC93  0EF3 60DD 1F16 B339 0CD1

**Comment by qua-bla** [comment]
Probably, you want to add your public key to your github profile such that the releases can be verified by github. <https://help.github.com/articles/adding-a-new-gpg-key-to-your-github-account/>
