### ISSUE TITLE
Mailvelope gives invalid signature error when verifying key with multiple identities

### ISSUE THREAD

**Issue by thinkprivacy** [mailvelope/mailvelope#395]
I have a GPG Key with 3 different identities attached to it.  When I sign an email with one of the identities Mailvelope gives an error when it tries to verify the signature.  It only checks the most recent identity in the key and doesn't check for other identities.

**Comment by toberndo** [comment]
This logic has changed in Mailvelope. Keys are now verified before you can choose them as a signing key. This issue might be fixed. If you cannot choose your key for signing, although it is valid, please re-open this issue.
