### ISSUE TITLE
Key search > import key

### ISSUE THREAD

**Issue by gregbkr** [mailvelope/mailvelope#396]
Hello,

I saw on the blog you implemented Key search > https://keyserver.ubuntu.com > click on ID > then import with the white/blue mailvelope key. But seems that I am redirected to mailvelope import key tab but no text is present. 

I am on chrome Version 51.0.2704.63 m. Though it is working on firefox.

![mailvelope](https://cloud.githubusercontent.com/assets/5642000/15655359/caa854f6-269c-11e6-96cf-03d03f6783c7.JPG)

Thank you! Good day!
Greg.

**Comment by toberndo** [comment]
This should be fixed with Mailvelope v2.0.0
Please reopen if problem persists.
