### ISSUE TITLE
Mailvelope key server integration

### ISSUE THREAD

**Issue by pat247** [mailvelope/mailvelope#400]
Can the Mailvelope [public key server](https://keys.mailvelope.com) be integrated into the Mailvelope extension (yet)?

v1.4, Firefox
Options / Key Server accepts neither hkps://keys.mailvelope.com nor https://keys.mailvelope.com.

"Just copy and paste hkps://keys.mailvelope.com into your current OpenPGP plugin and go"
https://keys.mailvelope.com/demo.html

I realize it's early days.

https://github.com/mailvelope/keyserver

**Comment by tanx** [comment]
Client integrstion is underway. Working on auto-lookup here:

https://github.com/mailvelope/mailvelope/tree/keyserver

There will be a blog post discussing the user experience for the next release.

**Comment by tanx** [comment]
We merely started discussing it now to get feedback from other GPG/OpenPGP user agents and plugings. In the final mailvelope users will not need to setup anything for lookup to work.

**Comment by toberndo** [comment]
Integration of the key server into the Mailvelope extension is now available with release 3.1.0: the synchronization status is displayed for each individual user ID of a key and there are options to upload or remove keys from the key server.
