### ISSUE TITLE
Password prompt disappears when navigating away from it before typing the password

### ISSUE THREAD

**Issue by aleksandar-todorovic** [mailvelope/mailvelope#409]
**System:** Windows 7 / Windows 8(.1) (I tried reproducing this issue on one more computer and I was able to do so)

**Browser:** Google Chrome

**Mailvelope version:** We haven't had this problem until the version **1.5.1** that came out recently.

**Affects:** Both encrypting and decrypting of the emails, and decrypting of the files (haven't tried encrypting them).

---

**Problem:**

We tell our staff to save all of their passwords (including the PGP one) in a password manager. The password manager we're using is accessible via a browser extension. So, when the window pops up asking them to enter their password and they navigate out of it to copy their passwords and then come back to the password window, the password prompt disappears and all they can do is to close the window.

**Workaround:**

Workaround that we're currently using is simply copying the password _before_ trying to encrypt/decrypt mail, but it is a pain in the ass because people tend to forget doing that until the password prompt pops out.

**Example:**

I tried decrypting a file. I selected it, clicked on `Decrypt`, password prompt popped out, I navigated away from it by clicking on the password management extension. Password prompt disappeared, Mailvelope showed a login screen and it got stuck there. Navigating away from the file decryption screen and navigating back to it didn't restart the process and the only thing that did restart it was restarting Chrome.

**Comment by toberndo** [comment]
Yes, that is a usability problem. The password dialog goes in the background once you click somewhere else in the browser. We had in previous versions of Chrome a mechanism in place that always pushes the popup back to the foreground when you click outside of the dialog, but that was a bit of a hackish solution and annoying once you switch to another tab and the password dialog stays in the foreground. I think a solution is to force the password dialog in the foreground, but only when the corresponding tab is active.

> We haven't had this problem until the version 1.5.1 that came out recently.

Can't confirm that, the described behaviour should be in place for quite a while

> the password prompt disappears and all they can do is to close the window.

It should still be there, but being pushed to the background

**Comment by toberndo** [comment]
The activation of the password popup has now been improved: when you navigate to another tab the popup will be set to the background. Once you navigate back to your mail provider page, we put it again to the foreground.
