### ISSUE TITLE
Google Inbox support

### ISSUE THREAD

**Issue by mikemol** [mailvelope/mailvelope#419]
While GMail seems to be supported, Google Inbox does not. It would be very helpful to have this rectified.

**Comment by SonofLiberty90** [comment]
Can confirm this.

**Comment by jgoclawski** [comment]
Looks like a duplicate of #241. BTW: It mostly works OK, but you have to add it as a provider manually.

**Comment by toberndo** [comment]
See: https://github.com/mailvelope/mailvelope/issues/241#issuecomment-253807614
