### ISSUE TITLE
invalid default recipients

### ISSUE THREAD

**Issue by mpetr** [mailvelope/mailvelope#421]
In Office365 mailbox, when I try to reply to any email...
**expected**: right default recipient or no recipient
**actual**: multiple invalid recipients, none of them is right, the list is growing and is hard/slow to manually fix by deleting them one by one

Screenshot here
![2016-09-06_10-26-33](https://cloud.githubusercontent.com/assets/1060428/18267456/74aa3594-741f-11e6-8360-bed21e3c2eb8.png)

What is the relation between the default list of Mailvelope's recipients and the opened email?

**Comment by toberndo** [comment]
This is now fixed in v1.5.2: per default no recipients will be transferred back and forth from the editor. Only for specific providers we implement the transfer, currently: Yahoo und Gmail. Outlook support planned.

**Comment by mpetr** [comment]
That was so fast! Thanks you very very much!
