### ISSUE TITLE
e10s: Mark your addon as compatible

### ISSUE THREAD

**Issue by rugk** [mailvelope/mailvelope#423]
A follow-up of https://github.com/mailvelope/mailvelope/issues/371

You can now use the manifest file to mark your add-on as compatible with e10s. Currently [ACR](https://addons.mozilla.org/firefox/addon/add-on-compatibility-reporter/) shows it is not compatible.

**Comment by toberndo** [comment]
This is already the case. Check out the install.rdf:
````
<em:multiprocessCompatible>true</em:multiprocessCompatible>
```

**Comment by rugk** [comment]
Is this already included in the latest release?

**Comment by toberndo** [comment]
Since:

v1.3.6
-------
__Feb. 24, 2016__

**Comment by rugk** [comment]
In this case you did something wrong. You can install ACR by yourself and check it.

**Comment by toberndo** [comment]
![bildschirmfoto 2016-09-09 um 14 34 15](https://cloud.githubusercontent.com/assets/1164474/18387064/a5e80fb4-769a-11e6-957f-d1ad1f96c471.png)

**Comment by rugk** [comment]
Ah, all right. I now see it too.
Must be chosen the wrong line.
