### ISSUE TITLE
FEATURE REQUEST: Allow the user to specify generated key size

### ISSUE THREAD

**Issue by cajuntechie** [mailvelope/mailvelope#425]
In the current release of Mailvelope for Firefox (current on 09/11/2016). Mailvelope does not allow the user to set the size of the key they wish to generate.  While this is not an issue for many users, some of them are not happy with the default size and wish to change it but cannot. 

Feature request: implement a way for users to choose the size of the key they wish to generate when generating a new key using Mailvelope.

**Comment by toberndo** [comment]
The key size setting is available in the key generation dialog when you click on "Advanced".
