### ISSUE TITLE
selected menuitem of the mailvelopeframe is not highlighted (only Firefox)

### ISSUE THREAD

**Issue by deepee2** [mailvelope/mailvelope#430]
Firefox: If the menuitem "Einrichtung" at the Mailvelope frame is clicked, the backroundcolor is not highlighted blue. The first menuitem "Schlüssel anzeigen" keeps highlighted blue.

![mailvelope_frame_firefox](https://cloud.githubusercontent.com/assets/11028366/18753761/9b6fe9e8-80e6-11e6-8292-8ae56c3b5883.png)

The behavoir of the chrome-plugin is correct, means the selected menuitem is highlighted blue.
![chrome_frame_firefox](https://cloud.githubusercontent.com/assets/11028366/18753760/9b56029e-80e6-11e6-9e6a-b138aef3289b.png)

**Comment by toberndo** [comment]
This issue is no longer relevant as the secondary menu is no longer available.
