### ISSUE TITLE
Scripterror at eventListenerer-function in mailvelope-client-api.js (Chrome)

### ISSUE THREAD

**Issue by deepee2** [mailvelope/mailvelope#431]
Chrome Version 53.0.2785.116 m
Mailvelope 1.5.2

mailvelope-client-api.js?_=1474959436410:612 
Uncaught TypeError: callbacks[event.data.id] is not a function

Firefox-addin is not affected.

![scriptfehler](https://cloud.githubusercontent.com/assets/11028366/18864564/345d4246-8497-11e6-917c-f9dfc6db842f.png)
![scriptfehler2](https://cloud.githubusercontent.com/assets/11028366/18864566/37a53fb2-8497-11e6-8e82-7a635ad4927d.png)

**Comment by toberndo** [comment]
Should be fixed in recent Mailvelope releases. Please reopen if problem persists.
