### ISSUE TITLE
Mailvelope website does not link to Mailvelope Code Signing key

### ISSUE THREAD

**Issue by runasand** [mailvelope/mailvelope#433]
The [latest release page](https://github.com/mailvelope/mailvelope/releases/latest) links to .asc files that allows users to verify their downloads. The downloads are signed with the Mailvelope Code Signing key, however this key is nowhere to be found on the Mailvelope website.

I found Thomas Oberndörfer's key on the [about page](https://www.mailvelope.com/en/about), but this is not used to sign the latest release.

**Comment by toberndo** [comment]
I added two sections to the FAQ:
[How does the automatic update process work for Mailvelope?](https://www.mailvelope.com/en/faq#updates)
[How can I verify Mailvelope downloads?](https://www.mailvelope.com/en/faq#codesigning)
The latter has also a link to the code signing key.
