### ISSUE TITLE
textParts[0] is undefined

### ISSUE THREAD

**Issue by rugk** [mailvelope/mailvelope#435]
I got this message when I wanted to "reply encrypted". The mail is an HTML mail and was sent with Thunderbird/45.4.0.
![decryptionfailed](https://cloud.githubusercontent.com/assets/11966684/19347340/9e320806-9148-11e6-8924-82af5cc88389.png)

Here is an anonymized version of the mail's HTML code:

``` html
<html style=""><head><meta charset="UTF-8"><link rel="stylesheet" href="resource://jid1-aqqsmbyb0a8adg-at-jetpack/data/common/dep/bootstrap/css/bootstrap.css"></head><body><div id="content" style="padding: 6px 12px; overflow: auto;">
    <font face="Calibri">XXX<br>
      XXXXXXXXX<br>
    </font>
    <pre cols="72" class="moz-signature">XXXXXX,
XXXXXXXXX

<a href="mailto:XXXXXXXXX" class="moz-txt-link-abbreviated" target="_blank">XXXXXXXXX</a> 
XXXXXXXXX
<a href="XXXXXXXXXXXX" class="moz-txt-link-abbreviated" target="_blank">XXXXXXXXXXXX</a> 
</pre>
    <div class="moz-cite-prefix">At DD.MM.YYYY Mr. Someone wrote:
      <br>
    </div>
    <blockquote type="cite">
      <pre>XXXXXXXXXXXXXXX (original mail)
XXXXXXXXX
</pre>
    </blockquote>
    <br>

</div></body></html>
```

I use a mail provider, who uses the Mailvelope API. Just viewing the message works without any problems, but when I want to reply to the encrypted mail the above error is shown and the original text sent is erased.

Mailvelope v1.5.2

**Comment by toberndo** [comment]
This should be fixed with the MIME parser update of Mailvelope 3.0.
Please reopen if problem persists.
