### ISSUE TITLE
Not able to import keys anymore because of Uncaught (in promise) TypeError: Cannot read property 'length' of undefined(…)

### ISSUE THREAD

**Issue by mschaaf** [mailvelope/mailvelope#436]
A private key is already uploaded
But it fails on the line `if (!privateKeys.length) {`

the bigger context is

```
function showSetupView(privateKeys) {
    // No private key yet? Navigate to setup tab
    if (!privateKeys.length) {
      $('.keyring_setup_message').addClass('active');
```

**Comment by toberndo** [comment]
Not sure what is happening here. The `showSetupView`method is not triggered after key import.

Is the following description correct for your case?
1. You have one private key imported. The key is valid, displayed correctly in the keyring and you can decrypt messages with this key.
2. You import another public or private key and it fails with the mentioned exception.

Thanks.

**Comment by mschaaf** [comment]
> 1. You have one private key imported. The key is valid, displayed correctly in the keyring and you can decrypt messages with this key.

This was possible days before. The key is valid until 2017. I didn't upload any other keys in the meantime
All the other stuff I can't check because the extension is now in a state that brings it in an un-useable state. No upload of keys, no key listing, no decryption and no configuration possible. 

> 2. You import another public or private key and it fails with the mentioned exception.

No. I had only one private key. Also after deletion of the local storage (all the keys), it fails with the same error.

In the meantime, I could solve the issue by removing the extension from chrome and reinstall it.
Maybe an update of the extension lead to the issue.

**Comment by toberndo** [comment]
Ok, now I get the picture. It looks like the data in the local storage of Mailvelope was corrupt, but I'm not sure what's the cause for this. Could also come from outside of Mailvelope. Normally deletion of the local storage should reset Mailvelope, but you would need to delete everything, not just the keys.
