### ISSUE TITLE
Problem with decoding long messages

### ISSUE THREAD

**Issue by irigi** [mailvelope/mailvelope#44]
I was trying to decode some of the longer messages I have in my mail and the Mailvelope doesn't seem to be working for them. There is one, which decrypts well under gpg, but not in mailvelope: https://www.dropbox.com/s/9pvc7abj3k2oa0w/failedPGPMessage.asc . The private key (passphrase 12345) is in the issue #43 . (I tried to send the message to myself by gmail, gmail interface truncates it, but it opens after clicking on the "show whole message".)

I tried the openpgpjs test http://openpgpjs.github.io/openpgpjs/test/encryption.html and it seems it has troubles with the decryption as well, so it may be bug in openpgpjs.

**Comment by toberndo** [comment]
Lots of updates to OpenPGP.js since this was reported. Problem might be related to missing bzip2 compression which is tracked in other issue, but not seeing any particular problem with longer messages.
