### ISSUE TITLE
Mailvelope error in decrypting e-mail

### ISSUE THREAD

**Issue by ezieragabriel** [mailvelope/mailvelope#440]
I can't decrypt an e-mail sent to me. It says `Error! Could not decrypt this message: Error: Ascii armor integrity check on message failed: '' should be '0Zo3'` when I open it using Mailvelope.

**Comment by Whoknowsit** [comment]
Make sure, that the mail is unformatted and not sent as HTML mail.

**Comment by toberndo** [comment]
Mailvelope supports now also PGP messages without checksum. But if checksum is there, it needs to be correct.
