### ISSUE TITLE
Email services cannot be added to the watchlist if Mailvelope Options is already open

### ISSUE THREAD

**Issue by 79068932** [mailvelope/mailvelope#441]

**Comment by toberndo** [comment]
Cannot reproduce in general. Please provide more details (browser version etc.)
Issue related to not working "Add" (to watchlist) button in Firefox for sites using CSP: https://github.com/mailvelope/mailvelope/issues/449#issuecomment-257576822

**Comment by 79068932** [comment]
Huh. This used to be an issue for me. It used to be impossible for me to add sites when the Mailvelope Options tab was open. Not anymore.

Thanks and sorry

Firefox 49.0.2 and Mailvelope 1.5.2
