### ISSUE TITLE
[Feature request] Create an option to automatically recognize PGP messages, signatures, and keys on webpages

### ISSUE THREAD

**Issue by 79068932** [mailvelope/mailvelope#444]
In other words, treat every website as if it's on the watchlist.

**Comment by toberndo** [comment]
This would have several disadvantages:
* The Mailvelope script would also run in websites like online banking or Paypal, where I would like to stay out in general or only with explicit user consent
* The scanning of the website that Mailvelope does costs performance, you would not want that on all pages

**Comment by rugk** [comment]
I also think this idea is rather bad for performance and is not worth it. If you want to import a key from a site (keyserver) add it to the whitelist.
