### ISSUE TITLE
[Feature request] Allow keys larger than 4096 bits to be generated

### ISSUE THREAD

**Issue by 79068932** [mailvelope/mailvelope#445]

**Comment by Izzette** [comment]
No one really uses > 4096 bit keys, what's even the point?

**Comment by 79068932** [comment]
No one uses >4096 bit keys because there isn't any software that supports it. If I recall correctly, the GnuPG developers actually removed the ability to generate >4096 bit keys a while back.

But that can change. And because computers are only getting more powerful, it should change. If someone is willing to sacrifice convenience for security, why not let them?

**Comment by toberndo** [comment]
Mailvelope will support the standard key sizes that are available in OpenPGP.js and GnuPG.
