### ISSUE TITLE
Use correct format when no name is entered

### ISSUE THREAD

**Issue by rugk** [mailvelope/mailvelope#446]
When creating a PGP key without a name the UID is `mail@provider.example`. However [according to RFC 2822](https://tools.ietf.org/html/rfc2822#section-3.4) the mail address should at least be `<mail@provider.example>`.

**Comment by toberndo** [comment]
Probably either old key or old Mailvelope version.
Since v1.3.4: `Use name-addr format if no name provided in userid at key generation`.

**Comment by rugk** [comment]
Okay, nice. So if this is already fixed, I'll close this issue
