### ISSUE TITLE
Support elliptical curves

### ISSUE THREAD

**Issue by rugk** [mailvelope/mailvelope#451]
Example keys: https://github.com/mailvelope/mailvelope/issues/281

**Comment by toberndo** [comment]
Depends on https://github.com/openpgpjs/openpgpjs/issues/427

**Comment by NoSubstitute** [comment]
It is now merged. Go for it!
https://github.com/openpgpjs/openpgpjs/pull/628
https://github.com/openpgpjs/openpgpjs/issues/427

**Comment by Queuecumber** [comment]
opengpgjs now has full support for ecc keys, when will this be merged into mailvelope?

**Comment by NoSubstitute** [comment]
Back in April I got this response.
https://twitter.com/mailvelope/status/992700976292298753

**Comment by toberndo** [comment]
ECC is supported with Mailvelope v3.0
