### ISSUE TITLE
Visual glitch, interference with other add-ons

### ISSUE THREAD

**Issue by 79068932** [mailvelope/mailvelope#452]
I use Firefox 49.0.2 and Mailvelope 1.5.2.

![mailvelope visual glitch](https://cloud.githubusercontent.com/assets/23144693/19989210/5700dae8-a1fb-11e6-9191-1ba5e68516aa.png)
![mailvelope visual glitch2](https://cloud.githubusercontent.com/assets/23144693/19989209/57005e24-a1fb-11e6-9c4b-9705bb45c978.png)

Before the interface got messed up, I was also unable to check signed messages or read decrypted emails.

![mailvelope bug](https://cloud.githubusercontent.com/assets/23144693/19989276/d296b88a-a1fb-11e6-86e3-b69d185d6a49.png)

**Comment by 79068932** [comment]
So I disabled all my extensions and re-enabled them one at a time to see if one of them was to blame for this problem. It seems like Random Agent Spoofer was screwing up the interface, but only when it was active (i.e., used to spoof a user agent), and even then, only under unknown conditions (it is possible for RAS to be active and for the interface to look just fine). YesScript was interfering with Mailvelope's ability to display messages, even when the relevant website was not on the blacklist. 

Not spoofing your user agent and disabling YesScript will eliminate this glitch immediately, but I'd like for this issue to remain open. This is a work-around, not a solution.

**Comment by toberndo** [comment]
Thanks for the detailed analysis. These sort of errors have been around for a while. It's good to have identified the problem as a correlation to other add-ons. But I guess it will be hard to fix it. As we are planning to migrate to WebExtension for Firefox in 2017, the architecture will change so fundamentally that it might also affect this bug.

**Comment by toberndo** [comment]
Should be fixed with the Web Extension release of Mailvelope (v2.0.0) which is now available.
