### ISSUE TITLE
Strings are not localized

### ISSUE THREAD

**Issue by 12people** [mailvelope/mailvelope#454]
After installing Mailvelope in Firefox, none of the strings in the UI are localized for me -- it's just the keywords shown. I'm not sure what the cause of that is.

![nonlocalized](https://cloud.githubusercontent.com/assets/7361228/20861406/b643ed50-b98f-11e6-944c-a6fb929681a9.png)

**Comment by toberndo** [comment]
Can you check if interference with other add-ons as described here apply in your case as well: https://github.com/mailvelope/mailvelope/issues/452#issuecomment-259004789

**Comment by 12people** [comment]
No -- turning off all the add-ons does nothing.
However, I have messed with the user agent in the past (to appear as another browser). I reset it using the guide at https://support.mozilla.org/en-US/kb/how-reset-default-user-agent-firefox, but perhaps it didn't clean up everything.

**Comment by Drugoy** [comment]
I am experiencing that too on latest stable Fx 50.0.2 under W7SP1x64.

**Comment by noplanman** [comment]
Me too, after the latest update to 1.6.0.

**Comment by noplanman** [comment]
As @12people mentions, I too can confirm that it is a user-agent problem.
When I have the "Random Agent Spoofer" plugin enabled, the localisation fails.

Any idea why this happens? Shouldn't the language for plugins be fetched from the browser itself?

**Comment by Drugoy** [comment]
@noplanman thanks for mentioning that spoofing user agent may cause this, I am using Random Agent Spoofer too.

**Comment by toberndo** [comment]
Should be fixed with the Web Extension release of Mailvelope: v2.0.0
