### ISSUE TITLE
How can I use All-Inkl Webmail with Mailvelope?

### ISSUE THREAD

**Issue by JPRuehmann** [mailvelope/mailvelope#458]
Hello How can I use the webmail Formular of All-Inkl with Mailvelope?

*.all-inkl.com won´t work.

Thanks,

**Comment by toberndo** [comment]
Please check here the howto: https://www.mailvelope.com/de/help#watchlist

**Comment by JPRuehmann** [comment]
Thanks, disabling API helped.
