### ISSUE TITLE
auto import keys

### ISSUE THREAD

**Issue by JPRuehmann** [mailvelope/mailvelope#466]
Hello
is it intended that if I write a Mail to a receiver that is not in the Keybase I must first import the receiver keys by hand by discarding the mail import the key and restart the mail?
Thanks,

**Comment by toberndo** [comment]
Not intended, but yes that is currently the limitation. Would be good to update list of receivers in editor without need to restart the editor.

**Comment by JPRuehmann** [comment]
or much more convenient automaticaly in the Background.

**Comment by toberndo** [comment]
The list of possible receivers in the editor is now updated once you import a key in the main app.
