### ISSUE TITLE
Encrypted e-mails from GMX account resulting in attached files

### ISSUE THREAD

**Issue by jweke** [mailvelope/mailvelope#469]
Hello github/mailvelope community

I encounter problems with encrypted messages leaving the GMX "universe".

**Problem-scenario**
1. Sending encrypted e-mail from my GMX-account to my gmail.com-account or hispeed.ch-account.
2. When opening the e-mail in my gmail.com-inbox see two attachments, both "noname".
3. When opening the e-mail in my hispeed.ch-inbox see two attachments "Part_1.pgp" and "Part_2.bin"

In both accounts the message-body is empty. mailvelope does not offer to decrypt the attachments (no problem).

**Control-scenario**
- Exchanging encrypted e-mail between gmail.com and hispeed.ch
The encrypted message appears inline like it should and mailvelope will decrypt it.
- Sending encrypted e-mail from gmail.com and hispeed.ch to GMX
The encrypted message appears inline and mailvelope will decrypt it.
- Sending encrypted e-mail from my GMX to my GMX.
The encrypted message appears inline and mailvelope will decrypt it.

Why does mailvelope / GMX attach the encrypted message when recipients are outside GMX?
How can I change this behaviour?
Is there anybody out there experiencing the same with other accounts?

**Comment by rugk** [comment]
This happens because in the API version of Mailvelope the mail is sent as S/MIME, which incompatible clients just show as extensions.

**Comment by toberndo** [comment]
There is some variation in how webmail clients display PGP/MIME. But in general the sender can set the header ‘Content-Disposition: inline‘ and then the webmail client should display the content as a message and not as an attachment. Unfortunately GMX doesn't set this header. They are aware of this issue, but so far haven't taken any action. So Mailvelope can't solve the issue, this has to be done on the mail provider side.
