### ISSUE TITLE
Decrypt *.* attachments/files instead of *.asc only

### ISSUE THREAD

**Issue by AlexStrobel** [mailvelope/mailvelope#471]
It would be helpful if mailvelope could decrypt attachments/files with any file extension and not with *.asc pattern only.
Is there any chance that this will be implemented somewhen? 
Why does mailvelope decrypt files with "asc" extension only?

**Comment by toberndo** [comment]
Mailvelope currently only supports file encryption with PGP armored text files. Hence the .asc extension. Do you have any examples of PGP implementations that use this format and do not use the .asc extension?

**Comment by AlexStrobel** [comment]
Thank you for your reply. 
Because of your answer I realized that my question should have been why Mailvelope is restricted to ASCII armored files only and not all types of files? :)
Is there any specific reason for this implementation and are there plans to implement the decryption of non ASCII armored files?

One of our customers asked us why one recipient of his email (who is using Mailvelope) can not decrypt non ASCII attachments. (Images, Word/Excel documents, ...)

**Comment by toberndo** [comment]
Yes, support for PGP binary format is planned and I think we will see that until end of March. My plan was to then support .pgp and .gpg file extensions. Do you see any other extensions? `*.*` would be also possible and then we decide during parsing if we accept the file, but I currently assume the restrictions to certain extensions provide a better usability in the file selection dialog.

**Comment by AlexStrobel** [comment]
Glad to read that this  feature will be implemented (somewhen).
I think supporting these three filetypes should be sufficient and won't be too much the user has to think about. 
In my opinion this issue is solved. Thanks you for your explanation! :)
