### ISSUE TITLE
Won't decrypt PGP messages with imported key.

### ISSUE THREAD

**Issue by VodooSupreme** [mailvelope/mailvelope#477]
Using Chrome, it won't decrypt PGP messages in email using an imported key. After entering the password it says, "Error! Invalid enum value". It will decrypt messages if you use a key that was created with Mailvelope. I tried this with two different computers and with Yahoo mail and Google mail.

**Comment by toberndo** [comment]
Probably the key uses ECC which is now supported with Mailvelope 3.0. Please try with latest release.
