### ISSUE TITLE
Button for adding an URL to the list of providers without function (FF addon only)

### ISSUE THREAD

**Issue by deepee2** [mailvelope/mailvelope#480]
Firefox 47.0.2
Mailvelope v1.6.5

- open URL in FF
- click "Mailvelope"-icon at toolbar
- click "Hinzufügen" for adding URL to the list of providers
-> no reaction
![2017-02-16 13_15_27-heise online - it-news nachrichten und hintergrunde](https://cloud.githubusercontent.com/assets/11028366/23021006/0e4232ec-f44a-11e6-96c3-8899741b91ab.png)

The addon for Chrome is not affected, means URL is added correctly to the list ov providers.

**Comment by lphooge** [comment]
I have the same problem, but I wasn't sure if I maybe misunderstood what that button is supposed to do exactly.

The documentation on how to use mailvelope from a providers point of view is really lacking IMHO.

**Comment by toberndo** [comment]
Fix for this will come with new release ~tomorrow

**Comment by deepee2** [comment]
Works with new addon version Mailvelope 1.7.1
