### ISSUE TITLE
Can't execute grunt in dep/chrome/openpgpjs and dep/firefox/openpgpjs

### ISSUE THREAD

**Issue by cesarandreslopez** [mailvelope/mailvelope#481]
Hello all!

When executing the following steps:

    git clone git://github.com/mailvelope/mailvelope.git
    cd mailvelope
    git submodule update --init
    cd dep/chrome/openpgpjs
    npm install && grunt
    cd ../../firefox/openpgpjs
    npm install && grunt
    cd ../../..
    npm install && bower install && grunt

Once i reach npm install && grunt on either chrome or ff /dep/---/openpgjs I get the following error:

    #
    # Fatal error in ../deps/v8/src/api.cc, line 1051
    # Check failed: !value_obj->IsJSReceiver() || value_obj->IsTemplateInfo().
    #

    ==== C stack trace ===============================

        0   node                                0x0000000100941a29 v8::base::debug::StackTrace::StackTrace() + 19
        1   node                                0x0000000100940733 V8_Fatal + 241
        2   node                                0x0000000100143fb9 v8::Template::Set(v8::Local<v8::Name>, v8::Local<v8::Data>, v8::PropertyAttribute) + 323
        3   fse.node                            0x0000000106081c6d fse::FSEvents::Initialize(v8::Local<v8::Object>) + 197
        4   node                                0x0000000100780929 node::DLOpen(v8::FunctionCallbackInfo<v8::Value> const&) + 855

        5   node                                0x0000000100169f93 v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const
    &)) + 389
        6   node                                0x00000001001aa433 v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCa
    llHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8
    ::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) + 915
        7   node                                0x00000001001a9a1c v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*)
     + 286
        8   ???                                 0x00003ec1578063a7 0x0 + 69000117642151
        9   ???                                 0x00003ec157b5ed5a 0x0 + 69000121150810
    Illegal instruction: 4

npm version is 4.1.2
node version is v7.3.0
Running Mac 10.12.3

Any ideas?

**Comment by cesarandreslopez** [comment]
Just tried this on a linux box and works ok, so it is an issue only seen on Mac.

**Comment by toberndo** [comment]
OpenPGP.js is now a npm dependency with Mailvelope v2.0.0
