### ISSUE TITLE
Error "domWindow is undefined" with gmail on firefox 51 & mailvelope 1.6.5

### ISSUE THREAD

**Issue by s-bernard** [mailvelope/mailvelope#482]
I cannot sign or encrypt a message. I get error "domWindow is undefined" when mailvelope is preparing the message.
Settings :
- mailvelope 1.6.5
- Firefox 51.0.1 (64 bits) Linux
- GMail

Thanks.

**Comment by s-bernard** [comment]
My bad, it is was due to the use of Tab Mix Plus with single window mode activated.

**Comment by knobhead** [comment]
but... but...

can't i haz single window mode? 😿
