### ISSUE TITLE
Automatic lookup for public key.

### ISSUE THREAD

**Issue by rasved** [mailvelope/mailvelope#483]
**Problem:** 
I need to have a public key in my keyring, when I want to write an email to someone. This means, I have to actively look her address up, manually add the public key to my keyring, and then go back to my mail editor to write the email. 

**Suggestion**
When I write a receiver for who I don't have the public key, it would be nice if the plug-in automagically look the address up on a (predefined) keyserver. 

R

**Comment by c8k** [comment]
Mailvelope does lookup keys automatically and you can choose if keyserver or/and WKD-server are used as sources. @toberndo I think this one can be closed :)
