### ISSUE TITLE
mailvelope cannot decrypt files that are not armored

### ISSUE THREAD

**Issue by tomholub** [mailvelope/mailvelope#485]
Files without ascii armor are within OpenPGP spec. OpenPGP.js can do this, just use `openpgp.message.read` instead of `openpgp.message.readArmored` when appropriate.

Here https://github.com/mailvelope/mailvelope/blob/a7efd4a8a7e90f6fecb8b434e3556451c511ef24/src/modules/pgpModel.js#L503

You can decide which one to use based on `text.indexOf('-----BEGIN .... -----')` being present within the first 100 bytes of the ascii or binary string.

Then people don't need to fuzz around with GPG everytime someone sends them a file.

**Comment by toberndo** [comment]
Binary format is now supported with .asc and .gpg files in Mailvelope v2.0.0
Thanks for reporting.

**Comment by tomholub** [comment]
That's great to hear
