### ISSUE TITLE
Sign git commits & releases (tags)

### ISSUE THREAD

**Issue by rugk** [mailvelope/mailvelope#488]
You should consider signing git commits & releases.

* [onionshare#221 (comment)](https://is.gd/7vU4oK)
* It is also displayed on GitHub: https://github.com/blog/2144-gpg-signature-verification
* Here is GitHub's help for this: https://help.github.com/articles/signing-commits-with-gpg/
* And here is how you can properly sign releases: https://wiki.debian.org/Creating%20signed%20GitHub%20releases ([and here is a script for that](https://github.com/rugk/gittools/blob/master/signrelease.sh))

**Comment by toberndo** [comment]
We activated signing of git commits a while ago. Also the extension packages in the GitHub release section are signed.
