### ISSUE TITLE
Mailvelope GitHub repo has no tags

### ISSUE THREAD

**Issue by gusandrews** [mailvelope/mailvelope#494]
Hey Thomas and co.! I would love to send developers to help work on Mailvelope, but it's really hard to identify which issues they can work on when so few of your issues have tags. 

Tagging by the [Up For Grabs](http://up-for-grabs.net/#/) guidelines (tag for "beginner-friendly," "up for grabs," "quick win," etc; tasks should not have many dependencies; tasks should be well-described and documented; they should be completeable in a few nights) would make it easier for new developers to help you out. 

Tagging UI issues as such would help XDs like me and UI devs plug into the project.

Similarly, tagging tasks which need QA assistance would help me figure out where to send QAs.

<3 <3 <3

**Comment by toberndo** [comment]
Hi Gus, tagging is good idea! The GitHub issues require some consolidation and I will also work on tagging for beginners. Regarding QA: @kevinmuller is working on a selenium test suite in https://github.com/mailvelope/mailvelope-selenium which should be available soon. Assistance  with creating test cases for the major UI scenarios would be helpfull as well.

**Comment by toberndo** [comment]
@gusandrews I tagged now messages with the label https://github.com/mailvelope/mailvelope/labels/up-for-grabs
This includes issues which are beginner friendly and implementation is relatively straight forward.
And it also includes topics that require UX work where a design proposal would be already helpful for us and the implementation is more an optional step.
