### ISSUE TITLE
Multiple Recipients?

### ISSUE THREAD

**Issue by TheByteStuff** [mailvelope/mailvelope#495]
When sending to multiple recipients, the first recipient in the list is presented in the decrypt dialog. There does not appear to be a way to select another recipient.  In addition, when opening the email from the sent side, the first recipient information is what is needed for decrypting as well vs the sender email.

Note: I am using multiple email addresses for which I have generated public/private keys for and are defined in the key management of mailvelope.  Is this an undocumented feature that it will only present the first option it finds that is defined with a private key in the local keystore?

**Comment by toberndo** [comment]
> Is this an undocumented feature that it will only present the first option it finds that is defined
> with a private key in the local keystore?

Yes, this is currently the limitation: we try to decrypt with the first available private key in the keyring. So if you have multiple private keys in your keyring and the message was encrypted for more than one (private) key in your keyring then the first is selected without the chance to select another private key you want to decrypt with. But does this practically cause any problems?

**Comment by TheByteStuff** [comment]
That's a good question.  If I have multiple email addresses attached to the same private key, then it doesn't matter all which one I am prompted for.  

As you understand in this case, I had two different private keys set up - one for each email address as I was in the process of documenting some sender/recipient scenarios.  So I was prompted to enter the passphrase for private key "B" while reading the email from the private key "A" address.  

To your point, as long as I have the needed passphrase then all is good.  I can''t define a use case that this is a problem for.  Just Seemed like a quirky scenario to ask about.
