### ISSUE TITLE
No proper text in Firefox (Antergos,KDE)

### ISSUE THREAD

**Issue by maikwoehl** [mailvelope/mailvelope#502]
Hello mailvelope team,
I've installed the mailvelope firefox extension on my Antergos machine running KDE 5.9.4 on 64bit.

The problem is that I'm seeing no proper text like you can see in the image I've appended.
Its look like the javascript can't switch the text to the l10n strings for my language. I'm german by the way.
The inspection tools doesn't show up an error.

[EDIT] It works, but this text issue is a little bit annoying. [/EDIT]

Thank you,

Maik

![screenshot_20170325_120011](https://cloud.githubusercontent.com/assets/864633/24321704/76166408-1153-11e7-976c-f744539bb43d.png)

**Comment by toberndo** [comment]
I think this should be solved with migration of Mailvelope to Web Extensions in Mailvelope v2.0.0
Please reopen if problem persists.
