### ISSUE TITLE
All keys and preferences lost for no apparent reason

### ISSUE THREAD

**Issue by lapineige** [mailvelope/mailvelope#503]
Hello mailvelope team,

I have an issue that I encounter from time to time and that is really annoying: sometimes, for no visible reason, all preferences, and keys, are lost.
I first tough it was because of Firefox Sync and because I didn't have the keys on the synchronised computers, but forcing a sync from another computer doesn't delete all preferences.
It does it if I disable the extension, which I didn't do. Maybe it's because of extension updates ?
Loosing the preferences is annoying but not a so big deal - but loosing my private keys is a no go.
(I have backups, hopefully)

Do you know what's happening ?
Thank you for your time.

**Comment by alecpl** [comment]
See #304.

**Comment by toberndo** [comment]
Closing duplicate.
