### ISSUE TITLE
Mailvelope labels broken on Firefox 55+

### ISSUE THREAD

**Issue by rvandermeulen** [mailvelope/mailvelope#508]
I suspect that this is a regression from https://bugzilla.mozilla.org/show_bug.cgi?id=1314861. The Options page all looks the same too.

![mailvelope](https://cloud.githubusercontent.com/assets/3661247/25350820/640c4440-28f4-11e7-9978-81deb855b76c.png)

**Comment by rvandermeulen** [comment]
I was able to bisect this down to being a regression from https://bugzilla.mozilla.org/show_bug.cgi?id=1346616

**Comment by rvandermeulen** [comment]
I've confirmed that Firefox 55 Beta builds are now also broken.

**Comment by toberndo** [comment]
@rvandermeulen Thanks for relating this to the resp. bug in Bugzilla. Hopefully there is a solution for https://bugzilla.mozilla.org/show_bug.cgi?id=1373061 as I'm not sure we will be ready with the WebExtension migration for Firefox 55.

**Comment by toberndo** [comment]
Still broken in 55.0b11. Seems like fix for https://bugzilla.mozilla.org/show_bug.cgi?id=1373061 didn't help in our case.

**Comment by rvandermeulen** [comment]
Something seems to have fixed this on Fx55/Fx56 now. Given that 56 is the last version to support this addon, this can probably just be closed out now.
