### ISSUE TITLE
maivelope.svg is not available (HTTP status code 404)

### ISSUE THREAD

**Issue by deepee2** [mailvelope/mailvelope#511]
Firefox 53
Mailvelope 1.7.2

- opening the De-Mail-Frontend (T-Deutschland) which includes the mailvelope iframe for manage keys (see screenshot)

- maivelope-logo.svg is not available (HTTP status code 404), perhaps its a typo maivelope/mailvelope?
![404](https://cloud.githubusercontent.com/assets/11028366/25709749/72470704-30ea-11e7-8b45-22b38278f454.png)

**Comment by toberndo** [comment]
Interestingly the type in maivelope-logo.svg is not the problem as it is consistent.
But this problem should be fixed with Mailvelope v2.0.0
