### ISSUE TITLE
Mailvelope displays only first text-part, swallows others

### ISSUE THREAD

**Issue by duckdalbe** [mailvelope/mailvelope#515]
Mailvelope (in API-mode) displays only the first "inline"-disposited text/plain-part and swallows all others, regardless of nesting. It looks like there were no more content, event though there is.

(Parts with disposition "attachment" are listed on top as expected.)

**Comment by toberndo** [comment]
Closing as duplicate of https://github.com/mailvelope/mailvelope/issues/516
