### ISSUE TITLE
Mailvelope ignores encrypted text parts in PGP/MIME mails

### ISSUE THREAD

**Issue by rugk** [mailvelope/mailvelope#516]
This makes it incompatible with [schleuder](https://schleuder.nadir.org/).
See issue https://0xacab.org/schleuder/schleuder/issues/192 for details.

In order to test this you can send a mail to `cute-cats-sendkey@schleuder.nadir.org` to get a key and afterwards an encrypted mail to `cute-cats@schleuder.nadir.org`, which you should get back as this is a mailing list.

**Comment by toberndo** [comment]
> can send a mail to cute-cats-sendkey@schleuder.nadir.org to get a key

Got the key

> afterwards an encrypted mail to cute-cats@schleuder.nadir.org,
> which you should get back as this is a mailing list.

Didn't get a reply, how do they know my public key?

**Comment by rugk** [comment]
Ah, yeah, referring to [this comment](https://0xacab.org/schleuder/schleuder/issues/185#note_107864) you also have to send your public key to them (too schleuder@nadir.org, maybe).

**Comment by toberndo** [comment]
This is how the MIME looks like:
```
----==_mimepart_591c5b4239450_3fa16372fc727b2
Content-Type: text/plain;
 charset=UTF-8
Content-Transfer-Encoding: quoted-printable

From: "Thomas Obernd=C3=B6rfer" <thomas@mailvelope.com>
To: cute-cats@schleuder.nadir.org
Cc: =

Date: Wed, 17 May 2017 16:16:27 +0200
Sig: Unsigned
Enc: Encrypted

----==_mimepart_591c5b4239450_3fa16372fc727b2
Content-Type: text/plain;
 charset=UTF-8
Content-Transfer-Encoding: quoted-printable

https://github.com/mailvelope/mailvelope/issues/516=

----==_mimepart_591c5b4239450_3fa16372fc727b2--
```
Question how normal MUA would handle that. Simply concatenate all parts?

**Comment by duckdalbe** [comment]
> Simply concatenate all parts?

Yes. E.g. Thunderbird shows a thin line in between the parts, Mutt prefixes each part with it mime-type anyway (separates it thus), Claws shows the parts without separation.

**Comment by toberndo** [comment]
Test builds available here:
https://build.mailvelope.com/nightly/mailvelope.2017-05-19.chrome.crx
https://build.mailvelope.com/nightly/mailvelope.2017-05-19.chrome.zip
https://build.mailvelope.com/nightly/mailvelope.2017-05-19.firefox.xpi

**Comment by duckdalbe** [comment]
Works well in Chromium 58.0.3029.110 on Linux!

Thank you very much!

**Comment by ge-fa** [comment]
Any chance of a new release, including this fix?

**Comment by toberndo** [comment]
Mailvelope v1.8.0 has been released, including this fix.

**Comment by ge-fa** [comment]
Thanks!
