### ISSUE TITLE
Auto-detect recipients 

### ISSUE THREAD

**Issue by tbelaire** [mailvelope/mailvelope#52]
It currently takes a lot of clicking around to use
Currently it looks like:
1. Open popup editor and type away
2. Click Lock.
3. Click list of recipients 
4. Click on particular recipient.
5. Click add.
6. Click ok.
7. Click transfer back

I'd like it if there was a way for it to parse my 'To:' field, and by default add those people's keys, as well as have a "encrypt and transfer button" to shorten the loop down to:
1. Launch popup editor
2. Type my reply then click Lock.
3. Verify the right people are there, and click encrypt and transfer.
   Much less clicking around, I think it would be a nice ease of use improvement.

Possible downside:
If you accidentally reply to all, it's easier to add extra people, since you don't have to add each by name anymore.  But there's still that verify step, and it'd be easy to spot a large list opposed to a single entry (I'd hope).
It also might be harder to have it work on all sites, the more integrated it is with each.

**Comment by toberndo** [comment]
Recipient transfer from/to editor available for Gmail and Yahoo, working on Outlook.com
