### ISSUE TITLE
Invalid enum value

### ISSUE THREAD

**Issue by techmagus** [mailvelope/mailvelope#521]
I get an "Invalid enum value" when decrypting a content encrypted with my key. Not sure what's happening. It was good last week.

My pubkey is here: [https://keybase.pub/yukino/keys/jc_john_sese-cuneta.0xDF3B8EBFD250A680.pub.asc](https://keybase.pub/yukino/keys/jc_john_sese-cuneta.0xDF3B8EBFD250A680.pub.asc)

![image](https://user-images.githubusercontent.com/1079205/27506086-882e2a40-58e3-11e7-936c-06834d760a37.png)

**Comment by techmagus** [comment]
Figured out what's happening. It turns out, mailvelope can not read CAMELLIA cipher. After converting back to AES, it works again.

Any chance CAMELLIA cipher will be supported in the future?

**Comment by toberndo** [comment]
CAMELLIA is not part of the specification: https://tools.ietf.org/html/rfc4880#section-9.2
I don't that this will be supported in OpenPGP.js

**Comment by techmagus** [comment]
I see. But reviewing RFC4880, it did mention an update, RFC5581 for use CAMELLIA in OpenPGP. Like in any other legalise documents, an update is like an attachment to an existing law or standard (in this case) because there's no need to rewrite the whole thing.

Hmm… In any case, I think this one lies on OpenPGP.js. Thank you for the heads-up!
