### ISSUE TITLE
The link is not HTTPS.

### ISSUE THREAD

**Issue by ghost** [mailvelope/mailvelope#528]
Mailvelope - Import Keys

Import Keys
Key search
Search for public keys on key server.
Key server pgp.mit.edu (Change)

The link "pgp.mit.edu" is HTTP. It should be HTTPS.

**Comment by toberndo** [comment]
Fixed with https://github.com/mailvelope/mailvelope/commit/ccffcc0737d52b26bba0eef32f7b82e9af911d45
But his will only affect new installations of Mailvelope
