### ISSUE TITLE
Firefox warning about use of deprecated getAttributeNode()

### ISSUE THREAD

**Issue by rvandermeulen** [mailvelope/mailvelope#536]
Noticed this in the Firefox browser console:
Use of getAttributeNode() is deprecated. Use getAttribute() instead.  background.bundle.js:28351:23

Looks like it happens when I click on an encrypted message it does the little sliding animation.

**Comment by toberndo** [comment]
That happens in an external dependency of Mailvelope: https://github.com/cure53/DOMPurify/blob/master/dist/purify.js#L354
Not much we can do about here. But i don't think it is critical.
