### ISSUE TITLE
"Encrypt attach" opens a new popup window behind the main browser window.

### ISSUE THREAD

**Issue by ignaciovidalfranco** [mailvelope/mailvelope#538]
Hello:

I was trying to send an email with attached encrypted files, so I:
- Opened gmail
- Started composing the mail
- Added the recipients
- Clicked on the mailvelope icon
- On the new popup window, I clicked on "Encrypt attachment" and...

... the new popup window closed and a new window opened BEHIND the main browser window, so I wasn't able to see it and it wasn't obvious that my actions were successful.

I guess this is not the expected behaviour, so I'm posting this here.

OS: Ubuntu Linux 16.04
Browser: Mozilla Firefox 55.0.2 (64bit)
Mailvelope version: 1.8.1

Active extensions:
AdblockPlus 2.9.1
Privacy Badger 2017.9.12.1
Mega 3.15.13
uBlock Origin 1.14.10
Ubuntu Modifications 3.4

**Comment by toberndo** [comment]
This is currently a bug in Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1400264

**Comment by toberndo** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1400264 seems fixed and I could also reproduce that the link opens a new tab in latest Firefox.
