### ISSUE TITLE
Mailvelope for Firefox breaks Google Inbox conversation/message expansion

### ISSUE THREAD

**Issue by cdokolas** [mailvelope/mailvelope#540]
Since Sunday, Oct, 1st (could be Sat., Oct 30th, but I'm not sure), I had problems fully expanding conversations and specific messages in Google Inbox. I would click on a conversation and it would show the collapsed messages within it. But then, I was unable to fully expand any messages or expand "bunched" messages (older ones collapsed to a double line with a number in a circle on the left).
All other browsers had no problems (no Mailvelope in them), Firefox in safe mode worked fine. As soon as I deactivated Mailvelope, Google Inbox worked fine.

Windows 10 64-bit
Firefox 55.0.3 32-bit and 64-bit

**Comment by toberndo** [comment]
As Google Inbox is deprecated, I'm closing old issues related to it.
