### ISSUE TITLE
Error! Error in openpgp.decryptKey

### ISSUE THREAD

**Issue by madchap** [mailvelope/mailvelope#544]
Hi,

I have been using your terrific plugin with office365 on google chrome, but today, a red error pops up after typing my key password. Note the same behavior happens also on gmail, as I just tested out. I don't use it everyday, and this is the first time I encounter this behavior.

`Error! Error in openpgp.decryptKey`

This happens on Linux and Mac. The plugin does select the entire ascii pgp text correctly (visually).

Chrome version: 61.0.3163.100 (mac) and 61.0.3112.101 on Linux (opensuse tumbleweed).

Screenshot with chrome console output: https://drive.google.com/open?id=0B-qOhAZJNwmQNDNEbVFsNDhzVnc

Thanks for your help.
Cheers,
fred

**Comment by madchap** [comment]
Also, I can actually encrypt out. Only the decrypting seems possibly "broken".

**Comment by madchap** [comment]
Sorry for the noise.. I re-imported they key after seeing something fishy, and it works now. My bad!

Cheers,
fred

**Comment by arsham** [comment]
I am getting the same error when I'm trying to input my password. My key is SE, generated with gnupg 2.2.1 (linux)

**Comment by madchap** [comment]
Re-import your key and make sure the private key part is in it. It is likely you imported only the public key part of your key.

**Comment by arsham** [comment]
Done that already, didn't help. Cheers.
