### ISSUE TITLE
Support keys from ed25519 algorithm

### ISSUE THREAD

**Issue by lifehome** [mailvelope/mailvelope#547]
My PGP key was using on Github and other places, and it is fine until comes to Mailvelope, which obviously does not support ECDSA algorithms. Would there be such support for such feature?

Step to reproduce:
1) Type in my key id in the configuration page
2) Click search, then it should redirect to ubuntu keyserver
3) I'm here >> https://keyserver.ubuntu.com/pks/lookup?op=index&search=0x5743B814494C7C58362B96BA4B155ECEBCC832AF
4) Click my key ID, then seeing Mailvelope with a ➕ cursor icon
5) Click the key stash to add into Mailvelope
6) Error!

**Comment by lifehome** [comment]
Give a little push as it really needs attention.

**Comment by tycho** [comment]
Ed25519/Curve25519 support just got merged in the OpenPGP.js project, so it now could be possible for Mailvelope: https://github.com/openpgpjs/openpgpjs/pull/618

Any Mailvelope devs looking at this?

**Comment by bratkartoffel** [comment]
Another push, i would need this too :(

**Comment by toberndo** [comment]
Ed25519/Curve25519 is supported in Mailvelope 3.0
