### ISSUE TITLE
not working with Protonmail.com encrypted email service

### ISSUE THREAD

**Issue by craigarno** [mailvelope/mailvelope#550]
Using public key downloaded from Protonmail, message on Protonmail Inbox remains encrypted.  Same Protonmail key with Thunderbird/Enigmail/Gmail decrypts properly in Protonmail.

Protonmail support asked for Mailvelope support to look into this issue to help determine cause.

**Comment by msiqx9** [comment]
I have also encountered this problem.  I installed FlowCrypt as a Chrome browser extension and this has no problem sending messages to Protonmail using the Protonmail public key.  The FlowCrypt interface also seems nicer.

**Comment by toberndo** [comment]
This should be related to ECC keys, which are now supported with Mailvelope 3.0
