### ISSUE TITLE
Blank unlock popup in Firefox 57 in GMail

### ISSUE THREAD

**Issue by noahschoem** [mailvelope/mailvelope#552]
Issue: When I try to decrypt an encrypted message in GMail on Firefox 57, the unlock popup where I normally enter my password for the key is blank.

Steps to reproduce:
1. Receive email encrypted with a password-protected key in GMail
2. Try to decrypt email

Expected behavior:
A popup prompting for the key's password appears. Enter password, hit OK, email decrypts

Actual behavior:
The popup is blank

Version: Firefox 57.0 on ArchLinux

**Comment by toberndo** [comment]
This is due to a bug in Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1408446
Seems like fix will be available with Firefox 58.
Workaround is to resize the popup window, then the content will be shown.

**Comment by noahschoem** [comment]
Thank you!
