### ISSUE TITLE
result.signatures is undefined (Firefox)

### ISSUE THREAD

**Issue by rschuetzler** [mailvelope/mailvelope#553]
I'm using the Firefox extension to have my students encrypt some messages, and I'm running into an error message from a few of their messages. In Firefox/Gmail, when I click to decrypt a message, I get the error message:

```
Error! result.signatures is undefined
```

In Chrome/Gmail when I try to decrypt the same message, I get a different error:

```
Error! Cannot read property 'map' of undefined
```

Any idea why I'm getting this error?

**Comment by toberndo** [comment]
This happens when you try to decrypt an empty message.
Fixed in: https://download.mailvelope.com/releases/v2.1.0b2/
