### ISSUE TITLE
Blank input dialogs on Firefox (Linux) 

### ISSUE THREAD

**Issue by fanfan70** [mailvelope/mailvelope#558]
When opening a received encrypted message, the password input window opens but is empty. Have to resize it to make content appear.
Also happens when composing a new mail.

Mailvelope 2.1.1
Firefox 57.0.2 64 bits
Linux

**Comment by tl-pierre** [comment]
Hi,
Same error here !

Mailvelope 2.1.1
Firefox 57.0.4
Debian 9

**Comment by kapn1966** [comment]
Ditto. 
Mailvelope 2.1.1
Firefox 58.0.1
Ubuntu 17.10

**Comment by toberndo** [comment]
Bug in Firefox on Linux: https://bugzilla.mozilla.org/show_bug.cgi?id=1408446
Can't see a work around, calling `window.resizeTo(window.outerWidth, window.outerHeight)` in our popus after loading didn't help.
Mozilla plans to fix this bug with Firefox 60.
Work around: resizing the popup window with the mouse will repaint the window and content appears.

**Comment by JediBrooker** [comment]
Right clicking on the window seems to help too.

**Comment by waldher** [comment]
This issue persists in Firefox 60.

Mailvelope 2.2.2
Firefox 60.0.1
ArchLinux

**Comment by ianGre** [comment]
This never happened to me until *recently*. 

[ macOS High Sierra v.10.13.5
Firefox 60.0.2 (64-bit)
	Mailvelope 2.2.2 ] 

Then it has been happening 100% of the time! No mention of this on the website. No way to find a Mailvelope Toolbar icon in the browser. 

I have installed this on one or more other browser and device.

**Comment by toberndo** [comment]
Fixed in Firefox 63
