### ISSUE TITLE
Allow Mailvelope to work in Zendesk agent interface

### ISSUE THREAD

**Issue by tjbaker** [mailvelope/mailvelope#561]
I attempted to add Mailvelope as an email provider to the Zendesk agent interface by following the watchlist instructions in the online help[1].  This would allow our agents to pgp sign responses and potentially verify signatures.  With the domain pattern listed I attempted several page refreshes and am still unable to get the "compose" envelope icon to display in text entry elements on the page.  I've tried adding the page numerous times via the "activate on current tab" ui option and that has not helped.  

Any advice?

[1] https://www.mailvelope.com/en/help#watchlist

**Comment by tjbaker** [comment]
I restarted Chrome and now signed messages in a ticket display the red wax seal icon and I can verify the signature, so that is progress.  Unfortunately text input elements on the page still do not show the compose icon.

**Comment by toberndo** [comment]
There is a minimum height for text elements which is currently set to 84px, for smaller sizes Mailvelope will not identify the element as a valid input field. Could this be the reason?
Otherwise we would need access to Zendesk to analyze the site structure. Possible to have a test account?

**Comment by tjbaker** [comment]
Minimum height was in fact the issue.  The good news is that the input element grows with carriage returns and by hitting enter a few times the compose icon does appear.  You can close this issue, and thanks.
