### ISSUE TITLE
Not showing up on Yandex mail

### ISSUE THREAD

**Issue by skygate2012** [mailvelope/mailvelope#564]
![setting](https://user-images.githubusercontent.com/7148976/36338640-e77783c6-13ef-11e8-982f-8c82e74dc2c4.png)
I've add it to the list of email providers, but no popup is shown on Yandex mail.
![ym](https://user-images.githubusercontent.com/7148976/36338720-6892c064-13f1-11e8-972d-bed972efdd6e.png)

**Comment by toberndo** [comment]
This should work after browser restart in 2.1.1.
Or now fixed in the new version 2.2.0.
