### ISSUE TITLE
[Feature Request] Edge Browser extension

### ISSUE THREAD

**Issue by AnthonyBe** [mailvelope/mailvelope#572]
Would an Edge Browser extension be possible?

**Comment by Mikaela** [comment]
Considering https://www.mailvelope.com/en/ links to Edge Store, I think this has been fixed.

**Comment by toberndo** [comment]
Yes, Mailvelope is available for Edge and you can download it here: https://microsoftedge.microsoft.com/addons/detail/mailvelope/dgcbddhdhjppfdfjpciagmmibadmoapc
Current limitation: only in English.
