### ISSUE TITLE
API can not be used if mail provider frontend does not use the standard https port 443

### ISSUE THREAD

**Issue by deepee2** [mailvelope/mailvelope#577]
Chrome 66 + Mailvelope 2.2.1
Firefox 60 + Mailvelope 2.2.1

- add new e-mail-provider (in this case a test system with port https://localhost:8080)
- activate API-switch
- open testsystem
-> testsystem does not detect the mailvelope IFrame for managing keys or writing a new mail

additional information:
- if the testsystem uses standard port 443 the IFrame is available 
- works fine with same test system, same settings and e.g. Firefox 47 + Mailvelope 1.7.1

**Comment by dysbulic** [comment]
I found this to still be true in 4.3.1. I have to serve from 443 with a trusted SSL cert in order for the `mailvelope` object to be inserted into the page.

The state of the HTTPS-only toggle had no effect.
