### ISSUE TITLE
PGP vulnerability: EFAIL attack

### ISSUE THREAD

**Issue by rugk** [mailvelope/mailvelope#578]
So this is going crazy right now: https://efail.de/

I did not look into the details, but it works because of a combination of HTML parsing and some cryptographic stuff.

So:
* Were you informed about this vulnerability prior to release today?
* Is Mailvelope affected by this?
    * Do you use the Modification Detection Code and require it? (i.e. use AEAD authenticated encryption, which mitigates this attack)
* What do you advise Mailvelope users?
* As for the [explained mitigation](https://efail.de/#mitigations):
   * > Short term: No decryption in email client.
       
      Does this work by copying text into Mailvelopes "manually decrypt window" or is that also affected by this attack, because it is not a single CLI tool?
    * > Short term: Disable HTML rendering.
       
       It is described that disabling HTML mail/parsing prevents this attack? I found no option to do this in Mailvelope. Is this planned/can this be added? (could also be useful independent of that actual attack)
    * > Medium term: Patching. 
       
       Is there any plan for that already? I.e. what is Mailvelope considering to do now?

Generally maybe these questions are also better answered in a blog post, BTW.

**Comment by FreedomMercenary** [comment]
I tried replicating the attack with Mailvelope and the interaction of the CSP controlled iframes might be blocking the attack.  This relies on eventually mixing the encrypted content with HTML and I so far can't replicate that in Mailvelope.

The most interesting related bit of content is definitely this one:
https://github.com/mailvelope/mailvelope/issues/410

But even in this scenario it doesn't lead to encrypted text getting decrypted and then passed over a URL or the like because when leaving the img src attribute unclosed it is undetected in Gmail as even signed.

Hopefully the maintainers can give final confirmation or denial that Mailvelope is affected.  I'm curious if anyone else has been able to replicate the attack vector when decrypting with Mailvelope.

**Comment by toberndo** [comment]
The Efail paper describes three types of attacks:

1. Direct Exfiltration

Mailvelope is not affected by attacks described in chapter 3.1 in the Efail paper. There  is a strong isolation of decrypted plaintext in Mailvelope and the rest of the MIME structure.

2. The CFB Gadget Attack

Malleability of plaintexts is detected in OpenPGP.js and will raise an exception, therefore modified messages will never be displayed in Mailvelope. With the restriction that this check on MDC will only happen for AES and not for older symmetric algorithms (see https://github.com/openpgpjs/openpgpjs/issues/706). So for old keys (>15years) this could be an issue if AES is not the preferred symmetric algorithm and we do not detect a modification of a PGP message. But I'm not sure about practicability of this attack as we also apply DOMpurify before rendering the HTML of the message and therefore erasing something like `">` from the plaintext should be detected.

3. General backchannel problem

We do not block requests to external resources, therefore leak metadata. That's not nice, but should also not be confused with leaking plaintext as in 1.

Advice to users: Mailvelope to Mailvelope encryption with in Mailvelope generated keys is uncritical. Be aware of older keys (>15 years) that have the potential to circumvent our detection on integrity protection.

Fix for 2: is planned for tomorrow as described in https://github.com/openpgpjs/openpgpjs/issues/706
Fix for 3: we are considering limiting the display of decrypted email to plain text messages, mid-term: block external resources and only load on user request.

> Does this work by copying text into Mailvelopes "manually decrypt window" or is that also affected by this attack, because it is not a single CLI tool?
The manual text decrypt feature uses the same component, so no difference here.

Blog post is in the making.

**Comment by mdik** [comment]
> We do not block requests to external resources, therefore leak metadata. That's not nice, but should also not be confused with leaking plaintext as in 1.

Apropos, why is that? The text editor has no WYSIWYG functionality, so I don't see any HTML entering the to-be-decrypted  text, so also no need to interpret any HTML. And if, I'd say it would still be ok to not load any external elements ¯\_(ツ)_/¯

(should I open a new issue for this?)

**Comment by toberndo** [comment]
Blog post: https://www.mailvelope.com/en/blog/implications-efail-on-mailvelope

@mdik New issue for blocking external resources makes sense

**Comment by rugk** [comment]
Maybe you should be clear to mention that Mailvelope users are of course only save if all other recipients and ("all") senders of PGP messages also use fixed clients/are not affacted. Otherwise, the attacker can of course attack them and extract the plaintext from their clients.

**Comment by My1** [comment]
about interpreting HTML, I would be careful.

FAcebook's encrypted emails for example are a total stream of HTML. whether it has external stuff inside I have no odea but at least HTML should stay at least as an option.

**Comment by toberndo** [comment]
Loading remote content in decrypted messages is blocked since v3.0.0
