### ISSUE TITLE
Feature: Support for key lookup using Web Key Directory protocol

### ISSUE THREAD

**Issue by wiktor-k** [mailvelope/mailvelope#580]
[Web Key Directory is a draft](https://datatracker.ietf.org/doc/draft-koch-openpgp-webkey-service/) for a new key discovery scheme (implemented e.g. in new gnupg). It is similar to HKP but instead of querying the keyserver it queries the domain from the UID's e-mail address. The difference is that WKD returns binary data and HKP ASCII-armored.

For example, when looking for key for `Joe.Doe@Example.ORG` the key would be fetched from `https://example.org/.well-known/openpgpkey/hu/iy9q119eutrkn8s1mk4r39qejnbu3n5q`.

Several services (like kernel.org) already have WKS support, for example Linus' key is at: https://kernel.org/.well-known/openpgpkey/hu/pf113mfnx1f3eb1yiwhsipa91xfc7o4x. Some third party services like posteo.de [support WKS too](https://posteo.de/.well-known/openpgpkey/). WKS is also [supported by Enigmail](https://www.gnupg.org/blog/20170803-web-key-in-enigmail.html).

More details here (in German): https://www.golem.de/news/web-key-service-openpgp-schluessel-ueber-https-verteilen-1609-123194.html

Support for WKD lookup was [merged recently in openpgpjs](https://github.com/openpgpjs/openpgpjs/pull/714).

Mailvelope could lookup keys using WKD in addition to searching the default server (`keys.mailvelope.com`).

If this feature sounds like a good fit for Mailvelope I could work on a PR.

**Comment by toberndo** [comment]
I saw the PR for OpenPGP.js, great stuff! We have planned to implement WKD as part of https://github.com/mailvelope/mailvelope/wiki/mw2018.
At the moment there is still a lot of refactoring going on in Mailvelope at the moment and I think for WKD support it makes sense to wait until August before starting to integrate it.

**Comment by wiktor-k** [comment]
Good idea, thanks for your message.

> At the moment there is still a lot of refactoring going on in Mailvelope at the moment ...

Is update to openpgpjs 3.x also planned? I've seen Mailvelope still use 2.x and I don't know if any API did change in the meantime...

By the way the roadmap looks really promising and ambitious, are there more details about it? For example this sparks my interest:
> Design and implement a secure way of exchanging pubkeys with Mailvelope.

**Comment by wiktor-k** [comment]
> This part of the roadmap is exactly what we want to achieve with WKD support.

Excellent!

Will Mailvelope be affected by CORS when accessing WKD keys?

For testing openpgpjs I had to add `Access-Control-Allow-Origin: *` header to all responses (200 and 404) on my host, but as far as I can see the WKD draft does not require it and most (all?) hosts on the internet do not emit them. Maybe it would be good to include CORS in the WKD draft? I'm just pointing out some issues I've encountered as you'll probably dig deeper into WKD when working on that milestone.

> Another new feature that is almost completed is encrypted forms 

Oh, I was just about to work on a contact form with OpenPGP-abilities, I'll look through your docs when they are released, it would be nice to utilize Mailvelope.

Also this one goal:

> Develop a JavaScript bridge to native GnuPG installation for use in Mailvelope.

would be very beneficial for me personally (as I've got keys on a smartcard and a "well groomed" keyring).

Thanks a lot for your time!

**Comment by toberndo** [comment]
> Will Mailvelope be affected by CORS when accessing WKD keys?
> 
> For testing openpgpjs I had to add Access-Control-Allow-Origin: * header to all responses (200 and
> 404) on my host, but as far as I can see the WKD draft does not require it and most (all?) hosts on
> the internet do not emit them. Maybe it would be good to include CORS in the WKD draft? I'm just
> pointing out some issues I've encountered as you'll probably dig deeper into WKD when working on
> that milestone.

That's a good point. I just checked that we have already the permission to do cross-origin requests: https://developer.chrome.com/extensions/xhr
So for Mailvelope this should work. For regular web pages, CORS header would be beneficial. (ping to @bernhardreiter).

> Oh, I was just about to work on a contact form with OpenPGP-abilities, I'll look through your docs
> when they are released, it would be nice to utilize Mailvelope.

I just sent you the link.

> would be very beneficial for me personally (as I've got keys on a smartcard and a "well groomed" 
> keyring).

Excellent :)

**Comment by azul** [comment]
My understanding is that now a basic implementation of key lookup via WKD has been included.
@toberndo Maybe this can be closed now?

**Comment by wiktor-k** [comment]
Yes, I've tested it another day and it worked flawlessly. Thank you all!
