### ISSUE TITLE
Again from Begin: Problems with container/overly - Documentation wrong

### ISSUE THREAD

**Issue by githubadminsarefotrols** [mailvelope/mailvelope#583]
Hi,

I got a special site, where in a common < table > inside < td >'s are encrypted messages as PGP-Block - mailvelope finds them und offers the overlay < div > for decryption, but not on top of the origninal block, they are positioned nearly top left corner of the page and overlay each other. This way you had to decrypt all and the assume wich is wich. How can I adjust positioning of the overlays? Is there a possibility? It seems like, that the x,y offsets are false calculated, but I cant understand why, its a static side..

Then is in the Documentation mentioned, that one can a "row" expand and see how this mailprovider is handled, wich frames, divs and so on are parsed. But I cant expand this row, is it a past feature or a future one?

"You can also manually add websites and their frame structures to the list. However, this process is not described here." Nice, where is it described? 

Thanks a lot

**Comment by toberndo** [comment]
This issue is now be worked on in #590. Closing.
