### ISSUE TITLE
Tor Browser Issues

### ISSUE THREAD

**Issue by githubadminsarefotrols** [mailvelope/mailvelope#584]
If you choose security level middle or high - the image, background-security image is not shown and mailvelope is unbelievable slow

mailvelope works only, if you for the specific site add an whitelist-entry in noscript for this site

**Comment by toberndo** [comment]
We do only support the official Chrome and Firefox builds and new releases are only tested against these two browsers. But we would accept pull requests to improve the situation for Mailvelope on Tor browser. But it will probably be hard to fix issues like bad performance and the need for a whitelist-entry in noscript only on Mailvelope side.
