### ISSUE TITLE
Password dialog design

### ISSUE THREAD

**Issue by githubadminsarefotrols** [mailvelope/mailvelope#585]
The dialog-windows to pass in the passphrase for the private key is HUUGEE, this could be way more little, that would look more professional. at the Moment it looks silly.

**Comment by toberndo** [comment]
The password dialog should include: user information (user id + email address), key id, security background, checkbox for password caching. I'm open to constructive design proposals. "Looks silly" does not help.

**Comment by githubadminsarefotzentrolle** [comment]
Ok, how should I say it other. It looks like "Wie gewollt und nicht gekonnt" - better? Does not look professional made, like the other gui elements.

For me, may be depends this on my tor-browser or other element, is 1/3 of height content, 2/3 are empty, that could be improoved, so I think its better to reopen. Its a serious suggestion, nothing personal.
