### ISSUE TITLE
text areas and input fields are not parsed/searched for PGP-BLOCK-Content

### ISSUE THREAD

**Issue by githubadminsarefotrols** [mailvelope/mailvelope#589]
Assume you have a Forum where You save your public key block, so that others can read it. Assume, that others this PGP-BLOCK is shown in an text-area or input field. mailvelope does not recognise this block, I suggest to parse this Elements too.

If you would give me advise, how to set settings what to parse what not, I would do it. The only thing you reacted today for me was beeing upset about the word "silly" but no comment bout my ideas..

Bummer!

**Comment by toberndo** [comment]
> Assume you have a Forum where You save your public key block, so that others can read it.

I assume this won't be displayed in the forum in an input or text area but more in a display-only area? Contenteditable fields from a Mailvelope perspective are fields where you want to paste the encrypted message. If we would scan here for public keys that would mean if you paste your public key in the email compose editor, then Mailvelope would detect it and create a frame around it, which would be rather strange.

**Comment by githubadminsarefotrols** [comment]
Yes, that would be silly.

But when page loads, and a area or field appears, that got a pgp-block in it, why not parse?

You could everytime klick X on the overlay, edit what is in the area, field..?

May be to think about the dynamic concept.. Does mailvelope scan for JS-added objects, text to? Or only on page load?

May be it would be better design, if anywhere on the page a PGP-Block appears, show an icon on top like in the input-field/textareas something like "check PGP", when it is a signature/key then ++ when it is a message -- decrypt, and so on. the automatic overlaying is not the best idea, sorry I have to say this.

toberno: What really makes me sorrow: You only answer to things that come in conquer to your ideas, but you do not answer questions, I wrote 4,5 other tickets, no comment. This is not trust awakening..

**Comment by toberndo** [comment]
Not desirable from a usability point of view.
