### ISSUE TITLE
Improve extract frame positioning

### ISSUE THREAD

**Issue by githubadminsarefotrols** [mailvelope/mailvelope#590]
I spent some nice hours this night frickling through the source code - big project. praise! Now I understand why You not so very very intense much strong look after smaller UI-Problems.

Unfortunally I didnt got the concept of the parsing - to complex for me. I tryed to understand the problem described in https://github.com/mailvelope/mailvelope/issues/583 - why the injected div with the iframe is shown on the top left of the page and not overly to the PGP blocks in the table. But sorry, I would need days to get through really, so I cant only ask you for help. If you give me advise here, I will help debug and test! Its important, we want to use mailvelope for a row of security dependend sites, so I will help as much as I can to fix this, that our users can as fast as possible use mailvelope.

One thought about the documentation, the entry about the wath list/mail providers:

"Advanced: When expanding a row in the watch list, we see the frames that will be scanned for encrypted emails and email composing areas. If we can identify irrelevant frames (e.g. from ads), we can disable the entry and minimize the scanning effort. " -> I searched and search if I could find a sign what could be meant by advanced, no chance. Please explain!

Also

" You can also manually add websites and their frame structures to the list. However, this process is not described here." -> Yes, Yes... But how? Is it documented anywhere?

grüße

**Comment by toberndo** [comment]
Sorry, we are heavy in development at the moment with other features. So sometimes it's hard to find the patience for new design proposals.
The issue with the wrong positioning in #583 is a difficult one, which probably requires some CSS wizardry. We would need a detailed description how to reproduce the issue, but also than the probability that I can work on this in the next weeks is low. If you find someone who can work on this I can give guidance where the positioning can be found in the coding.

> Advanced: When expanding a row in the watch list, we see the frames that will be scanned for
> encrypted emails and email composing areas. If we can identify irrelevant frames (e.g. from ads), we
> can disable the entry and minimize the scanning effort.

This part of the documentation is outdated, new version is in the making. The scanning process on the page, as it is today, does not include all frames (like ads), but only frames for the main domain of the page and its sub domains. So you won't find here any irrelevant frames that you can disable.

> You can also manually add websites and their frame structures to the list. However, this process is
> not described here." -> Yes, Yes... But how? Is it documented anywhere?

It should not be necessary to manually change settings here. If you need to then you can add new domain match patterns like *.demo.com (*. prefix required) and Mailvelope will then scan websites or sub frames for this domain pattern.

**Comment by githubadminsarefotrols** [comment]
> . If you find someone who can work on this I can give guidance where the positioning can be found in the coding.

Ok, I will do it. Give me the hints and we can go.

**Comment by toberndo** [comment]
Positioning is done with this CSS: https://github.com/mailvelope/mailvelope/blob/master/src/content-scripts/framestyles.css#L15
Size and position is adapted here dynamically: https://github.com/mailvelope/mailvelope/blob/master/src/content-scripts/extractFrame.js#L114
Called on resize event and also in an interval every second:
https://github.com/mailvelope/mailvelope/blob/master/src/content-scripts/extractFrame.js#L82

**Comment by githubadminsarefotrols** [comment]
OK, thanks. I will go a night over it.

Could You please in my other tickets do similary comments, especially what is really deathlock the https://github.com/mailvelope/mailvelope/issues/586 - And: If I post patches, will you add it to the codebase and do a new release? I would it see better when our community gots the extension from browsers intern addon management.

**Comment by toberndo** [comment]
> Could You please in my other tickets do similary comments, especially what is really deathlock
> the #586

#586 is a feature request that requires some effort. Maybe you can first deliver a solution for this issue, and then we can continue with the next task. 

> And: If I post patches, will you add it to the codebase and do a new release? I would it see better
> when our community gots the extension from browsers intern addon management.

The patch needs to pass a code review. As this is a critical area, you need to make sure that your patch does not only solve your issue, but does not affect the positioning in major webmail clients (Gmail, Outlook.com, Yahoo, one Roundcube installation, and possibly other non-API using clients in our watchlist: https://github.com/mailvelope/mailvelope/blob/master/src/res/defaults.json#L3). If this is all completed, then we include it with next release.

**Comment by githubadminsarefotrols** [comment]
Ok, this resolution was relative easy.

First I thought, the e-frame div is positioned absolute (Iam/was not shure, if all parent objects are non-positioned, then this will be positioned from body/html), but I checked the dom-tree and saw, that style-->position of the e-frame div is unset. I wondered why the offsetParent linked to body, and not to the td element the e-frame div is injected in. So I searched a little about offsetParent:

---
HTMLElement.offsetParent
JavaScript

The HTMLElement.offsetParent read-only property returns a reference to the object which is the closest (nearest in the containment hierarchy) positioned containing element. **If the element is non-positioned**, the nearest table cell or root element (html in standards compliant mode; **body in quirks rendering mode**) is the offsetParent. offsetParent returns null when the element has style.display set to "none". The offsetParent is useful because offsetTop and offsetLeft are relative to its padding edge.

parentObj = element.offsetParent;
---

I changed the HTML of the eframe live in the webtools:

`<div id="eFrame-blabla" class="m-extract-frame m-large m-decrypt m-cursor" style="position: relative; width: 561.167px; height: 2314.6px; top: 8.40002px; left: 30.8px; display: block;"><a class="m-frame-close">×</a></div>`

and promptly the e-frame div was on the correct position, perfect. So it seems, that our site kicks the browser to quirksmode, and position:relative brings the e-frame to the wished position. What seems a little undocumented: if top,left style-attributes are set, position is unset and all other ancestors position is unset, then top/left is interpreted like absolute but relative from body.. Interesting: position:absolute again brings the e-frame div in absolute position in relation to body, and not the td.. 

**The solution is also, that the style-property of the e-frame div must explicitly set to "position:relative" - what I think that is what You want.** 

Please forgive me, that I not will do a patch, I think You know in 5 seconds where the exact line of code is to change. 

----

And Thomas, I disagree about #586 - this is a bug. a . means for me (in regex mind) ALL and not ALL WITH EMAIL. I cannot really understand why this needs efford, but again You could give me advice where to start in the source-code. It wonders me, that nobody has issued this before, there are many people who creat keys without address.

Tschiers

**Comment by toberndo** [comment]
> Positioning of the injected e-frame-div should be done on style position:absolute in the class definitions, and the top,left values are given direct in the html.
> 
> Position determining of the original PGP-Text is done by finding the parent of the PGP-Block-Text, and getting its position values due jscript-added function .position() - Right? This means, this values are from the offsetParent of this PGP-Text-Parent. In theory it must all went good, because top,left come from the offset to the offsetParent, and when position absolute is used for the e-frame, then in theory should it lay z-index higher on top of the PGP-Block.

That's also my understanding.

> One one page we have the problem, that the PGP-Block lays inside a td-element, top,left are returned by .position() something like 10,15 - The problem here is, that td, table Elements do not have position:absolut|relative set, but do have an offsetparent from wich the offset is derived , when positioning a div inside a td with position absolute, then this div will be positioned relative to body.

Is there a way to get the offset of the td element relative to the body? So we can say if PGP-Block is inside a td then: eframe.top = (td to body).offset + td.position().top.

> One problem also I see: If the PGP-Block is inside an Element with overflow:auto, this element in that the injected e-frame-div is becomes scrollbars when the iframe is injected. When you scroll then, the recalc of the positioning is awaked... deadlock.. That must be shut off with explicit overflow:hidden in the class-definition of the e-frame-div! I added overflow:hidden directly in the class, unfortunally the magic with infading the iframe does not work anymore. I see problems over problems.

Not sure why the fade in is related to the overflow attribute.

> Both problems come from the same design-problem: Why inject the divs not generally onto the body-element, with z-index 100 and calculate the position of the PGP-Text-Parent in relation to body, I analysed that not till now, may be jquery has got such an function inbuild - has jQuery.offset(). Injecting a div into a td is a problem, also a div cannot go into a span, I do no know exactly, but I remember that the HTML standard defines in what kind of element a div may be and may not. Without checking this, injecting the div is a design failure. Also this divs inherits all kind of css properties from ancestors, like scroll bars.

The current design worked so far pretty good. Be prepared for some extensive testing if you change the mechanism that fundamentally. Intuitively it feels for me more correct to put the div inline where it belongs logically, versus adding it to the body. Inheriting properties from ancestors I would see as a feature, not a bug. But I might be wrong and for this use case adding the divs to the body is the better approach.

What happens if we use another element instead of div for the eframe?

**Comment by githubadminsarefotrols** [comment]
> Is there a way to get the offset of the td element relative to the body? So we can say if PGP-Block is inside a td then: eframe.top = (td to body).offset + td.position().top.

Its much more complicated, because you use jquery - jquery != DOM != Implementation of W3C != Buggy Browser behavior...

> Not sure why the fade in is related to the overflow attribute.

Iam not, too. But I will find out.

>  Intuitively it feels for me more correct to put the div inline where it belongs logically, versus adding it to the body.

Yes, this accordes to the fact, or the rumor, that Mailproviders wich use the api can get the private key stored in mailvelope, (decryption key belongs to them) I checked the sourcecode not so to the extend as far, but I see the problem:

Phillosophical view: There is a site representated, in which a encrypted text is shown. May be this encrypted text is for you, the mailvelope-user. The purpose is, that the text is encrypted on this site, not unencrypted, your goal seems to be, for the user transparent, decrypt this text inside the site, als ob nichts wäre.. Thomas, also bitte.

This is nice and anyhow a thinking of gui-friendliness, but not the structural way of thinking in a security aware, anonymous, privacy way!

If I had written this software, I only would add a parser to the site, recognise PGP-Blocks, and add an icon or two on top, left, right, (like in your text-areas) with the function: Analyze block,, or Decrypt Block, Add Puplic Key, .. something like this, and would open a new popup/window/tab to explicitly seperate encrypted and unencrypted contend. I only will mention the fact, that **decrypted text is locally stored (on hard drive)** for the src of the injected iframe - this is a serious security bug - may be this file will be deleted, or overwritten, but on unencrypted file systems this file will be restoreable, this is also a definitily design failure, decrypted text has to be stored in RAM and then overwritten, deleted after viewing,, the possibility to restore this decrypted text is to high! Why do you not note this? Because you are busy implementing features you get paid for, I could also add some critics: Where is the community around this project? I mean, this is the only one stable, actual, cared firefox-plugin that can decrypt PGP-Blocks showed in websites - why are there not 20 of specialists who support you in questions abaout context-dividing, security aspects, and so on? Can you explain me that? You need only to post a help request to the openbsd, openssl, gpg, gnu, debian community - Please, help me with code review in concerns of security, anonymity,,... dozens of other security freaks, and you would get help over help...! Thomas, who holds you busy with implementing senseless features?

Ok, so far with my sorrows.

Basicly I would say: Encrypted and Decrypted content must be separated. One basic implementation is, to seperate it from the place encrypted text is shown. So I would recommend to add all injected objects to the most upper node in the DOM of the side, the body, position it z-index absolute over the encrypted target. I see only one problem, when the layer the encrypted block is inside is in a context, that is scrollable -- for this problem I have no idea at the moment -- as far as I understood, there comes so many problems because of inheriting css-properties. (you inherit all css bugs also, did you thought about that? for example background-features, bugs in interpreting binary image data,,, and so on)  I dont know. Its your thing, If you really want to give the user the feeling, that transparent decryption occours,, ok (But Thomas, please think about this ideologycally basics one round again - we talk about STRONG encryption and PRIVACY. No one in this world expect that any add-on intergrates into "google - the master of data grabbing" transparently - not only one human in this world, that concerns really about security and anonymity can ernst nehmen was Du da programmierst ( As I said. I would only may be highlighting the PGP-Block and add a little toolbar beside it like |View PGP-Identity/Analyce|Decrypt PGP-Block| and if the user chooses one of the options, a new popup, tab, window is opened - password-phrase is asked (without default checked "store password temporarily")). Also I would for PGP-Identities first show a information page, this is Mr. Edwards S. Public Key... and then a Button like Cancel, Add to store... also a design failure, every identity you click on is automatically stored in the key store... tracing your trails... wonderful Thomas. 

And so on. From the basic princible, I would say, the one who uses encryption, depends on privacy and trust, understands - expects already - that between encrypted view and decrpted view must be a step, a difference ... it is absolute nonsense, dangerous, in-need-of-umsatz-machen-thought to integrate a decryption feature into the context of a mailprovieder the user can NOT trust! So. who are you Thomas?

My suggestion is, take at new baseline: Encrypted content and decrpted contend is seperated, decrypted content is secured as much as possible, every step that leads to decryption must be secured and hardened at most it can be. -> Then will mailvelope (and then you can name it decrypt PGP on WEB, not only MAIL) be a new standard. At the moment it is a redicolous security bug.

To solve the problem with the positioning inside table cells, one patch is added here.

---

We have the problem, that jquery play its own game, where offsetParent in the DOM is pointed to `<td>` offsetParent() points to `HTML` - but position() in jquery reflects offset in relation to the `<td>` ,,, jquery is a bug of its own.. and so on. I rely on jquery with my patch, so lets hope.

.. to be edited again

**Comment by toberndo** [comment]
I mean it's not that I find your posts not entertaining, but it is always quite some effort to filter out the relevant part for the current task (positioning of divs in tds) and the other content which is more like the world according to githubadminsarefotrols.

> Its much more complicated, because you use jquery - jquery != DOM != Implementation of W3C != Buggy Browser behavior...

I'm open to ditch jquery here and directly use the DOM. Browser compatibility is not so much an issue for us because we only need to support evergreen Firefox and Chrome.

> Yes, this accordes to the fact, or the rumor, that Mailproviders wich use the api can get the private key stored in mailvelope, (decryption key belongs to them) I checked the sourcecode not so to the extend as far, but I see the problem:
> 
> Phillosophical view: There is a site representated, in which a encrypted text is shown. May be this encrypted text is for you, the mailvelope-user. The purpose is, that the text is encrypted on this site, not unencrypted, your goal seems to be, for the user transparent, decrypt this text inside the site, als ob nichts wäre.. Thomas, also bitte.
> 
> This is nice and anyhow a thinking of gui-friendliness, but not the structural way of thinking in a security aware, anonymous, privacy way!

Sure, as if there were no usability issues in PGP land. We simply need to work on improving the security of Mailvelope by 1% (and decreasing usability by 10%) and suddenly everybody will encrypt their email.

> If I had written this software, I only would add a parser to the site, recognise PGP-Blocks, and add an icon or two on top, left, right, (like in your text-areas) with the function: Analyze block,, or Decrypt Block, Add Puplic Key, .. something like this, and would open a new popup/window/tab to explicitly seperate encrypted and unencrypted contend.

You realize that this will decrease usability? Extra clicks and extra popups.

> I only will mention the fact, that decrypted text is locally stored (on hard drive) for the src of the injected iframe - this is a serious security bug - may be this file will be deleted, or overwritten, but on unencrypted file systems this file will be restoreable, this is also a definitily design failure, decrypted text has to be stored in RAM and then overwritten, deleted after viewing,, the possibility to restore this decrypted text is to high! Why do you not note this? 

Here you have my attention. Can you share more details?

> Because you are busy implementing features you get paid for

Sure, little site kick because someone is earning money with open source. Always appreciated.

> I could also add some critics:

What means "also"? Most of your post is critics, right?

> Where is the community around this project?

Could indeed be larger.

> openssl

That was a good one. LOL

> Thomas, who holds you busy with implementing senseless features?

Getting obscure now. You think there is a grand plan in all the things?

> Encrypted and Decrypted content must be separated. One basic implementation is, to seperate it from the place encrypted text is shown. So I would recommend to add all injected objects to the most upper node in the DOM of the side, the body, position it z-index absolute over the encrypted target.

How is the separation related to where you add the eframe in the DOM? That's not relevant.

> not only one human in this world, that concerns really about security and anonymity can ernst nehmen was Du da programmierst

I'm only reading that now. My mood turns to: shouldn't have answered at all to this trolling.
Ok, didn't read further. "Gelbe Karte". Stay on topic. Less talking, more coding.

**Comment by toberndo** [comment]
Having looked again at this pamphlet, actually that's a bit too much horse shit for any meaningful future discussion. Blocking user githubadminsarefotrols.
