### ISSUE TITLE
Disable loading of remote content

### ISSUE THREAD

**Issue by emkll** [mailvelope/mailvelope#594]
Originally brought up by @mdik in [issue 578](https://github.com/mailvelope/mailvelope/issues/578#issuecomment-389037893), it would be nice to disable loading of external content to prevent leaking metadata (e.g., IP address) to a third party.

It seems that for Chrome, adding a domain whitelist to the [manifest](https://github.com/mailvelope/mailvelope/blob/master/src/chrome/manifest.json#L30) can be possible
or perhaps set the URL permissions as optional to allow users to decide at runtime.

**Comment by toberndo** [comment]
This is implemented in this branch: https://github.com/mailvelope/mailvelope/tree/block_html
Works well with CSP.

**Comment by toberndo** [comment]
Release in v3.0.0
