### ISSUE TITLE
Unable to Update Expiration Date

### ISSUE THREAD

**Issue by PrinceSerna** [mailvelope/mailvelope#597]
![screen shot 2018-07-11 at 6 46 06 pm](https://user-images.githubusercontent.com/17882637/42603194-cf7d7e8a-853a-11e8-9562-3c0d1711bb72.png)

Unable to update Expiration Date on Secret Key Pair from Key Details. Or unable to find this feature that exist in other Key Ring Managers. 

By default I set users to about 2 year window to allow for key to expire on its own if lost, password is forgetten, or revocation cert is lost / not created. 

Seems similar to: https://github.com/mailvelope/mailvelope/issues/411
OS: Windows10 or macOS 10.13
Browser: Chrome v. 67
Mailvelope: 2.2.2

**Comment by toberndo** [comment]
Please check out latest release v3.1.0. Change of expiration date is now supported in key details.
