### ISSUE TITLE
Support for non-latin characters

### ISSUE THREAD

**Issue by toberndo** [mailvelope/mailvelope#6]
If a mail contains non-latin characters, Mailvelope will generate an invalid encrypted message which fails to decrypt.
This is due to the following issue in OpenPGP.js:
https://github.com/openpgpjs/openpgpjs/issues/51

**Comment by SaschaZorn** [comment]
Are you sure that UTF-8 decoding is working properly in v0.12.0

For me it looks like the attached screenshot:

Characters in questions are "German Umlauts" like ä,ö,ü,ß. Mail is from do.de, sent to posteo.de and was encrypted on retrieval by posteo.de server, shipped as:

Content-Type: multipart/encrypted; boundary=9bf2c0a735e6f735dd1d96fb8de0ad7ad1d41b485f0fd63e6b3b6627f3bc; protocol="application/pgp-encrypted"

![mailvelope](https://cloud.githubusercontent.com/assets/2486615/6220181/6d421c78-b633-11e4-8e49-45a6d3b59b3f.png)

**Comment by mars3142** [comment]
I also have this issue with German Umlauts.

**Comment by toberndo** [comment]
Could reproduce with transfer encoding: 8bit
`Content-Transfer-Encoding: quoted-printable` works fine.

**Comment by toberndo** [comment]
Fixed with https://github.com/mailvelope/mailvelope/commit/b72aa6421ff2a772086bf758201f93beecde237e

**Comment by rugk** [comment]
If it is (verified) fixed, you can close this issue.
