### ISSUE TITLE
Encryption of attachments 

### ISSUE THREAD

**Issue by anonranger** [mailvelope/mailvelope#61]
Encryption of attachments 

Is this feature in the pipeline?

**Comment by amir-r** [comment]
+1

**Comment by bennettaur** [comment]
+1

**Comment by v6** [comment]
// , :+1: 

Also, I think that we ought do more than blithely suggest that the maintainers add and maintain yet another feature for us, for free. 

I will at least put some of my money where my mouth is, and would donate .05 BTC for this feature if others donated 5 BTC to complete this feature. I would donate .1 BTC for this feature if others donated about 10 BTC to complete this feature.

**Comment by rugk** [comment]
BTW at least for mail providers which use the [Mailvelope API](https://mailvelope.github.io/mailvelope/) you can encrypt attachments. And possibly this is the only way to implement it as you cannot send attachments "inline" - hence you cannot use inline PGP.
You can test it with the [mailvelope demo](https://demo.mailvelope.com/manual).

**Comment by wxl** [comment]
@rugk which clients actually use the API?

**Comment by rugk** [comment]
You can see the big ones [here](https://www.mailvelope.com/coop), but I also know that [Posteo.de uses the API](https://posteo.de/en/blog/new-posteo-webmail-interface-can-find-public-keys).

**Comment by v6** [comment]
// , @rugk, could I invite us all to a github gist post against which we could all make pull requests to post clients known to implement the API or allow Mailvelope attachments?

**Comment by rugk** [comment]
@v6
Okay, finally created it: [E-mail providers using the Mailvelope API ](https://gist.github.com/rugk/15ed0296a5e1ab7a204d)

I also found a few more providers and I also added a few more features there, so you can see which provider provides what features.
If you want to test a provider and can fill the `N/A` gabs Pull Requests are more than welcome.

**Comment by CyberKiller40** [comment]
I'd love to see some way to use encrypted attachments in gmail

**Comment by v6** [comment]
// , It looks like that depends more on GMail, now. 

I think we can consider this issue closed.

**Comment by rugk** [comment]
I finally moved the list from the Gist to this wiki: https://github.com/mailvelope/mailvelope/wiki/E-mail-providers-which-are-using-the-Mailvelope-API

And it happened I saw that there [is already a similar page](https://github.com/mailvelope/mailvelope/wiki/Supported-email-services). However it is not that detailed as my tables.
So what about merging these two ones? @toberndo 

I am especially surprised to see a new provider there: zoho.com
Can someone please test zoho.com and add it to the wiki page if it really uses the API?

**Comment by toberndo** [comment]
@rugk Thanks for creating this overview. Mailvelope wiki is the right place for it. The old "Supported-email-services" can then be deleted. I will update the N/A gabs shortly. zoho.com does not use the API.

**Comment by rugk** [comment]
Thanks for the information. Good to hear this...

**Comment by toberndo** [comment]
Attachments are already supported via the Mailvelope API for some time.
And we have now the file encryption feature to manually encrypt files: https://www.mailvelope.com/en/help#files
