### ISSUE TITLE
Password, Editor, Composer-Window are blank when opened in Firefox 60

### ISSUE THREAD

**Issue by aspiargue** [mailvelope/mailvelope#619]
Hello Thomas,

in the actual torborwser (Firefox 60.3....) are the freshly opened windows for password, editor, composer blank. If you resize the window a little, content is shown. Can you please give code hints where to start with debugging, then I will code a little.

Thanks, aspi

**Comment by bernhardreiter** [comment]
Hi @aspiargue,
if it works in the regular Firefox, it will be an effect that has to do with the changes that Torbrowser has compared to the original Firefox. A typical debugging step would be to look at these changes, get an idea which one causes the problematic behaviour. You could also remove half of the changes and then another half of those that introduce the problem to identify the change that causes the issue.

Best Regards,
Bernhard

**Comment by toberndo** [comment]
On Linux this is a known issue and fixed with Firefox 63 (https://github.com/mailvelope/mailvelope/issues/558). Tor Browser seems to be based on the ESR release, so with this release cycle they won't get a fix until the 68 ESR release, somewhen mid 2019.
