### ISSUE TITLE
What's up with v3.0.0?

### ISSUE THREAD

**Issue by rugk** [mailvelope/mailvelope#627]
There is no changelog, there is no blog post, there is no tweet, there is no [version information on AMO](https://addons.mozilla.org/firefox/addon/mailvelope/versions/), and there is not even [a GitHub release](https://github.com/mailvelope/mailvelope/releases)…?

However, there is [a commit](https://github.com/mailvelope/mailvelope/commit/8ec9ddeac29e725c4212da84eca14db339a8220e) **several days ago** that mentions this is the v3.0.0 release…

Also the Firefox update does request the new "nativeMessaging" permission? 
So I really wonder what's up…?
Especially as this seems to be released/finished since 13 days I wonder why there is no announcement whatsoever… Especially as it requires a new permission… :thinking:

**Comment by rugk** [comment]
The new permission seems to be [related to the inclusion of gpgme](https://github.com/mailvelope/mailvelope/commit/afa861c42c38a1510dc949a27992c2cd1376da30) as a new [lib for interacting with native gpg](https://github.com/mailvelope/gpgmejs). I just wonder why? Does Mailvelope no longer want to use OpenPGP.js?

**Comment by sbriskin** [comment]
As i can see there is a news about 3.0 release https://www.mailvelope.com/en/blog/mailvelope-3.0
The user now has the choice whether they want to have the key management and encryption routines done by OpenPGP.js or by the locally installed GnuPG application.
That is great news for me because i don't need to import such a lot of key into mailvelope that i used for my corporate webmail.

**Comment by rugk** [comment]
Likely published after I've asked here…

**Comment by bernhardreiter** [comment]
@rugk the release has been long in the making, including the blog post. Post and release came yesterday together.

A quick release is good for get benefits of the new release to people who can already use it. More documentation is forthcoming as mentioned in the blog entry.  There is also:
https://github.com/mailvelope/mailvelope/releases/tag/v3.0.0

**Comment by rugk** [comment]
Yeah, it seems to be all filled now. :smile:
