### ISSUE TITLE
Support fetching keys from autocrypt headers

### ISSUE THREAD

**Issue by azul** [mailvelope/mailvelope#630]
First step towards #535.

Inside the [Mailvelope Client](https://github.com/posteo/mailvelope_client) extension for rouncube...
- [x] we will need a [hook](https://github.com/roundcube/roundcubemail/wiki/Plugin-Hooks#message_load) or [two](https://github.com/roundcube/roundcubemail/wiki/Plugin-Hooks#message_headers_output) that adds a hidden element with the autocrypt header to the page content. 
- [x] We also need access to the messages `Date` header. Not sure if that is in the page already anyway.
- [x] In the [init call](https://github.com/posteo/mailvelope_client/blob/7a8da40a5d925c9c266ea5b86727fba6a9645392/mailvelope_client.js#L738) we need to detect these elements and call a [callback](https://github.com/azul/mailvelope/blob/import-autocrypt-js/src/client-API/mailvelope-client-api.js#L286) in [the Mailvelope API](https://github.com/mailvelope/mailvelope/blob/master/src/client-API/mailvelope-client-api.js#L32) 

In Mailvelope itself...
- [x] Have that callback hand the header data to the [autocrypt storage](https://github.com/azul/mailvelope/blob/fee81fba660ed6b3c18b586e2fc2bfbd45be3996/src/modules/autocryptWrapper.js#L29)
- [x] Once the headers are being parsed we can [add another strategy](https://github.com/azul/mailvelope/blob/fee81fba660ed6b3c18b586e2fc2bfbd45be3996/src/modules/autocryptWrapper.js#L17) for [looking up keys](https://github.com/azul/mailvelope/blob/fee81fba660ed6b3c18b586e2fc2bfbd45be3996/src/modules/autocryptWrapper.js#L17) during compose time.
- [x] We will probably also want a configuration flag for using keys from AC headers.
- [x] replace the dummy storage with an actual storage
- [x] pick the storage based on the current identity

**Comment by azul** [comment]
So now we are storing autocrypt keys we retrieve from headers just fine.
We need to make them actually usable in the API. So far I have been focussing on using them in UI elements such as the editor.

So in Mailvelope we are missing:
- [ ] returning an object rather than the plain key
- [ ] wrapping AC keys in armor

The client extension will need to:
- [ ] call locatePublicKeys and check the result
- [ ] Propose to import these keys when found.

**Comment by azul** [comment]
This has been implemented in the last release. It needs provider support though in order to allow Mailvelope to read the headers in the first place.

**Comment by monperrus** [comment]
FTR, related issue [enable by default "Use keys from Autocrypt headers of incoming email"](https://github.com/mailvelope/mailvelope/issues/816)

**Comment by monperrus** [comment]
> It needs provider support though in order to allow Mailvelope to read the headers in the first place.

@azul This does not work out of the box for gmail.

Does Gmail's provider support collecting keys from autocrypt?

Thanks!
