### ISSUE TITLE
Change password of a private key

### ISSUE THREAD

**Issue by tigerhawkvok** [mailvelope/mailvelope#64]
If a key is created elsewhere, and an unencrypted copy is then saved into Mailvelope, the system should prompt to encrypt the private key, or allow after-the-fact encryption of the key.

**Comment by zixia** [comment]
i need this feature too.

it should be like the way that ssh-keygen works: 
```bash
ssh-keygen -p
Enter file in which the key is (/home/user/.ssh/id_rsa): 
Enter old passphrase: 
Enter new passphrase: 
```

**Comment by jochenonline** [comment]
+1

**Comment by nexxai** [comment]
+1

**Comment by fcastilloec** [comment]
+1

**Comment by gregcope** [comment]
+1

**Comment by HalliHalloSchatz** [comment]
+1

I have updates / change my passphrase by 3rd Party Tool on my Android Phone (OpenKeychain).
After reimport the new set of private/public key the password is the same old one.
I get the message, keyset are updated.

Only delete the existing key from the storage and reimport the new key-set make the new password working.

**Comment by toberndo** [comment]
Changing of private key passwords is now available in https://github.com/mailvelope/mailvelope/releases/tag/v3.1.0

**Comment by huan** [comment]
Awesome, thanks for enhancing this feature.
