### ISSUE TITLE
Mailvelope GnuPG integration does not work when API permission is on (private key not found).

### ISSUE THREAD

**Issue by soerenkornetzki** [mailvelope/mailvelope#640]
When I open up my Roundcube Webmail 1.4, Mailvelope's GnuPG integration will refuse to find any keys with the GnuPG key store. It seems only to have access to the newly created "site key store". However, my OpenPGP key is only on my YubiKey, so I need the GnuPG key store to be used.

The issue above only exists, when I turn on the "API" setting for that site with the "authorized domains" configuration section. When I turn it off, Mailvelope's GnuPG integration will work, despite not very well integrated.

**Comment by toberndo** [comment]
I could reproduce a "No private key found to sign this message." error when encrypting a message, which is a bug we need to work on. Is this also the issue that you describe, or do you get the error when decrypting a message?

**Comment by Bodup** [comment]
Yeah it seems like websites that use the API get their own keying. 
I would like to use the GnuPG keyring regardless of the website I'm using (without disabling API support). 
That way I could just use my Yubikey for things like posteo

**Comment by toberndo** [comment]
@Bodup If you go to the OpenPGP Preferences and set GnuPG as the preferred backend and have your private key in GnuPG then message decryption will always done in GnuPG. It's a fallback mechanism: we first check if a private key is available in the preferred backend, otherwise Mailvelope uses other available keyrings.

**Comment by toberndo** [comment]
The "No private key found to sign this message." error should be resolved in `v3.1.0` as we check now in all available keyrings for signing keys.
