### ISSUE TITLE
SOLVED: [BUG] Mailvelope fails to load/work in new Gmail (G Suite)

### ISSUE THREAD

**Issue by rafaelwv** [mailvelope/mailvelope#649]
Mailvelope doesn't work anymore on new Gmail.

Reproduction steps:
1. Clean install of Mailvelope
2. Import keys and finish setup
3. Check if domainpattern for Gmail is allowed.
4. Reload new Gmail (G Suite) https://mail.google.com/mail/u/0/#inbox
5. Compose new message. (https://mail.google.com/mail/u/0/#inbox?compose=new)
6. Mailvelope doesn't show up in compose window.
7. Console doesn't show any Mailvelope related errors.

Issue is also reproducible in the (to be deprecated) Inbox by Gmail.

[mail.google.com-1547045254707.log](https://github.com/mailvelope/mailvelope/files/2741321/mail.google.com-1547045254707.log)

PD: Mailvelope also doesn't detect encrypted messages anymore, attaching screenshot.
![screenshot 2019-01-09 at 15 58 44 - display 2](https://user-images.githubusercontent.com/46530865/50907408-98b83580-1427-11e9-82f7-64e852d9dcfd.png)

**Comment by rafaelwv** [comment]
![image](https://user-images.githubusercontent.com/46530865/50906839-4296c280-1426-11e9-8725-409f6cc57a03.png)

**Comment by toberndo** [comment]
@rafaelwv This looks like Chrome OS?

**Comment by rafaelwv** [comment]
> @rafaelwv This looks like Chrome OS?

Correct. Chrome Version 71.0.3578.94 (Official Build) (64-bit)

**Comment by rafaelwv** [comment]
Solved after factory reset. Seems to be an oddity of ChromeOS.
