### ISSUE TITLE
Keys being changed when importing?

### ISSUE THREAD

**Issue by qazip** [mailvelope/mailvelope#664]
I generated my priv/pub key pair on linux via terminal. I

I then exported the keys to .asc and subsequently imported the same pair to mailvelope on firefox (via priv/pub file). Now, the keys in mailvelope are not the same keys I have, as in, they are not the ones I imported. I suppose they should be the same, right? I "cat" the keys that I exported to ASC and they are clearly not the same as the ones in mailvelope. What is going on?

**Comment by bernhardreiter** [comment]
How do you see that the keys are different?

Background: Keys can be saved in different formats or variants with more or less information, so that in the end the encoded `.asc` file is different, but the key material itself is the same.
