### ISSUE TITLE
Gmail Smart Reply reading emails?

### ISSUE THREAD

**Issue by keystrike** [mailvelope/mailvelope#674]
I recently decrypted an email and I noticed three Google Smart Reply response options popped up which seemed to be related to the email text. Is the decryption window being accessed improperly?

**Comment by toberndo** [comment]
I couldn't reproduce a case where the Smart Reply actually pops up after decryption. They were always displayed once I opened the email to display the decrypted message.

Anyway, Gmail would need to fundamentally break the security policy of the browser to get access to the decrypted content. Nothing suggests that we see here anything outside of the boundaries of a normal web application.

**Comment by keystrike** [comment]
The subject line was "test" and one of the Smart Reply options was "It works." (and the others were similar IIRC) so I think Gmail must have been responding based on the subject then rather than the body of the email.
