### ISSUE TITLE
Firefox addon appears corrupt error

### ISSUE THREAD

**Issue by johna777** [mailvelope/mailvelope#681]
Using Firefox browser and clicking on the Firefox addon link on https://www.mailvelope.com/en gives an error saying "The addon downloaded from this site could not be installed because it appears to be corrupt." Firefox 66.0.3, 64bit. Win10

**Comment by toberndo** [comment]
Mozilla has fixed this issue with Firefox 66.0.4: https://blog.mozilla.org/addons/2019/05/04/update-regarding-add-ons-in-firefox/
