### ISSUE TITLE
Feature Request: Add keys.openpgp.org to keyserver options

### ISSUE THREAD

**Issue by SoftwUser** [mailvelope/mailvelope#689]
Reference (German only):
https://www.heise.de/security/meldung/Neuer-OpenPGP-Keyserver-liefert-endlich-verifizierte-Schluessel-4450814.html
https://www.heise.de/security/artikel/PGP-Der-langsame-Tod-des-Web-of-Trust-4467052.html

**Comment by SoftwUser** [comment]
Additional motivation, maybe
https://keys.openpgp.org/about/news#2019-09-12-three-months-later

**Comment by YarmoM** [comment]
Any updates?

**Comment by CumpsD** [comment]
My keys are on openpgp too :)

**Comment by dsiggi** [comment]
Please add this domain. I have my keys there too.

**Comment by devhell** [comment]
Yup, it would be good to include this domain.

**Comment by SoftwUser** [comment]
What do you think, @toberndo ?
What prevens you from implementing this? Just curious...

**Comment by toberndo** [comment]
https://github.com/mailvelope/mailvelope/pull/740 adds keys.openpgp.org to the list of key servers, but this list is only relevant for the key search here:
<img width="366" alt="Bildschirmfoto 2021-09-03 um 15 52 01" src="https://user-images.githubusercontent.com/1164474/132016640-ca5efcf5-e7fe-49e1-9497-a83d69ebdc74.png">
Yes, you should have keys.openpgp.org available here as an option, but what would be more interesting is to use keys.openpgp.org in the same way as keys.mailvelope.com as a source of verified keys: we do automatic key import from these sources when you enter a recipient email address in the Mailvelope editor or also when you open an encrypted message with unknown signature. Here we would need to enhance our key registry: https://github.com/mailvelope/mailvelope/blob/master/src/modules/keyRegistry.js

**Comment by SoftwUser** [comment]
Unfortunately I have no programming skills myself. I am just a happy user.

Is anyone able to somehow drive this topic foward?

**Comment by dawid-woitaschek** [comment]
No one? :(

**Comment by toberndo** [comment]
We have this already in the development branch, will be part of the next release end of Feb.
