### ISSUE TITLE
New install doesn't work with GnuPG only

### ISSUE THREAD

**Issue by demonbane** [mailvelope/mailvelope#695]
I was able to get Mailvelope working with GnuPG following the workaround in #638, but I noticed that Mailvelope doesn't think it's been set up until after you at least import a key locally. Once that's done, you can go to key management and switch between the built in keychain and the GnuPG keychain, but going from a clean install to only using GnuPG doesn't work at all. I keep being prompted to "Get started".

**Comment by toberndo** [comment]
In release v4.1.1 you can now switch between keyrings when the keyring setup view is displayed, which helps to prevent such deadlock situations. The "Get started" button in the menu is only shown when there is no private key available in any of the keyrings. When GnuPG is the only keyring in use and has a private key, you should not see the "Get started" button. Once you navigate to the keyrings view, Mailvelope will first show the main keyring (which might be empty and therefore the setup view is diplayed). But in v4.1.1 you can now always switch to the GnuPG keyring as the keyring selection is available.
