### ISSUE TITLE
Allow resizing editor's textarea

### ISSUE THREAD

**Issue by vphantom** [mailvelope/mailvelope#696]
In previous versions of Mailvelope, I could drag the bottom-right corner of the popup editor's `<textarea>` to resize it to a comfortable height. In the current version however, a lot of CSS seems to have been added specifically to prevent that, and the forced height of 5 lines is way too small for editing messages.

I tried playing with the CSS a bit, and the best work-around I found was to first expand the height of the editor window manually, then add a `height: 500px !important` to the `<div>` immediately around the `<iframe>` to work around its `.h-100` class without disturbing other instances.

**Comment by toberndo** [comment]
Can you send a screenshot of the editor you mean? Because normally the height of the textarea is set to 12 rows and by default should look like this:
![image](https://user-images.githubusercontent.com/1164474/62867180-f80a5b00-bd12-11e9-9864-7ea0ca7e8d61.png)
In any case you can resize the editor popup window, which will also resize the textarea.

**Comment by vphantom** [comment]
Hi Thomas. :smile: Weird, that's not at all what 3.2.0 looks like for me on Chrome 71.0.3578.98 (Official Build) (64-bit):

![mailvelope_tiny_textarea](https://user-images.githubusercontent.com/3063161/62872137-d1d0c500-bcea-11e9-9ac3-b8772b0bdd51.png)

Making that window taller does not influence the height of the textarea.

**Comment by toberndo** [comment]
Is there a reason not to upgrated to 4.1? That would solve the issue.

**Comment by vphantom** [comment]
Oh! Odd, I thought Chrome extensions auto-updated. I went to the extension's page in Chrome and there was indeed an "Update" button, which I clicked, and I now have 4.1.0.

However, I still cannot expand the `<textarea>` regardless of window height:
![mailvelope_4 1 0_textarea](https://user-images.githubusercontent.com/3063161/63513219-9afd6a80-c4b3-11e9-851e-123c9be23697.png)

**Comment by toberndo** [comment]
We are not able to reproduce this. Can you also update Chrome to latest? Maybe clear the browser cache?

**Comment by vphantom** [comment]
Hi! I tend to postpone Chrome upgrades until something absolutely requires it, given how they tend to break UI things I rely upon without recourse, but let's give 71->76 a try…

Strangely enough, the height does get updated with window resizes now. Thanks!
