### ISSUE TITLE
Cannot find documentation for Encrypted Forms

### ISSUE THREAD

**Issue by ovalseven8** [mailvelope/mailvelope#700]
At link to the PDF file at your wiki does not work:
https://github.com/mailvelope/mailvelope/wiki/Encrypted-Forms

**Comment by toberndo** [comment]
I'm not sure why the link is not working. Please try again: https://github.com/mailvelope/mailvelope/wiki/files/Mailvelope-Encrypted-Form-Documentation.v1.2.0.pdf

**Comment by ovalseven8** [comment]
Works, sorry.
