### ISSUE TITLE
The decrypt message box displays [object Object]

### ISSUE THREAD

**Issue by jadair10** [mailvelope/mailvelope#701]
This new version 4.1.0 displays "[object Object]" in the decrypt message box instead of the decrypted message.

**Comment by toberndo** [comment]
Does this happen for all your encrypted messages or only a specific sender? Was the received message encrypted with Mailvelope?

**Comment by ptrinh** [comment]
it happens on all encrypted messages. I was able to decrypt message using Mailvelope but since earlier 2019 I got this issue. Then cannot use anymore.

**Comment by ptrinh** [comment]
<img width="1315" alt="Screenshot 2019-08-27 11 57 56" src="https://user-images.githubusercontent.com/774083/63740014-fff4fe00-c8c1-11e9-80f4-9d116a44e264.png">
<img width="1311" alt="Screenshot 2019-08-27 11 57 44" src="https://user-images.githubusercontent.com/774083/63740015-008d9480-c8c2-11e9-972a-e30fdec9f4d0.png">

**Comment by toberndo** [comment]
Are you in Chrome? Please check if you have activated the chrome://flags/#enable-experimental-web-platform-features (Experimental Web Platform features).

**Comment by ptrinh** [comment]
Yes I did.

<img width="688" alt="Screenshot 2019-08-27 18 02 15" src="https://user-images.githubusercontent.com/774083/63762121-de613a00-c8f4-11e9-8925-55d93009729a.png">

**Comment by toberndo** [comment]
If you disable Experimental Web Platform features then Mailvelope should decrypt correctly. I will work on a fix, to make the process in Mailvelope compatible to Experimental Web Platform features.

**Comment by ptrinh** [comment]
Thanks a lot. It works!

I would suggest to put this notice somewhere in the plugin page while pending for the fix. I wasn't able to use this for half a year because I didn't know about this issue.

**Comment by toberndo** [comment]
Release v4.1.1 fixes one reason for the "[object Object]" output, but there might be others. Please provide feedback if v4.1.1 doesn't solve the problem.

**Comment by jadair10** [comment]
Release v4.1.1, although had a hiccup updating to the new release which was resolved by rebooting my machine (or chrome), fixed the [object Object] issue. I am running chrome dev.

**Comment by toberndo** [comment]
@jadair10 Good to hear :)
