### ISSUE TITLE
Gmail Integration -  Login with Google not working

### ISSUE THREAD

**Issue by rafaelreis-r** [mailvelope/mailvelope#709]
Hey Guys, 

Just decided to try Mailvelope, when enabling Gmail integration and clicking the compose with Mailvelope button, I'm directed to the login page to allow Mailvelope to integrate do my google account. However, after I choose the account, login and password @ google's window, I get a message from Google saying  "login with google temporarily unavailable", app is has not been verified by google to work with Google Login (wording might be slightly different since I'm translating this from my mother tongue). 

![image](https://user-images.githubusercontent.com/57492577/69432263-20ddbb80-0d18-11ea-9cbd-068cbf861f8b.png)

It is not currently possible to use Google integration.

I'm available to do testing and debugging if you need. 

Rafael

**Comment by toberndo** [comment]
We are currently in the verification process of Google. During this phase access to the Gmail API integration in Mailvelope is limited to 100 users. Sorry you didn't make it. Might take some weeks before we get approval.

**Comment by Yexiaoxing** [comment]
Sorry, but is there any update to the Gmail integration? 

Also, would you mind if putting a notice in the preference panel so people can know why there are getting this error?

**Comment by JonTheNiceGuy** [comment]
Just to note, for anyone else catching up - it's still not opened up :(

**Comment by czikus** [comment]
One month later, still no go. What is the prognosis on this issue? Will gmail integration become operational any time soon?

**Comment by rafaelwv** [comment]
Open a ticket and escalate it, this verification process should not take that long.

**Comment by JonTheNiceGuy** [comment]
https://twitter.com/jontheniceguy/status/1234748161559793665 - Maybe this will help?

**Comment by czikus** [comment]
> Open a ticket and escalate it, this verification process should not take that long.

What do you mean exactly? Open the ticket where?

**Comment by rafaelwv** [comment]
Send feedback to oauth-feedback@google.com and see https://support.google.com/cloud/answer/9110914

**Comment by rafaelwv** [comment]
> https://twitter.com/jontheniceguy/status/1234748161559793665 - Maybe this will help?

Mentioned relevant Google accounts and @taviso, let's see if it helps.

**Comment by toberndo** [comment]
Thanks for the joint effort to bring us through the verification process by Google!

Little timeline of the events:

- 14 NOV 19: we initially went into "Review in Progress"
- 20 FEB 20: requested status update from Cloud Platform team. Probably should have done that earlier :(
- 24 FEB 20: Google: please add sign in button
- 4 MAR 20: v4.2.2 adds new sign in button
- 4 MAR 20: Google: not good enough, requests conformance with Google sign in branding guidelines
- 7 MAR 20: v4.2.3 "We have a tremendous button. It's the best sign in button..."
- 9 MAR 20:  Botton seems ok. Status again "Review in Progress"

So apart from the long initial waiting time, I think what we see as response time since end of Feb is ok.

**Comment by toberndo** [comment]
We got approval from Google! Sign in for Gmail accounts is now available :tada:

**Comment by JonTheNiceGuy** [comment]
Great! However, I'm a grandfathered "Google Apps For Your Domain" user (Now called a G Suite account", and I'm getting this message: "Email addresses assigned to a G Suite account are not supported in the current test phase."

![image](https://user-images.githubusercontent.com/228671/76617334-f9f10280-651d-11ea-9dbf-9fe3c6c332ef.png)

I'm not concerned (as I'm sure I'm non-typical), but do you want me to raise that for visibility as a separate "issue", or is it worth tracking it here?

**Comment by rafaelreis-r** [comment]
Seems to be fixed for typical use cases.

**Comment by abampalexnder** [comment]
I have got solution for google after 3 weeks brain storming and spent all day and night time to resolve the issue

any one need solution can contact on wire @abampalxender
