### ISSUE TITLE
Message decryption fails when the signer has no keyId

### ISSUE THREAD

**Issue by pc-coholic** [mailvelope/mailvelope#717]
https://github.com/mailvelope/mailvelope/blob/d8f30f56a30b06e2e7d0120587dc7bf2bc5e6d32/src/components/decrypt-message/DecryptMessage.js#L259-L273

The above referenced code throws a `TypeError`, as it cannot read the property `keyId`, when no such property is included in the `signer`.

Console log:
```javascript
TypeError: Cannot read property 'keyId' of undefined
    at DecryptMessage_DecryptMessage.signatureStatus (decryptMessageRoot.bundle.js:formatted:9300)
    at DecryptMessage_DecryptMessage.render (decryptMessageRoot.bundle.js:formatted:9341)
    at Ne (react-dom.js:103)
    at Bh (react-dom.js:103)
    at Lj (react-dom.js:230)
    at $h (react-dom.js:137)
    at Fj (react-dom.js:137)
    at We (react-dom.js:132)
    at react-dom.js:60
    at unstable_runWithPriority (react.js:25)
```

Content of `DecryptMessage_DecryptMessage`'s this.props:
```json
{
   "id":"e3fbdf78141951da320e6f4c",
   "embedded":false
}
```

Content of `DecryptMessage_DecryptMessage`'s this.state:
```json
{
   "message":"[redacted]",
   "signer":{
      "fingerprint":"60667a5c97363ae2bf16c90ce1f56ce6693f9c45",
      "valid":null
   },
   "showSig":false,
   "waiting":false,
   "locked":false,
   "clearText":false,
   "files":[

   ],
   "encFiles":[

   ],
   "notification":null,
   "showNotification":false,
   "pwdDialog":null,
   "terminate":false,
   "signatureToolTipOpen":false,
   "large":false
}
```

A possible band-aid would be to add 
```javascript
    if (typeof(this.state.signer.keyDetails == "undefined")) {
        this.state.signer.keyDetails = Object();
        this.state.signer.keyDetails.keyId = "";
    }
```

to `signatureStatus()` - but that's probably not the best way to handle this.

If necessary, I can provide messages triggering this error.

Mailvelope version: 4.2.1
Chrome: 80.0.3987.106
Backend: GnuPG
OS: Linux

**Comment by toberndo** [comment]
Thanks for the detailed analysis!
Fixed with: https://github.com/mailvelope/mailvelope/commit/db0280b622d58b3f89713cdbfc185d1601984680
You can test with this build: https://build.mailvelope.com/nightly/mailvelope.latest.chrome.zip

**Comment by pc-coholic** [comment]
Works like a charm - Thank you very much for the quick fix!

-------------------

(On an unrelated note: the GMail-Integration also works fine on GSuite accounts, when removing the check in the codebase *and* manually designating Mailvelope as a trusted 3rd party app on the admin console... :-) )

**Comment by drzraf** [comment]
@pc-coholic : Where is this check? I've to remove this arbitrary restriction.

**Comment by pc-coholic** [comment]
It used to be a simple check - but now they extended it into a whole license check and whatnot...

While I do think this is really sucky, since I have a legacy GSuite account but am not a business (and cannot revert back to a regular GMail account). But I won't go out here and discuss circumventing their licensing checks.

But perhaps @toberndo might be open to flagging legacy GSuite-accounts as regular free users, too... I at least would appreciate it :)

**Comment by toberndo** [comment]
See https://github.com/mailvelope/mailvelope/issues/724#issuecomment-610944223. @pc-coholic your are a contributor, right? ;)

**Comment by toberndo** [comment]
Some background info on the subscription model: as the name implies we are clearly aiming at non-private users for the Mailvelope Business subscription, but the problem is that from a browser extension perspective we cannot distinguish between a G Suite and a Google Apps account. That's why currently only the normal Gmail accounts are free. We have not yet decided how to deal with this topic. But as I said in my linked comment, we have established a free plan for contributors. And until there is a final decision we will apply a quite broad definition on what is a contributor. So if you want to be part of this contributor plan just send us an email.
