### ISSUE TITLE
Id token invalid!

### ISSUE THREAD

**Issue by AdriDevelopsThings** [mailvelope/mailvelope#752]
Hello,

I want to use G-Mail Integration. When I click on the mailvelope button next to the Gmail write button, redirecting to the mailvelope google login site. When I am redirected back, I get this error: 
![image](https://user-images.githubusercontent.com/45321107/100265914-dc978380-2f48-11eb-9a85-1884f6f77f34.png)

I hope you can help me!

Best regards,

AdriBloober

**Comment by toberndo** [comment]
Can you go to the Gmail-API settings in Mailvelope, remove the entry for your email address and redo the authorization step?
