### ISSUE TITLE
increase sizelimit for attachments 

### ISSUE THREAD

**Issue by deepee2** [mailvelope/mailvelope#760]
Chrome 87 + Mailvelope 4.4.0

* I use De-Mail and want to add an attachment with 6 MB -> error message with max size of 4 MB is allowed 
![create-mail-sizelimit](https://user-images.githubusercontent.com/11028366/104579525-58b26b80-565c-11eb-9534-81ac92e75826.png)

* if an pgp mail with an attachment larger than 4 MB is received -> mail can not be opened and script error appears 

* is there a way to increase the size limit of the attachments to encrypt / decrypt of the iframe? (the plugin itself allows files up to 50 MB, see https://www.mailvelope.com/en/faq#attachments)

**Comment by toberndo** [comment]
This is a limit set by your De-Mail provider. Here is the `quota` parameter in the Mailvelope client-API: https://mailvelope.github.io/mailvelope/global.html#EditorContainerOptions__anchor

**Comment by deepee2** [comment]
thx
