### ISSUE TITLE
OpenPGP/MIME decryption not working in Fastmail

### ISSUE THREAD

**Issue by eloquence** [mailvelope/mailvelope#780]
At @freedomofpress we recently switched to Fastmail, which has a pretty decent web app. After enabling the fastmail.com domain, I can send encrypted messages. Decryption is proving more tricky. OpenPGP/MIME messages don't seem to be detected by Mailvelope (latest Firefox version). Here's an example of a message source.

Mailvelope is active for the domain but no decryption options are displayed; the attachment just shows up as `encrypted.asc`. I can decrypt it in Mailvelope manually via copy/paste after downloading it, but that defeats much of the point of a browser-based integration.

I realize Fastmail is not currently listed as a supported provider (though the Fastmail folks do recommend Mailvelope on https://fastmail.blog/advanced/pgp-tools-with-fastmail/). Is this a supported use case?

```
This is an OpenPGP/MIME encrypted message (RFC 2440 and 3156)
----==_mimepart_617b2e76bb390_360a2ac35b17c4e4280887
Content-Type: application/pgp-encrypted
Content-Transfer-Encoding: 7bit
Content-Description: PGP/MIME Versions Identification

Version: 1
----==_mimepart_617b2e76bb390_360a2ac35b17c4e4280887
Content-Type: application/octet-stream;
 name=encrypted.asc
Content-Transfer-Encoding: 7bit
Content-Disposition: inline;
 filename=encrypted.asc
Content-Description: OpenPGP encrypted message
Content-ID: <617b2e7761c46_360a2ac35b17c4e4281324@redmine.mail>

-----BEGIN PGP MESSAGE-----

<snip>

-----END PGP MESSAGE-----

----==_mimepart_617b2e76bb390_360a2ac35b17c4e4280887--
```

**Comment by eloquence** [comment]
Thanks @toberndo; I've opened a ticket with Fastmail support in case they are interested in expanding Mailvelope support.

**Comment by julianwachholz** [comment]
@eloquence just out of curiousity, did you receive a reply about this from Fastmail?
