### ISSUE TITLE
Can not decrypt message compressed with Bzip2

### ISSUE THREAD

**Issue by hypatia1** [mailvelope/mailvelope#8]
I have imported my gmail private key to mailvelope. I can not decrypt email sent from a enigmail on thunderbird. Mailvelope prompts me for my pass phrase, but when I click "OK" nothing happens. The prompt remains. There is no indication that the pass phrase is incorrect. I can click cancel.

I know that the message is OK because I can decrypt it with gpg on the command line.
The GPG header for the message is:

-----BEGIN PGP MESSAGE-----
Version: GnuPG v1.4.8 (Darwin)

Mail sent from gmail/mailvelope is not recognized as being encrypted by t-bird/enigmail, but again, I can decrypt it on the command line.

System Info:
MacOS 10.6.8
Thunderbird 16.0.2
GnuPG 1.4.8

**Comment by jinnko** [comment]
OpenPGPjs [added support for bzip2 in v3.0.11](https://github.com/openpgpjs/openpgpjs/commit/fa2672fcc15fe3667d132919490e5d88dd71fa7c).  Looks like [Mailvelope is still using v2.5.x](https://github.com/mailvelope/mailvelope/blob/master/package.json#L28).

**Comment by toberndo** [comment]
Update to OpenPGP.js 4.2 in Mailvelope 3.0 also brought bzip2 support (decompression only).
