### ISSUE TITLE
Nextcloud Mail App Not Working With Mailvelope

### ISSUE THREAD

**Issue by zohaib09** [mailvelope/mailvelope#806]
Hi

This app is not working in our Nextcloud Mail app. We have added our NC domain into authorized domain. After composing email, click on encrypt it shows email body unecrypted.

NC: 24
Mailvelope: 4.6.1
Mail app: 1.13.8

**Comment by systemplatine** [comment]
Hi zohaib09,

are you sure, you inserted the text within the Mailvelope-Editor (opens when you click the mailvelope icon within the usual composing-editor)?
Even the developers of the Nextcloud Mail App state, that Mailvelope should work: https://apps.nextcloud.com/apps/mail
You could also have a try and ask them about your problem, as I don’t have a Nextcloud instance running here for testing...

Bernhard
——
Mailvelope Communication Manager

**Comment by zohaib09** [comment]
Hi

Thank you for your reply, yes offcourse i inserted text in Mailveope-Editor, it prompts icon during composing new email. Added recipient, then click on encrypt it prompt me for password then i enter password to sign email then email body there. It is perfectly working for gmail, and our zimbra webmail.

**Comment by ChristophWurst** [comment]
There was a bug when formatting is turned on. This is fixed as of today: https://github.com/nextcloud/mail/pull/7558

**Comment by dolphinscorp** [comment]
Thank you it works !

**Comment by NoSubstitute** [comment]
Perhaps this can be closed, if it was fixed two years ago?
