### ISSUE TITLE
Roundcube doesn't seem to work with the Firefox addon

### ISSUE THREAD

**Issue by AmyMoriyama** [mailvelope/mailvelope#807]
I've tried everything I could think of and read every howto I could find, and the addon just doesn't work in my browser with the roundcube webmail on my cpanel (namecheap). Is this a bug or is there other things that can be tried?

I've made sure to update the addon from the releases page on here. 

Name: LibreWolf (AppImage)
Version: 105.0.1
Build ID: 20220924101334
Distribution ID: io.gitlab.librewolf-community
User Agent: Mozilla/5.0 (X11; Linux x86_64; rv:105.0) Gecko/20100101 LibreWolf/105.0.1
OS: Linux 5.19.0-14.1-liquorix-amd64 #1 ZEN SMP PREEMPT_DYNAMIC liquorix 5.19-17.1~bullseye

Mailvelope 4.6.1

Roundcube Webmail 1.4.12

**Comment by AmyMoriyama** [comment]
Tried on a regular Firefox, same thing. It doesn't work by not doing any sort of altering of the roundcube interface, basically making it not usable in roundcube.

**Comment by systemplatine** [comment]
Thanks for trying! Are you sure you authorized the domain you’re working on with roundcube, like it is described here in our “Getting started” for Roundcube (See Chapter 5)? Otherwise Mailvelope can't know that this is a site it should interact with.

**Comment by systemplatine** [comment]
Sorry, forgot to add the link: https://mailvelope.com/en/help

**Comment by AmyMoriyama** [comment]
This is what I have..

![Screenshot_2022-10-11_06-28-00](https://user-images.githubusercontent.com/87048190/195067334-eea85f41-82c5-499a-970e-bac12cc33e9f.png)
![Screenshot_2022-10-11_06-28-43](https://user-images.githubusercontent.com/87048190/195067547-fb8069aa-81bf-43ef-b4d7-1fef107b54f5.png)

**Comment by systemplatine** [comment]
Thanks for the screenshots! Try to add the port number under “Domain pattern”. It should read: *.premium183.web-hosting.com:2096 <http://premium183.web-hosting.com:2096/>
Working now?

**Comment by AmyMoriyama** [comment]
Adding the port fixed it, thank you.
