### ISSUE TITLE
[Feature Request] Add cross-browser account synchronization.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [mailvelope/mailvelope#809]
I'd like my keys to be synchronized across browsers, so https://github.com/mailvelope/mailvelope/issues/99 and https://github.com/mailvelope/mailvelope/issues/204 are inadequate. I see no reason why this should be manual.

**Comment by rimmer** [comment]
While the idea is great, the implementation without compromising security would be quite complex. I don't thing we could tackle this ourselves in near future. However, if you have ideas on implementation and maybe even willing to help, it would be highly appreciated.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/mailvelope/mailvelope/issues/809#issuecomment-2334385200

@rimmer, any assistance I could offer probably wouldn't be of much use - I'm unfortunately only able to develop in a few languages irrelevant to those codebase. However, if you were to implement an account system, basing it upon OAuth tokens from other account systems (like Medium does) would mean you don't have to worry nearly as much about storing personal data.

**Comment by rimmer** [comment]
If I take off my hat of Mailvelope team member and speak as an engineer and a user, I wouldn't be happy to have my **personal** keys stored somewhere unencrypted and accessible with a third-party OAuth. If I use for instance Google Account OAuth, then if my Google Account is compromised, the attacker has access to my keys too. 

I don't say it is impossible, but it is harder to implement with privacy and security in mind. I am closing this as for now, for this might come up in a different shape of form later.

**Comment by RokeJulianLockhart** [comment]
> If I use for instance Google Account OAuth, then if my Google Account is compromised, the attacker has access to my keys too.

@rimmer, surely if your account is compromised, that would be expected? If an account protected by 2FA is compromised, then you've already a very, very significant breach of security. Additionally, monolithic account services like Microsoft's and Google's provide e-mail and password management, protected by a single authentication system.

**Comment by rimmer** [comment]
> > If I use for instance Google Account OAuth, then if my Google Account is compromised, the attacker has access to my keys too.
> 
> @rimmer, surely if your account is compromised, that would be expected? If an account protected by 2FA is compromised, then you've already a very, very significant breach of security. Additionally, monolithic account services like Microsoft's and Google's provide e-mail and password management, protected by a single authentication system.

What I am trying to say is that the software besides the functionality also carries an idea. We are building Mailvelope around zero-trust mindset, so offering to store their private keys on a remote server that they have to trust isn't particularly nice. 
I don't say it is impossible, but it has to have an additional level of security above authentication, keys should be encrypted etc, and all this should be opensourced ofc. I believe there might be some interest for this feature from the corporate, and then it makes more sense but due to the different reasons. 

Nevertheless, we have plans to pay more attention how users store and backup their keys. 

> I presume that this consequently hasn't been implemented, so I also presume it would be better closed as unplanned than completed.

Absolutely, wrong button 😊 . Thank you!
