### ISSUE TITLE
Version of the Mailvelope extension in the Firefox Browser Add-ons is out of date.

### ISSUE THREAD

**Issue by rafaelrandom** [mailvelope/mailvelope#810]
Hello everyone, the version of Mailvelope on the Firefox extensions store is out of date, while there the version is still 4.2.3, last updated on March 5, 2020, the current version here on Github is already 4.7.1. In the edge add-on store and chrome web store the version is up to date, so would it be possible to load version 4.7.1 for Firefox Browser Add-ons?

**Comment by meanssaddles** [comment]
to added: it's not a problem for firefox desktop since it can be install directly from github but firefox android can only update via amo (firefox extension hub) so it is outdated
