### ISSUE TITLE
Firefox artifact missing from 5.0.0 github release

### ISSUE THREAD

**Issue by daurnimator** [mailvelope/mailvelope#813]
The 5.0.0 release is missing a `mailvelope.firefox.xpi` (as well as other files including signatures):

![image](https://user-images.githubusercontent.com/127971/230752789-fb76f84f-5fcb-4319-9801-c4a6e3207709.png)

**Comment by daurnimator** [comment]
This is also an issue with 5.0.1:
![image](https://user-images.githubusercontent.com/127971/233225580-13c7bdb6-d5cb-4a3f-b7f4-19bf70febfcd.png)

**Comment by toberndo** [comment]
We currently don't have a signed XPI for version 5 of Mailvelope. This is probably fixed soon, once we have made it again through the AMO review process. Until then you can download the latest available version (4.7.1) at: https://download.mailvelope.com/releases/v4.7.1/mailvelope.firefox.xpi

**Comment by daurnimator** [comment]
@toberndo could you upload it before the AMO process is complete.
=> I want it for updating https://archlinux.org/packages/community/any/firefox-extension-mailvelope/

**Comment by toberndo** [comment]
We first have to go through the review process, otherwise we won't get a signed XPI package from Mozilla.

**Comment by toberndo** [comment]
`mailvelope.firefox.xpi` is now available at https://github.com/mailvelope/mailvelope/releases/tag/v5.0.1

**Comment by eleius** [comment]
Firefox artifact is missing again for 5.1.0

**Comment by toberndo** [comment]
<img width="974" alt="image" src="https://github.com/mailvelope/mailvelope/assets/1164474/a333b336-3830-46fa-b4e5-a09a0ede23bc">

**Comment by toberndo** [comment]
xpi now available for 5.1.0
