### ISSUE TITLE
[Bug] Unable to use Gmail API integration.

### ISSUE THREAD

**Issue by rokejulianlockhart** [mailvelope/mailvelope#815]
![image](https://user-images.githubusercontent.com/42837531/233390591-88af7812-02e3-4065-9413-3194213c015e.png)
https://support.google.com/accounts/answer/12379384

![image](https://user-images.githubusercontent.com/42837531/233390733-42738eba-1b3d-4f2c-96fa-4ae10aea0e1e.png)
https://developers.google.com/identity/protocols/oauth2/resources/oob-migration

Potentially caused by https://github.com/mailvelope/mailvelope/issues/810#issue-1593637886.

**Comment by systemplatine** [comment]
Mailvelope version in AMO is outdated. Update manually to Mailvelope v5.0.1 https://download.mailvelope.com/releases/v5.0.1/
More here: https://github.com/mailvelope/mailvelope/issues/813#issuecomment-1515537862

**Comment by rokejulianlockhart** [comment]
Thanks, @systemplatine, but I'll just wait. I'm not going to bother to manually manage an extension.

**Comment by toberndo** [comment]
Version 5.0.1 for Firefox is now available at https://addons.mozilla.org/addon/mailvelope/
