### ISSUE TITLE
enable by default "Use keys from Autocrypt headers of incoming email"

### ISSUE THREAD

**Issue by monperrus** [mailvelope/mailvelope#816]
Sharing keys via Autocrypt headers is great.

Lots of email clients do so incl. Tunderbird and Deltachat.

What about enabling by default "Use keys from Autocrypt headers of incoming email"?

**Comment by toberndo** [comment]
For Autocrypt to work we need support from the mail provider. Mailvelope offers Autocrypt functionality as part of its client-API and a webmail client that is using the client-API could use Mailvelope to generate the Autocrypt headers. But to my knowledge there is not a single mail provider/client that is actively using the Autocrypt part of the client-API. Therefore we keep this option disabled by default until there is a significant interest from mail provider/clients.

**Comment by monperrus** [comment]
thanks for the explanation.

what's the status of sending the key via autocrypt in outgoing emails?
