### ISSUE TITLE
Sender can decrypt a message

### ISSUE THREAD

**Issue by namhoang1999** [mailvelope/mailvelope#817]
I just found out that the sender can decrypt a message that was encrypted with the recipient's public key.

So I first encrypt an arbitrary message (both works with/without the signature). I copied the encrypted message to the decryption section. Then a message popup asking for the password to the **sender's key**, I entered my password and it did decrypt it.

This is probably trivial since the sender knows the message content anyway, but why is the sender allowed to do this? and why is the sender's key used? AFAIK PKC can only decrypt a message with the recipient's private key. Please let me know if i'm understanding anything wrong.

**Comment by toberndo** [comment]
![image](https://github.com/mailvelope/mailvelope/assets/1164474/54d37278-8805-44b1-947f-6d4a059456da)

You can use this setting if you do not want to encrypt messages with your default key.
