### ISSUE TITLE
Speed up the workflow

### ISSUE THREAD

**Issue by yannickoo** [mailvelope/mailvelope#82]
Mailvelope is an awesome extensions but one think is a big downside: time.

I need 4 seconds to write a short email (Gmail):
1. Click "Compose"
2. Enter recipient
3. Enter subject
4. Write message
5. CMD+Enter (Send)

With Mailvelope I it's costlier (11 seconds):
1. Click "Compose"
2. Enter recipient
3. Enter subject
4. Click the lock icon
5. Enter text
6. Click the other lock icon
7. Select recipient from select list
8. Click "Add"
9. Click "Ok"
10. Click "Transfer"
11. CMD+Enter (Send)

It would be faster if there wouldn't be these animations and transitions. Another benefit would be fixing #52.

Should we split that into multiple issues? So I would create a new issue for the animation stuff.

Remaining issues:
1. #52 
2. #81

**Comment by toberndo** [comment]
With automatic recipient transfer for major providers and the new recipient input field in the editor workflow has much improved since this issue has been reported. Closing.
