### ISSUE TITLE
Can't open encypted emails on Yahoo Mail

### ISSUE THREAD

**Issue by Anutrix** [mailvelope/mailvelope#821]
The emails (same thread/subject) on Yahoomail recently show up as empty email with 2 attachments: `Untitled` and `encrypted.asc`.

![image](https://github.com/mailvelope/mailvelope/assets/11459028/cdc4116a-2d9c-4460-8f9d-aad70d949120)

**Comment by masterjg** [comment]
Very similar issue in Nextcloud Mail with mailbox.org as backend server
![Screenshot from 2023-09-20 21-45-36](https://github.com/mailvelope/mailvelope/assets/11464772/ea2f75a6-0e6c-407f-a2c1-53d8bdd27370)

**Comment by masterjg** [comment]
Anyone has any clues on how to fix it?

**Comment by johseg** [comment]
I have the same problem on mailbox.org. Since ~2 weeks I see the mails as empty and mailvelope doesn't allow me to open it. The mail as text file looks fine and contains gpg data

**Comment by johseg** [comment]
It works for mails that have
Content-Type: multipart/encrypted; protocol="application/pgp-encrypted"
and does not work for mails that have
Content-Type: text/plain; charset="utf-8"
which my bank is using. That used to work. I'll have a look in the git log to see if anything changed in that regard

**Comment by johseg** [comment]
also doesn't work with Mailvelope 5.0.1, and in April this definitely it worked for me. So I think this is something in my local setup/a chrome change

**Comment by systemplatine** [comment]
> Very similar issue in Nextcloud Mail with mailbox.org as backend server ![Screenshot from 2023-09-20 21-45-36](https://private-user-images.githubusercontent.com/11464772/269387378-ea2f75a6-0e6c-407f-a2c1-53d8bdd27370.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzNDg2ODIsIm5iZiI6MTcwMTM0ODM4MiwicGF0aCI6Ii8xMTQ2NDc3Mi8yNjkzODczNzgtZWEyZjc1YTYtMGU2Yy00MDdmLWEyYzEtNTNkOGJkZDI3MzcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTMwVDEyNDYyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyN2UyNTM4YzRjY2M1NTYzM2Q3YmM5ZTkwN2I1ZDc1ODBlYzk5MThhMmYxMDY0OWU1MmE3ODFhOWNhYTQ4MWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8cXhSqPni4Ha_45RWmCuTzbl1V6rGq-Bc229ilqkBHU)

As far as I know Nextcloud Mail has the possibility to turn API connection with Mailvelope on. Could you check if this is the case? If not, then you have the same problem with PGP/MIME as @Anutrix. If so, then this indicates that Nextcloud Mail is not recognizing the PGP/MIME message correctly.

**Comment by systemplatine** [comment]
@johseg Looks like mailbox.org is having a problem supporting PGP/Inline at the moment. We tried to get in contact with mailbox.org on this issue and it would maybe help if you as a user also contact them on this.

**Comment by johseg** [comment]
I've opened a ticket with mailbox.org and will report back when they reply

**Comment by johseg** [comment]
mailbox.org confirmed that they can reproduce this and will get back to me with more information

**Comment by johseg** [comment]
The workaround is to open a ticket with them and have S/MIME deactivated, then it works again. So at least for mailbox.org this can be closed, as this isn't an issue with mailvelope

**Comment by systemplatine** [comment]
> The emails (same thread/subject) on Yahoomail recently show up as empty email with 2 attachments: `Untitled` and `encrypted.asc`.
> 
> ![image](https://private-user-images.githubusercontent.com/11459028/269025420-cdc4116a-2d9c-4460-8f9d-aad70d949120.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1NTUyNjcsIm5iZiI6MTcwMjU1NDk2NywicGF0aCI6Ii8xMTQ1OTAyOC8yNjkwMjU0MjAtY2RjNDExNmEtMmQ5Yy00NDYwLThmOWQtYWFkNzBkOTQ5MTIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDExNTYwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxOTRhMmU0ODJlNDQ0MjJkNTZiMDk4NTVlYTZiNzMzNjAwMmMzZmZlYzc4MjAwMGM4MWNmOGU2NWU0NzJlNzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nf4dp1LYJ0lhxmNrRyH5KnUNJyfQGZxGVg9tpWkEiLM)

It looks to me like the broadcaster changed the format and may have sent PGP/Inline beforehand. We have no influence on how PGP/MIME messages get displayed by webmail provider as long as we don't have  access to API . The problem would have also occurred with an older Mailvelope version.
