### ISSUE TITLE
Mailvelope does not detect encrypted messages in current version of outlook web access (OWA)

### ISSUE THREAD

**Issue by childen** [mailvelope/mailvelope#826]
Mailvelope does not seem to detect and decrypt received or sent messages in the current version of OWA.

Even with Mailvelope enabled encrypted sent emails are displayed with an empty text and a single attachment "ATT00001". 

Received signed and encrypted emails are displayed with empty text two attachments "PGP/MIME version identification" and "OpenPGP encrypted message.asc".

Please let me know if there is anything I can do to help fix this.

**Comment by systemplatine** [comment]
We're currently having a look on this problem. Can't reproduce it on Outlook(OWA) when sending form Gmail, but  certainly when using Thunderbird PGP capabilities to send to Outlook. We will keep you informed.

**Comment by systemplatine** [comment]
Since we currently do not have the option to directly access the Outlook API, we are not able to solve the problem as we cannot change the way Outlook behaves in this case. However, an Outlook API interface is planned for 2024.
