### ISSUE TITLE
Warn user if no other email address is selected as recipient

### ISSUE THREAD

**Issue by yannickoo** [mailvelope/mailvelope#83]
If you enable _Always add primary key to list of recipients. (Allows to decrypt sent mails)_ in the "General" settings you won't get a notification that your message cannot read be other because you dind't select another recipient.

As long as #52 is not fixed this is a major issue and it is a pain to re-send the email with the right recipient's public key included ;(

**Comment by toberndo** [comment]
This is fixed with the new recipient input in the editor.
