### ISSUE TITLE
Refresh GnuPG Keyring cause duplicate entry

### ISSUE THREAD

**Issue by zhiyan114** [mailvelope/mailvelope#832]
It seems like if you try to use the `refresh` button GnuPG keyring option, it will generate duplicate entry. There's also no way to delete the duplicate entry, so the only way to remove them is by reinstalling the extension.

Screenshot below shows the duplicate entry after using the `refresh` button:
![image](https://github.com/mailvelope/mailvelope/assets/20156291/bf70b90c-6821-4b65-b222-0b888d56484c)

EDIT: I would like to mention that disable and re-enabling the extension can also resolve the issue, but it's not a very "user friendly" approach.

**Comment by ksaveras** [comment]
The same happened to me. Now I have six same entries :(

**Comment by gmax9803** [comment]
+1, this is still an issue

**Comment by toberndo** [comment]
Fixed in dev branch (https://github.com/mailvelope/mailvelope/commit/f9f740f28bc1045ffa07a02dff21fe3833a0e72e), comes with next release.

**Comment by toberndo** [comment]
Now available with release v5.2.0
