### ISSUE TITLE
mailvelope in Firefox can't detect GnuPG

### ISSUE THREAD

**Issue by SuperdukeGates** [mailvelope/mailvelope#837]
I'm in Windows 10 and run the Firefox 125.0.1. I installed the mailvelope 5.1.2 to the Firefox. I also installed the Gpg4win 4.3.0 (unprivileged user).

On the OpenPGP Preferences of the mailvelope, it says "You are currently using **OpenPGP.js**" and "**GnuPG is not available**   Do you have GnuPG installed? ...."

**Comment by rimmer** [comment]
@SuperdukeGates did you follow the steps here https://github.com/mailvelope/mailvelope/wiki/Mailvelope-GnuPG-integration ?

**Comment by rimmer** [comment]
I actually stubled upon the same issue and spend several hours trying to resolve it until I found the [wiki page](/mailvelope/mailvelope/wiki/Mailvelope-GnuPG-integration).
I believe the user simply should be better informed about the required steps. 
I would suggest simply adding this wiki to the option description in the options UI.

**Comment by toberndo** [comment]
https://github.com/mailvelope/mailvelope/pull/840 is now released with v5.2.0
