### ISSUE TITLE
Printing encrypted emails

### ISSUE THREAD

**Issue by blap-o** [mailvelope/mailvelope#843]
I've just started experimenting Mailvelope in Gmail and have come up against an issue I can't figure out:

From time to time, I need to make a PDF backups of some emails I receive. This works fine if the message is unencrypted in Gmail.

But when I try to "print to pdf" decrypted Mailvelope messages, they are usually cut off if they are "bigger" than one a4 page.

This is is how I'm trying to print (Firefox Browser):

1- Right click decrypted message, select "This Frame" -> Print Frame
2 - Message shows up ready to be printed to pdf but if the message is too long or has a lot of graphics, it gets cut off and not all of the content gets printed to pdf

Is there a correct way to print to pdf with Mailvelope?

Or is there some limitation due to security issues that will not allow "proper" print to pdf?

**Comment by systemplatine** [comment]
As printing is browser specific, you should try also with another browser. You also tried to copy the contents of the email and paste them into some sort of text editor before printing from there?
