### ISSUE TITLE
Problem importing locally generated keys using gpg

### ISSUE THREAD

**Issue by excited-bore** [mailvelope/mailvelope#848]
I have trouble decrypting messages from mailvelope verification mails in thunderbird. 
I've made a key-pair using gpg, imported it into the thunderbird and into mailvelope. I'm able to decrypt messages using a different mailaccount when sending from thunderbird, but I cannot seem to decrypt mailvelope's verification mail.
I've checked fingerprints but they match completely. What am I doing wrong?
EDIT: I want to add that I hadn't configured mailvelope to work with GPG when I generated the keys
EDIT2: I might have misunderstood how to properly import secret keys into thunderbird. Finally succeeded by understanding that you need to specifically 'Import secret keys from file', not from clipboard or any other way

**Comment by rimmer** [comment]
Hi, thanks for filing an issue. 
Let me try to understand: so the issue is/was with decrypting a verification mail from mailvelope keyserver **in thunderbird**?
