### ISSUE TITLE
Compatibility with manifest v3

### ISSUE THREAD

**Issue by Plaschke-Culturall** [mailvelope/mailvelope#862]
Chrome is displaying a warning that this extension may be unsupported soon and it is getting deactivated automatically.
This is because of the deprecation of chrome extensions with manifest v2.

https://www.theverge.com/2024/10/15/24270981/google-chrome-ublock-origin-phaseout-manifest-v3-ad-blocker
https://derstandard.at/story/3000000241054/ublock-origin-google-deaktiviert-beliebten-werbeblocker-fuer-chrome

Is there going to be a version of Mailvelope that supports manifest v3 soon?

When is this expected to be published?

**Comment by toberndo** [comment]
Development for manifest v3 happens in https://github.com/mailvelope/mailvelope/tree/manifest-v3
We are currently doing some final testing and will probably publish next week.
