### ISSUE TITLE
Cannot decrypt emails on Firefox

### ISSUE THREAD

**Issue by DavidEGx** [mailvelope/mailvelope#87]
## Description

Cannot decrypt emails (gmail) on Firefox.
## Steps to reproduce
1. Open a encrypted message on gmail.
2. Click on the envelope + lock icon that appears.
   Icon moves to the left and change to a open envelope but the text is not visible and there is no popup asking for the passphrase.
## Expected result

Works same way as in chrome.
A popup asking for the passphrase should appear and after introducing it the email text should be visible.
## Environment

Last mailvelope on github (1c85354470501fe23a45fadc2b4e1e736b4b2dee).
- Firefox 21 under Debian Squeeze.
- Firefox 23 under Windows XP.
  Same result on both.

**Comment by dotnetCarpenter** [comment]
Mailvelope: 1.3.2

@toberndo I got a similar or the same issue.
In Options -> Security -> Where are decrypted messages displayed?
check -> In a separate popup from Mailvelope.

I'm on Windows7, using Firefox 42.0. When I hover over the firefox icon in the taskbar, I can see a Mailevelope window but when I click on it, it disappear.

![mailevelope](https://cloud.githubusercontent.com/assets/43763/11758621/98637ec2-a06d-11e5-9410-4f6c8112c7b9.png)

**Comment by dotnetCarpenter** [comment]
I found a temporary work-around. Find I hover over the Mailvelope image in the taskbar, I can right-click and choose Maximize. It then opens the window and I can edit and send mail.
